// This file is generated. Do not edit!
// see https://github.com/hpvb/dynload-wrapper for details
// generated by generate-wrapper.py 0.7 on 2026-03-13 16:28:20
// flags: generate-wrapper.py --include /home/build/github/godot/thirdparty/linuxbsd_headers/X11/Xcursor/Xcursor.h --sys-include thirdparty/linuxbsd_headers/X11/Xcursor/Xcursor.h --soname libXcursor.so.1 --init-name xcursor --output-header /home/build/github/godot/platform/linuxbsd/x11/dynwrappers/xcursor-so_wrap.h --output-implementation /home/build/github/godot/platform/linuxbsd/x11/dynwrappers/xcursor-so_wrap.c --ignore-other
//
#include <stdint.h>

#define XcursorImageCreate XcursorImageCreate_dylibloader_orig_xcursor
#define XcursorImageDestroy XcursorImageDestroy_dylibloader_orig_xcursor
#define XcursorImagesCreate XcursorImagesCreate_dylibloader_orig_xcursor
#define XcursorImagesDestroy XcursorImagesDestroy_dylibloader_orig_xcursor
#define XcursorImagesSetName XcursorImagesSetName_dylibloader_orig_xcursor
#define XcursorCursorsCreate XcursorCursorsCreate_dylibloader_orig_xcursor
#define XcursorCursorsDestroy XcursorCursorsDestroy_dylibloader_orig_xcursor
#define XcursorAnimateCreate XcursorAnimateCreate_dylibloader_orig_xcursor
#define XcursorAnimateDestroy XcursorAnimateDestroy_dylibloader_orig_xcursor
#define XcursorAnimateNext XcursorAnimateNext_dylibloader_orig_xcursor
#define XcursorCommentCreate XcursorCommentCreate_dylibloader_orig_xcursor
#define XcursorCommentDestroy XcursorCommentDestroy_dylibloader_orig_xcursor
#define XcursorCommentsCreate XcursorCommentsCreate_dylibloader_orig_xcursor
#define XcursorCommentsDestroy XcursorCommentsDestroy_dylibloader_orig_xcursor
#define XcursorXcFileLoadImage XcursorXcFileLoadImage_dylibloader_orig_xcursor
#define XcursorXcFileLoadImages XcursorXcFileLoadImages_dylibloader_orig_xcursor
#define XcursorXcFileLoadAllImages XcursorXcFileLoadAllImages_dylibloader_orig_xcursor
#define XcursorXcFileLoad XcursorXcFileLoad_dylibloader_orig_xcursor
#define XcursorXcFileSave XcursorXcFileSave_dylibloader_orig_xcursor
#define XcursorFileLoadImage XcursorFileLoadImage_dylibloader_orig_xcursor
#define XcursorFileLoadImages XcursorFileLoadImages_dylibloader_orig_xcursor
#define XcursorFileLoadAllImages XcursorFileLoadAllImages_dylibloader_orig_xcursor
#define XcursorFileLoad XcursorFileLoad_dylibloader_orig_xcursor
#define XcursorFileSaveImages XcursorFileSaveImages_dylibloader_orig_xcursor
#define XcursorFileSave XcursorFileSave_dylibloader_orig_xcursor
#define XcursorFilenameLoadImage XcursorFilenameLoadImage_dylibloader_orig_xcursor
#define XcursorFilenameLoadImages XcursorFilenameLoadImages_dylibloader_orig_xcursor
#define XcursorFilenameLoadAllImages XcursorFilenameLoadAllImages_dylibloader_orig_xcursor
#define XcursorFilenameLoad XcursorFilenameLoad_dylibloader_orig_xcursor
#define XcursorFilenameSaveImages XcursorFilenameSaveImages_dylibloader_orig_xcursor
#define XcursorFilenameSave XcursorFilenameSave_dylibloader_orig_xcursor
#define XcursorLibraryLoadImage XcursorLibraryLoadImage_dylibloader_orig_xcursor
#define XcursorLibraryLoadImages XcursorLibraryLoadImages_dylibloader_orig_xcursor
#define XcursorLibraryPath XcursorLibraryPath_dylibloader_orig_xcursor
#define XcursorLibraryShape XcursorLibraryShape_dylibloader_orig_xcursor
#define XcursorImageLoadCursor XcursorImageLoadCursor_dylibloader_orig_xcursor
#define XcursorImagesLoadCursors XcursorImagesLoadCursors_dylibloader_orig_xcursor
#define XcursorImagesLoadCursor XcursorImagesLoadCursor_dylibloader_orig_xcursor
#define XcursorFilenameLoadCursor XcursorFilenameLoadCursor_dylibloader_orig_xcursor
#define XcursorFilenameLoadCursors XcursorFilenameLoadCursors_dylibloader_orig_xcursor
#define XcursorLibraryLoadCursor XcursorLibraryLoadCursor_dylibloader_orig_xcursor
#define XcursorLibraryLoadCursors XcursorLibraryLoadCursors_dylibloader_orig_xcursor
#define XcursorShapeLoadImage XcursorShapeLoadImage_dylibloader_orig_xcursor
#define XcursorShapeLoadImages XcursorShapeLoadImages_dylibloader_orig_xcursor
#define XcursorShapeLoadCursor XcursorShapeLoadCursor_dylibloader_orig_xcursor
#define XcursorShapeLoadCursors XcursorShapeLoadCursors_dylibloader_orig_xcursor
#define XcursorTryShapeCursor XcursorTryShapeCursor_dylibloader_orig_xcursor
#define XcursorNoticeCreateBitmap XcursorNoticeCreateBitmap_dylibloader_orig_xcursor
#define XcursorNoticePutBitmap XcursorNoticePutBitmap_dylibloader_orig_xcursor
#define XcursorTryShapeBitmapCursor XcursorTryShapeBitmapCursor_dylibloader_orig_xcursor
#define XcursorImageHash XcursorImageHash_dylibloader_orig_xcursor
#define XcursorSupportsARGB XcursorSupportsARGB_dylibloader_orig_xcursor
#define XcursorSupportsAnim XcursorSupportsAnim_dylibloader_orig_xcursor
#define XcursorSetDefaultSize XcursorSetDefaultSize_dylibloader_orig_xcursor
#define XcursorGetDefaultSize XcursorGetDefaultSize_dylibloader_orig_xcursor
#define XcursorSetTheme XcursorSetTheme_dylibloader_orig_xcursor
#define XcursorGetTheme XcursorGetTheme_dylibloader_orig_xcursor
#define XcursorGetThemeCore XcursorGetThemeCore_dylibloader_orig_xcursor
#define XcursorSetThemeCore XcursorSetThemeCore_dylibloader_orig_xcursor
#include "thirdparty/linuxbsd_headers/X11/Xcursor/Xcursor.h" // IWYU pragma: export.
#undef XcursorImageCreate
#undef XcursorImageDestroy
#undef XcursorImagesCreate
#undef XcursorImagesDestroy
#undef XcursorImagesSetName
#undef XcursorCursorsCreate
#undef XcursorCursorsDestroy
#undef XcursorAnimateCreate
#undef XcursorAnimateDestroy
#undef XcursorAnimateNext
#undef XcursorCommentCreate
#undef XcursorCommentDestroy
#undef XcursorCommentsCreate
#undef XcursorCommentsDestroy
#undef XcursorXcFileLoadImage
#undef XcursorXcFileLoadImages
#undef XcursorXcFileLoadAllImages
#undef XcursorXcFileLoad
#undef XcursorXcFileSave
#undef XcursorFileLoadImage
#undef XcursorFileLoadImages
#undef XcursorFileLoadAllImages
#undef XcursorFileLoad
#undef XcursorFileSaveImages
#undef XcursorFileSave
#undef XcursorFilenameLoadImage
#undef XcursorFilenameLoadImages
#undef XcursorFilenameLoadAllImages
#undef XcursorFilenameLoad
#undef XcursorFilenameSaveImages
#undef XcursorFilenameSave
#undef XcursorLibraryLoadImage
#undef XcursorLibraryLoadImages
#undef XcursorLibraryPath
#undef XcursorLibraryShape
#undef XcursorImageLoadCursor
#undef XcursorImagesLoadCursors
#undef XcursorImagesLoadCursor
#undef XcursorFilenameLoadCursor
#undef XcursorFilenameLoadCursors
#undef XcursorLibraryLoadCursor
#undef XcursorLibraryLoadCursors
#undef XcursorShapeLoadImage
#undef XcursorShapeLoadImages
#undef XcursorShapeLoadCursor
#undef XcursorShapeLoadCursors
#undef XcursorTryShapeCursor
#undef XcursorNoticeCreateBitmap
#undef XcursorNoticePutBitmap
#undef XcursorTryShapeBitmapCursor
#undef XcursorImageHash
#undef XcursorSupportsARGB
#undef XcursorSupportsAnim
#undef XcursorSetDefaultSize
#undef XcursorGetDefaultSize
#undef XcursorSetTheme
#undef XcursorGetTheme
#undef XcursorGetThemeCore
#undef XcursorSetThemeCore
#include <dlfcn.h>
#include <stdio.h>
XcursorImage *(*XcursorImageCreate_dylibloader_wrapper_xcursor)(int, int);
void (*XcursorImageDestroy_dylibloader_wrapper_xcursor)(XcursorImage *);
XcursorImages *(*XcursorImagesCreate_dylibloader_wrapper_xcursor)(int);
void (*XcursorImagesDestroy_dylibloader_wrapper_xcursor)(XcursorImages *);
void (*XcursorImagesSetName_dylibloader_wrapper_xcursor)(XcursorImages *, const char *);
XcursorCursors *(*XcursorCursorsCreate_dylibloader_wrapper_xcursor)(Display *, int);
void (*XcursorCursorsDestroy_dylibloader_wrapper_xcursor)(XcursorCursors *);
XcursorAnimate *(*XcursorAnimateCreate_dylibloader_wrapper_xcursor)(XcursorCursors *);
void (*XcursorAnimateDestroy_dylibloader_wrapper_xcursor)(XcursorAnimate *);
Cursor (*XcursorAnimateNext_dylibloader_wrapper_xcursor)(XcursorAnimate *);
XcursorComment *(*XcursorCommentCreate_dylibloader_wrapper_xcursor)(XcursorUInt, int);
void (*XcursorCommentDestroy_dylibloader_wrapper_xcursor)(XcursorComment *);
XcursorComments *(*XcursorCommentsCreate_dylibloader_wrapper_xcursor)(int);
void (*XcursorCommentsDestroy_dylibloader_wrapper_xcursor)(XcursorComments *);
XcursorImage *(*XcursorXcFileLoadImage_dylibloader_wrapper_xcursor)(XcursorFile *, int);
XcursorImages *(*XcursorXcFileLoadImages_dylibloader_wrapper_xcursor)(XcursorFile *, int);
XcursorImages *(*XcursorXcFileLoadAllImages_dylibloader_wrapper_xcursor)(XcursorFile *);
XcursorBool (*XcursorXcFileLoad_dylibloader_wrapper_xcursor)(XcursorFile *, XcursorComments **, XcursorImages **);
XcursorBool (*XcursorXcFileSave_dylibloader_wrapper_xcursor)(XcursorFile *, const XcursorComments *, const XcursorImages *);
XcursorImage *(*XcursorFileLoadImage_dylibloader_wrapper_xcursor)(FILE *, int);
XcursorImages *(*XcursorFileLoadImages_dylibloader_wrapper_xcursor)(FILE *, int);
XcursorImages *(*XcursorFileLoadAllImages_dylibloader_wrapper_xcursor)(FILE *);
XcursorBool (*XcursorFileLoad_dylibloader_wrapper_xcursor)(FILE *, XcursorComments **, XcursorImages **);
XcursorBool (*XcursorFileSaveImages_dylibloader_wrapper_xcursor)(FILE *, const XcursorImages *);
XcursorBool (*XcursorFileSave_dylibloader_wrapper_xcursor)(FILE *, const XcursorComments *, const XcursorImages *);
XcursorImage *(*XcursorFilenameLoadImage_dylibloader_wrapper_xcursor)(const char *, int);
XcursorImages *(*XcursorFilenameLoadImages_dylibloader_wrapper_xcursor)(const char *, int);
XcursorImages *(*XcursorFilenameLoadAllImages_dylibloader_wrapper_xcursor)(const char *);
XcursorBool (*XcursorFilenameLoad_dylibloader_wrapper_xcursor)(const char *, XcursorComments **, XcursorImages **);
XcursorBool (*XcursorFilenameSaveImages_dylibloader_wrapper_xcursor)(const char *, const XcursorImages *);
XcursorBool (*XcursorFilenameSave_dylibloader_wrapper_xcursor)(const char *, const XcursorComments *, const XcursorImages *);
XcursorImage *(*XcursorLibraryLoadImage_dylibloader_wrapper_xcursor)(const char *, const char *, int);
XcursorImages *(*XcursorLibraryLoadImages_dylibloader_wrapper_xcursor)(const char *, const char *, int);
const char *(*XcursorLibraryPath_dylibloader_wrapper_xcursor)(void);
int (*XcursorLibraryShape_dylibloader_wrapper_xcursor)(const char *);
Cursor (*XcursorImageLoadCursor_dylibloader_wrapper_xcursor)(Display *, const XcursorImage *);
XcursorCursors *(*XcursorImagesLoadCursors_dylibloader_wrapper_xcursor)(Display *, const XcursorImages *);
Cursor (*XcursorImagesLoadCursor_dylibloader_wrapper_xcursor)(Display *, const XcursorImages *);
Cursor (*XcursorFilenameLoadCursor_dylibloader_wrapper_xcursor)(Display *, const char *);
XcursorCursors *(*XcursorFilenameLoadCursors_dylibloader_wrapper_xcursor)(Display *, const char *);
Cursor (*XcursorLibraryLoadCursor_dylibloader_wrapper_xcursor)(Display *, const char *);
XcursorCursors *(*XcursorLibraryLoadCursors_dylibloader_wrapper_xcursor)(Display *, const char *);
XcursorImage *(*XcursorShapeLoadImage_dylibloader_wrapper_xcursor)(unsigned int, const char *, int);
XcursorImages *(*XcursorShapeLoadImages_dylibloader_wrapper_xcursor)(unsigned int, const char *, int);
Cursor (*XcursorShapeLoadCursor_dylibloader_wrapper_xcursor)(Display *, unsigned int);
XcursorCursors *(*XcursorShapeLoadCursors_dylibloader_wrapper_xcursor)(Display *, unsigned int);
Cursor (*XcursorTryShapeCursor_dylibloader_wrapper_xcursor)(Display *, Font, Font, unsigned int, unsigned int, const XColor *, const XColor *);
void (*XcursorNoticeCreateBitmap_dylibloader_wrapper_xcursor)(Display *, Pixmap, unsigned int, unsigned int);
void (*XcursorNoticePutBitmap_dylibloader_wrapper_xcursor)(Display *, Drawable, XImage *);
Cursor (*XcursorTryShapeBitmapCursor_dylibloader_wrapper_xcursor)(Display *, Pixmap, Pixmap, XColor *, XColor *, unsigned int, unsigned int);
void (*XcursorImageHash_dylibloader_wrapper_xcursor)(XImage *, unsigned char [16]);
XcursorBool (*XcursorSupportsARGB_dylibloader_wrapper_xcursor)(Display *);
XcursorBool (*XcursorSupportsAnim_dylibloader_wrapper_xcursor)(Display *);
XcursorBool (*XcursorSetDefaultSize_dylibloader_wrapper_xcursor)(Display *, int);
int (*XcursorGetDefaultSize_dylibloader_wrapper_xcursor)(Display *);
XcursorBool (*XcursorSetTheme_dylibloader_wrapper_xcursor)(Display *, const char *);
char *(*XcursorGetTheme_dylibloader_wrapper_xcursor)(Display *);
XcursorBool (*XcursorGetThemeCore_dylibloader_wrapper_xcursor)(Display *);
XcursorBool (*XcursorSetThemeCore_dylibloader_wrapper_xcursor)(Display *, XcursorBool);
int initialize_xcursor(int verbose) {
  void *handle;
  char *error;
#if defined(__OpenBSD__) || defined(__NetBSD__)
  handle = dlopen("libXcursor.so", RTLD_LAZY);
#else
  handle = dlopen("libXcursor.so.1", RTLD_LAZY);
#endif
  if (!handle) {
    if (verbose) {
      fprintf(stderr, "%s\n", dlerror());
    }
    return(1);
  }
  dlerror();
// XcursorImageCreate
  {
    void *tmp_dlsym = dlsym(handle, "XcursorImageCreate");
    __builtin_memcpy(&XcursorImageCreate_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorImageDestroy
  {
    void *tmp_dlsym = dlsym(handle, "XcursorImageDestroy");
    __builtin_memcpy(&XcursorImageDestroy_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorImagesCreate
  {
    void *tmp_dlsym = dlsym(handle, "XcursorImagesCreate");
    __builtin_memcpy(&XcursorImagesCreate_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorImagesDestroy
  {
    void *tmp_dlsym = dlsym(handle, "XcursorImagesDestroy");
    __builtin_memcpy(&XcursorImagesDestroy_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorImagesSetName
  {
    void *tmp_dlsym = dlsym(handle, "XcursorImagesSetName");
    __builtin_memcpy(&XcursorImagesSetName_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorCursorsCreate
  {
    void *tmp_dlsym = dlsym(handle, "XcursorCursorsCreate");
    __builtin_memcpy(&XcursorCursorsCreate_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorCursorsDestroy
  {
    void *tmp_dlsym = dlsym(handle, "XcursorCursorsDestroy");
    __builtin_memcpy(&XcursorCursorsDestroy_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorAnimateCreate
  {
    void *tmp_dlsym = dlsym(handle, "XcursorAnimateCreate");
    __builtin_memcpy(&XcursorAnimateCreate_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorAnimateDestroy
  {
    void *tmp_dlsym = dlsym(handle, "XcursorAnimateDestroy");
    __builtin_memcpy(&XcursorAnimateDestroy_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorAnimateNext
  {
    void *tmp_dlsym = dlsym(handle, "XcursorAnimateNext");
    __builtin_memcpy(&XcursorAnimateNext_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorCommentCreate
  {
    void *tmp_dlsym = dlsym(handle, "XcursorCommentCreate");
    __builtin_memcpy(&XcursorCommentCreate_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorCommentDestroy
  {
    void *tmp_dlsym = dlsym(handle, "XcursorCommentDestroy");
    __builtin_memcpy(&XcursorCommentDestroy_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorCommentsCreate
  {
    void *tmp_dlsym = dlsym(handle, "XcursorCommentsCreate");
    __builtin_memcpy(&XcursorCommentsCreate_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorCommentsDestroy
  {
    void *tmp_dlsym = dlsym(handle, "XcursorCommentsDestroy");
    __builtin_memcpy(&XcursorCommentsDestroy_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorXcFileLoadImage
  {
    void *tmp_dlsym = dlsym(handle, "XcursorXcFileLoadImage");
    __builtin_memcpy(&XcursorXcFileLoadImage_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorXcFileLoadImages
  {
    void *tmp_dlsym = dlsym(handle, "XcursorXcFileLoadImages");
    __builtin_memcpy(&XcursorXcFileLoadImages_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorXcFileLoadAllImages
  {
    void *tmp_dlsym = dlsym(handle, "XcursorXcFileLoadAllImages");
    __builtin_memcpy(&XcursorXcFileLoadAllImages_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorXcFileLoad
  {
    void *tmp_dlsym = dlsym(handle, "XcursorXcFileLoad");
    __builtin_memcpy(&XcursorXcFileLoad_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorXcFileSave
  {
    void *tmp_dlsym = dlsym(handle, "XcursorXcFileSave");
    __builtin_memcpy(&XcursorXcFileSave_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorFileLoadImage
  {
    void *tmp_dlsym = dlsym(handle, "XcursorFileLoadImage");
    __builtin_memcpy(&XcursorFileLoadImage_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorFileLoadImages
  {
    void *tmp_dlsym = dlsym(handle, "XcursorFileLoadImages");
    __builtin_memcpy(&XcursorFileLoadImages_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorFileLoadAllImages
  {
    void *tmp_dlsym = dlsym(handle, "XcursorFileLoadAllImages");
    __builtin_memcpy(&XcursorFileLoadAllImages_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorFileLoad
  {
    void *tmp_dlsym = dlsym(handle, "XcursorFileLoad");
    __builtin_memcpy(&XcursorFileLoad_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorFileSaveImages
  {
    void *tmp_dlsym = dlsym(handle, "XcursorFileSaveImages");
    __builtin_memcpy(&XcursorFileSaveImages_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorFileSave
  {
    void *tmp_dlsym = dlsym(handle, "XcursorFileSave");
    __builtin_memcpy(&XcursorFileSave_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorFilenameLoadImage
  {
    void *tmp_dlsym = dlsym(handle, "XcursorFilenameLoadImage");
    __builtin_memcpy(&XcursorFilenameLoadImage_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorFilenameLoadImages
  {
    void *tmp_dlsym = dlsym(handle, "XcursorFilenameLoadImages");
    __builtin_memcpy(&XcursorFilenameLoadImages_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorFilenameLoadAllImages
  {
    void *tmp_dlsym = dlsym(handle, "XcursorFilenameLoadAllImages");
    __builtin_memcpy(&XcursorFilenameLoadAllImages_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorFilenameLoad
  {
    void *tmp_dlsym = dlsym(handle, "XcursorFilenameLoad");
    __builtin_memcpy(&XcursorFilenameLoad_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorFilenameSaveImages
  {
    void *tmp_dlsym = dlsym(handle, "XcursorFilenameSaveImages");
    __builtin_memcpy(&XcursorFilenameSaveImages_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorFilenameSave
  {
    void *tmp_dlsym = dlsym(handle, "XcursorFilenameSave");
    __builtin_memcpy(&XcursorFilenameSave_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorLibraryLoadImage
  {
    void *tmp_dlsym = dlsym(handle, "XcursorLibraryLoadImage");
    __builtin_memcpy(&XcursorLibraryLoadImage_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorLibraryLoadImages
  {
    void *tmp_dlsym = dlsym(handle, "XcursorLibraryLoadImages");
    __builtin_memcpy(&XcursorLibraryLoadImages_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorLibraryPath
  {
    void *tmp_dlsym = dlsym(handle, "XcursorLibraryPath");
    __builtin_memcpy(&XcursorLibraryPath_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorLibraryShape
  {
    void *tmp_dlsym = dlsym(handle, "XcursorLibraryShape");
    __builtin_memcpy(&XcursorLibraryShape_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorImageLoadCursor
  {
    void *tmp_dlsym = dlsym(handle, "XcursorImageLoadCursor");
    __builtin_memcpy(&XcursorImageLoadCursor_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorImagesLoadCursors
  {
    void *tmp_dlsym = dlsym(handle, "XcursorImagesLoadCursors");
    __builtin_memcpy(&XcursorImagesLoadCursors_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorImagesLoadCursor
  {
    void *tmp_dlsym = dlsym(handle, "XcursorImagesLoadCursor");
    __builtin_memcpy(&XcursorImagesLoadCursor_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorFilenameLoadCursor
  {
    void *tmp_dlsym = dlsym(handle, "XcursorFilenameLoadCursor");
    __builtin_memcpy(&XcursorFilenameLoadCursor_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorFilenameLoadCursors
  {
    void *tmp_dlsym = dlsym(handle, "XcursorFilenameLoadCursors");
    __builtin_memcpy(&XcursorFilenameLoadCursors_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorLibraryLoadCursor
  {
    void *tmp_dlsym = dlsym(handle, "XcursorLibraryLoadCursor");
    __builtin_memcpy(&XcursorLibraryLoadCursor_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorLibraryLoadCursors
  {
    void *tmp_dlsym = dlsym(handle, "XcursorLibraryLoadCursors");
    __builtin_memcpy(&XcursorLibraryLoadCursors_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorShapeLoadImage
  {
    void *tmp_dlsym = dlsym(handle, "XcursorShapeLoadImage");
    __builtin_memcpy(&XcursorShapeLoadImage_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorShapeLoadImages
  {
    void *tmp_dlsym = dlsym(handle, "XcursorShapeLoadImages");
    __builtin_memcpy(&XcursorShapeLoadImages_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorShapeLoadCursor
  {
    void *tmp_dlsym = dlsym(handle, "XcursorShapeLoadCursor");
    __builtin_memcpy(&XcursorShapeLoadCursor_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorShapeLoadCursors
  {
    void *tmp_dlsym = dlsym(handle, "XcursorShapeLoadCursors");
    __builtin_memcpy(&XcursorShapeLoadCursors_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorTryShapeCursor
  {
    void *tmp_dlsym = dlsym(handle, "XcursorTryShapeCursor");
    __builtin_memcpy(&XcursorTryShapeCursor_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorNoticeCreateBitmap
  {
    void *tmp_dlsym = dlsym(handle, "XcursorNoticeCreateBitmap");
    __builtin_memcpy(&XcursorNoticeCreateBitmap_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorNoticePutBitmap
  {
    void *tmp_dlsym = dlsym(handle, "XcursorNoticePutBitmap");
    __builtin_memcpy(&XcursorNoticePutBitmap_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorTryShapeBitmapCursor
  {
    void *tmp_dlsym = dlsym(handle, "XcursorTryShapeBitmapCursor");
    __builtin_memcpy(&XcursorTryShapeBitmapCursor_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorImageHash
  {
    void *tmp_dlsym = dlsym(handle, "XcursorImageHash");
    __builtin_memcpy(&XcursorImageHash_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorSupportsARGB
  {
    void *tmp_dlsym = dlsym(handle, "XcursorSupportsARGB");
    __builtin_memcpy(&XcursorSupportsARGB_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorSupportsAnim
  {
    void *tmp_dlsym = dlsym(handle, "XcursorSupportsAnim");
    __builtin_memcpy(&XcursorSupportsAnim_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorSetDefaultSize
  {
    void *tmp_dlsym = dlsym(handle, "XcursorSetDefaultSize");
    __builtin_memcpy(&XcursorSetDefaultSize_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorGetDefaultSize
  {
    void *tmp_dlsym = dlsym(handle, "XcursorGetDefaultSize");
    __builtin_memcpy(&XcursorGetDefaultSize_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorSetTheme
  {
    void *tmp_dlsym = dlsym(handle, "XcursorSetTheme");
    __builtin_memcpy(&XcursorSetTheme_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorGetTheme
  {
    void *tmp_dlsym = dlsym(handle, "XcursorGetTheme");
    __builtin_memcpy(&XcursorGetTheme_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorGetThemeCore
  {
    void *tmp_dlsym = dlsym(handle, "XcursorGetThemeCore");
    __builtin_memcpy(&XcursorGetThemeCore_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XcursorSetThemeCore
  {
    void *tmp_dlsym = dlsym(handle, "XcursorSetThemeCore");
    __builtin_memcpy(&XcursorSetThemeCore_dylibloader_wrapper_xcursor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
return 0;
}
