// This file is generated. Do not edit!
// see https://github.com/hpvb/dynload-wrapper for details
// generated by generate-wrapper.py 0.7 on 2026-07-16 12:22:02
// flags: generate-wrapper.py --include /home/build/github/godot/thirdparty/linuxbsd_headers/X11/extensions/XInput2.h --sys-include thirdparty/linuxbsd_headers/X11/extensions/XInput2.h --soname libXi.so.6 --init-name xinput2 --output-header /home/build/github/godot/platform/linuxbsd/x11/dynwrappers/xinput2-so_wrap.h --output-implementation /home/build/github/godot/platform/linuxbsd/x11/dynwrappers/xinput2-so_wrap.c --ignore-other
//
#include <stdint.h>

#define XIQueryPointer XIQueryPointer_dylibloader_orig_xinput2
#define XIWarpPointer XIWarpPointer_dylibloader_orig_xinput2
#define XIDefineCursor XIDefineCursor_dylibloader_orig_xinput2
#define XIUndefineCursor XIUndefineCursor_dylibloader_orig_xinput2
#define XIChangeHierarchy XIChangeHierarchy_dylibloader_orig_xinput2
#define XISetClientPointer XISetClientPointer_dylibloader_orig_xinput2
#define XIGetClientPointer XIGetClientPointer_dylibloader_orig_xinput2
#define XISelectEvents XISelectEvents_dylibloader_orig_xinput2
#define XIGetSelectedEvents XIGetSelectedEvents_dylibloader_orig_xinput2
#define XIQueryVersion XIQueryVersion_dylibloader_orig_xinput2
#define XIQueryDevice XIQueryDevice_dylibloader_orig_xinput2
#define XISetFocus XISetFocus_dylibloader_orig_xinput2
#define XIGetFocus XIGetFocus_dylibloader_orig_xinput2
#define XIGrabDevice XIGrabDevice_dylibloader_orig_xinput2
#define XIUngrabDevice XIUngrabDevice_dylibloader_orig_xinput2
#define XIAllowEvents XIAllowEvents_dylibloader_orig_xinput2
#define XIAllowTouchEvents XIAllowTouchEvents_dylibloader_orig_xinput2
#define XIGrabButton XIGrabButton_dylibloader_orig_xinput2
#define XIGrabKeycode XIGrabKeycode_dylibloader_orig_xinput2
#define XIGrabEnter XIGrabEnter_dylibloader_orig_xinput2
#define XIGrabFocusIn XIGrabFocusIn_dylibloader_orig_xinput2
#define XIGrabTouchBegin XIGrabTouchBegin_dylibloader_orig_xinput2
#define XIUngrabButton XIUngrabButton_dylibloader_orig_xinput2
#define XIUngrabKeycode XIUngrabKeycode_dylibloader_orig_xinput2
#define XIUngrabEnter XIUngrabEnter_dylibloader_orig_xinput2
#define XIUngrabFocusIn XIUngrabFocusIn_dylibloader_orig_xinput2
#define XIUngrabTouchBegin XIUngrabTouchBegin_dylibloader_orig_xinput2
#define XIListProperties XIListProperties_dylibloader_orig_xinput2
#define XIChangeProperty XIChangeProperty_dylibloader_orig_xinput2
#define XIDeleteProperty XIDeleteProperty_dylibloader_orig_xinput2
#define XIGetProperty XIGetProperty_dylibloader_orig_xinput2
#define XIBarrierReleasePointers XIBarrierReleasePointers_dylibloader_orig_xinput2
#define XIBarrierReleasePointer XIBarrierReleasePointer_dylibloader_orig_xinput2
#define XIFreeDeviceInfo XIFreeDeviceInfo_dylibloader_orig_xinput2
#include "thirdparty/linuxbsd_headers/X11/extensions/XInput2.h" // IWYU pragma: export.
#undef XIQueryPointer
#undef XIWarpPointer
#undef XIDefineCursor
#undef XIUndefineCursor
#undef XIChangeHierarchy
#undef XISetClientPointer
#undef XIGetClientPointer
#undef XISelectEvents
#undef XIGetSelectedEvents
#undef XIQueryVersion
#undef XIQueryDevice
#undef XISetFocus
#undef XIGetFocus
#undef XIGrabDevice
#undef XIUngrabDevice
#undef XIAllowEvents
#undef XIAllowTouchEvents
#undef XIGrabButton
#undef XIGrabKeycode
#undef XIGrabEnter
#undef XIGrabFocusIn
#undef XIGrabTouchBegin
#undef XIUngrabButton
#undef XIUngrabKeycode
#undef XIUngrabEnter
#undef XIUngrabFocusIn
#undef XIUngrabTouchBegin
#undef XIListProperties
#undef XIChangeProperty
#undef XIDeleteProperty
#undef XIGetProperty
#undef XIBarrierReleasePointers
#undef XIBarrierReleasePointer
#undef XIFreeDeviceInfo
#include <dlfcn.h>
#include <stdio.h>
int (*XIQueryPointer_dylibloader_wrapper_xinput2)(Display *, int, Window, Window *, Window *, double *, double *, double *, double *, XIButtonState *, XIModifierState *, XIGroupState *);
int (*XIWarpPointer_dylibloader_wrapper_xinput2)(Display *, int, Window, Window, double, double, unsigned int, unsigned int, double, double);
int (*XIDefineCursor_dylibloader_wrapper_xinput2)(Display *, int, Window, Cursor);
int (*XIUndefineCursor_dylibloader_wrapper_xinput2)(Display *, int, Window);
int (*XIChangeHierarchy_dylibloader_wrapper_xinput2)(Display *, XIAnyHierarchyChangeInfo *, int);
int (*XISetClientPointer_dylibloader_wrapper_xinput2)(Display *, Window, int);
int (*XIGetClientPointer_dylibloader_wrapper_xinput2)(Display *, Window, int *);
int (*XISelectEvents_dylibloader_wrapper_xinput2)(Display *, Window, XIEventMask *, int);
XIEventMask *(*XIGetSelectedEvents_dylibloader_wrapper_xinput2)(Display *, Window, int *);
int (*XIQueryVersion_dylibloader_wrapper_xinput2)(Display *, int *, int *);
XIDeviceInfo *(*XIQueryDevice_dylibloader_wrapper_xinput2)(Display *, int, int *);
int (*XISetFocus_dylibloader_wrapper_xinput2)(Display *, int, Window, Time);
int (*XIGetFocus_dylibloader_wrapper_xinput2)(Display *, int, Window *);
int (*XIGrabDevice_dylibloader_wrapper_xinput2)(Display *, int, Window, Time, Cursor, int, int, int, XIEventMask *);
int (*XIUngrabDevice_dylibloader_wrapper_xinput2)(Display *, int, Time);
int (*XIAllowEvents_dylibloader_wrapper_xinput2)(Display *, int, int, Time);
int (*XIAllowTouchEvents_dylibloader_wrapper_xinput2)(Display *, int, unsigned int, Window, int);
int (*XIGrabButton_dylibloader_wrapper_xinput2)(Display *, int, int, Window, Cursor, int, int, int, XIEventMask *, int, XIGrabModifiers *);
int (*XIGrabKeycode_dylibloader_wrapper_xinput2)(Display *, int, int, Window, int, int, int, XIEventMask *, int, XIGrabModifiers *);
int (*XIGrabEnter_dylibloader_wrapper_xinput2)(Display *, int, Window, Cursor, int, int, int, XIEventMask *, int, XIGrabModifiers *);
int (*XIGrabFocusIn_dylibloader_wrapper_xinput2)(Display *, int, Window, int, int, int, XIEventMask *, int, XIGrabModifiers *);
int (*XIGrabTouchBegin_dylibloader_wrapper_xinput2)(Display *, int, Window, int, XIEventMask *, int, XIGrabModifiers *);
int (*XIUngrabButton_dylibloader_wrapper_xinput2)(Display *, int, int, Window, int, XIGrabModifiers *);
int (*XIUngrabKeycode_dylibloader_wrapper_xinput2)(Display *, int, int, Window, int, XIGrabModifiers *);
int (*XIUngrabEnter_dylibloader_wrapper_xinput2)(Display *, int, Window, int, XIGrabModifiers *);
int (*XIUngrabFocusIn_dylibloader_wrapper_xinput2)(Display *, int, Window, int, XIGrabModifiers *);
int (*XIUngrabTouchBegin_dylibloader_wrapper_xinput2)(Display *, int, Window, int, XIGrabModifiers *);
Atom *(*XIListProperties_dylibloader_wrapper_xinput2)(Display *, int, int *);
void (*XIChangeProperty_dylibloader_wrapper_xinput2)(Display *, int, Atom, Atom, int, int, unsigned char *, int);
void (*XIDeleteProperty_dylibloader_wrapper_xinput2)(Display *, int, Atom);
int (*XIGetProperty_dylibloader_wrapper_xinput2)(Display *, int, Atom, long, long, int, Atom, Atom *, int *, unsigned long *, unsigned long *, unsigned char **);
void (*XIBarrierReleasePointers_dylibloader_wrapper_xinput2)(Display *, XIBarrierReleasePointerInfo *, int);
void (*XIBarrierReleasePointer_dylibloader_wrapper_xinput2)(Display *, int, PointerBarrier, BarrierEventID);
void (*XIFreeDeviceInfo_dylibloader_wrapper_xinput2)(XIDeviceInfo *);
int initialize_xinput2(int verbose) {
  void *handle;
  char *error;
#if defined(__OpenBSD__) || defined(__NetBSD__)
  handle = dlopen("libXi.so", RTLD_LAZY);
#else
  handle = dlopen("libXi.so.6", RTLD_LAZY);
#endif
  if (!handle) {
    if (verbose) {
      fprintf(stderr, "%s\n", dlerror());
    }
    return(1);
  }
  dlerror();
// XIQueryPointer
  {
    void *tmp_dlsym = dlsym(handle, "XIQueryPointer");
    XIQueryPointer_dylibloader_wrapper_xinput2 = (__typeof__(XIQueryPointer_dylibloader_wrapper_xinput2))(intptr_t)tmp_dlsym;
#if defined(__GNUC__) && !defined(__clang__)
    __asm__ __volatile__ ("" : "+m" (XIQueryPointer_dylibloader_wrapper_xinput2));
#endif
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XIWarpPointer
  {
    void *tmp_dlsym = dlsym(handle, "XIWarpPointer");
    XIWarpPointer_dylibloader_wrapper_xinput2 = (__typeof__(XIWarpPointer_dylibloader_wrapper_xinput2))(intptr_t)tmp_dlsym;
#if defined(__GNUC__) && !defined(__clang__)
    __asm__ __volatile__ ("" : "+m" (XIWarpPointer_dylibloader_wrapper_xinput2));
#endif
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XIDefineCursor
  {
    void *tmp_dlsym = dlsym(handle, "XIDefineCursor");
    XIDefineCursor_dylibloader_wrapper_xinput2 = (__typeof__(XIDefineCursor_dylibloader_wrapper_xinput2))(intptr_t)tmp_dlsym;
#if defined(__GNUC__) && !defined(__clang__)
    __asm__ __volatile__ ("" : "+m" (XIDefineCursor_dylibloader_wrapper_xinput2));
#endif
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XIUndefineCursor
  {
    void *tmp_dlsym = dlsym(handle, "XIUndefineCursor");
    XIUndefineCursor_dylibloader_wrapper_xinput2 = (__typeof__(XIUndefineCursor_dylibloader_wrapper_xinput2))(intptr_t)tmp_dlsym;
#if defined(__GNUC__) && !defined(__clang__)
    __asm__ __volatile__ ("" : "+m" (XIUndefineCursor_dylibloader_wrapper_xinput2));
#endif
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XIChangeHierarchy
  {
    void *tmp_dlsym = dlsym(handle, "XIChangeHierarchy");
    XIChangeHierarchy_dylibloader_wrapper_xinput2 = (__typeof__(XIChangeHierarchy_dylibloader_wrapper_xinput2))(intptr_t)tmp_dlsym;
#if defined(__GNUC__) && !defined(__clang__)
    __asm__ __volatile__ ("" : "+m" (XIChangeHierarchy_dylibloader_wrapper_xinput2));
#endif
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XISetClientPointer
  {
    void *tmp_dlsym = dlsym(handle, "XISetClientPointer");
    XISetClientPointer_dylibloader_wrapper_xinput2 = (__typeof__(XISetClientPointer_dylibloader_wrapper_xinput2))(intptr_t)tmp_dlsym;
#if defined(__GNUC__) && !defined(__clang__)
    __asm__ __volatile__ ("" : "+m" (XISetClientPointer_dylibloader_wrapper_xinput2));
#endif
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XIGetClientPointer
  {
    void *tmp_dlsym = dlsym(handle, "XIGetClientPointer");
    XIGetClientPointer_dylibloader_wrapper_xinput2 = (__typeof__(XIGetClientPointer_dylibloader_wrapper_xinput2))(intptr_t)tmp_dlsym;
#if defined(__GNUC__) && !defined(__clang__)
    __asm__ __volatile__ ("" : "+m" (XIGetClientPointer_dylibloader_wrapper_xinput2));
#endif
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XISelectEvents
  {
    void *tmp_dlsym = dlsym(handle, "XISelectEvents");
    XISelectEvents_dylibloader_wrapper_xinput2 = (__typeof__(XISelectEvents_dylibloader_wrapper_xinput2))(intptr_t)tmp_dlsym;
#if defined(__GNUC__) && !defined(__clang__)
    __asm__ __volatile__ ("" : "+m" (XISelectEvents_dylibloader_wrapper_xinput2));
#endif
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XIGetSelectedEvents
  {
    void *tmp_dlsym = dlsym(handle, "XIGetSelectedEvents");
    XIGetSelectedEvents_dylibloader_wrapper_xinput2 = (__typeof__(XIGetSelectedEvents_dylibloader_wrapper_xinput2))(intptr_t)tmp_dlsym;
#if defined(__GNUC__) && !defined(__clang__)
    __asm__ __volatile__ ("" : "+m" (XIGetSelectedEvents_dylibloader_wrapper_xinput2));
#endif
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XIQueryVersion
  {
    void *tmp_dlsym = dlsym(handle, "XIQueryVersion");
    XIQueryVersion_dylibloader_wrapper_xinput2 = (__typeof__(XIQueryVersion_dylibloader_wrapper_xinput2))(intptr_t)tmp_dlsym;
#if defined(__GNUC__) && !defined(__clang__)
    __asm__ __volatile__ ("" : "+m" (XIQueryVersion_dylibloader_wrapper_xinput2));
#endif
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XIQueryDevice
  {
    void *tmp_dlsym = dlsym(handle, "XIQueryDevice");
    XIQueryDevice_dylibloader_wrapper_xinput2 = (__typeof__(XIQueryDevice_dylibloader_wrapper_xinput2))(intptr_t)tmp_dlsym;
#if defined(__GNUC__) && !defined(__clang__)
    __asm__ __volatile__ ("" : "+m" (XIQueryDevice_dylibloader_wrapper_xinput2));
#endif
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XISetFocus
  {
    void *tmp_dlsym = dlsym(handle, "XISetFocus");
    XISetFocus_dylibloader_wrapper_xinput2 = (__typeof__(XISetFocus_dylibloader_wrapper_xinput2))(intptr_t)tmp_dlsym;
#if defined(__GNUC__) && !defined(__clang__)
    __asm__ __volatile__ ("" : "+m" (XISetFocus_dylibloader_wrapper_xinput2));
#endif
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XIGetFocus
  {
    void *tmp_dlsym = dlsym(handle, "XIGetFocus");
    XIGetFocus_dylibloader_wrapper_xinput2 = (__typeof__(XIGetFocus_dylibloader_wrapper_xinput2))(intptr_t)tmp_dlsym;
#if defined(__GNUC__) && !defined(__clang__)
    __asm__ __volatile__ ("" : "+m" (XIGetFocus_dylibloader_wrapper_xinput2));
#endif
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XIGrabDevice
  {
    void *tmp_dlsym = dlsym(handle, "XIGrabDevice");
    XIGrabDevice_dylibloader_wrapper_xinput2 = (__typeof__(XIGrabDevice_dylibloader_wrapper_xinput2))(intptr_t)tmp_dlsym;
#if defined(__GNUC__) && !defined(__clang__)
    __asm__ __volatile__ ("" : "+m" (XIGrabDevice_dylibloader_wrapper_xinput2));
#endif
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XIUngrabDevice
  {
    void *tmp_dlsym = dlsym(handle, "XIUngrabDevice");
    XIUngrabDevice_dylibloader_wrapper_xinput2 = (__typeof__(XIUngrabDevice_dylibloader_wrapper_xinput2))(intptr_t)tmp_dlsym;
#if defined(__GNUC__) && !defined(__clang__)
    __asm__ __volatile__ ("" : "+m" (XIUngrabDevice_dylibloader_wrapper_xinput2));
#endif
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XIAllowEvents
  {
    void *tmp_dlsym = dlsym(handle, "XIAllowEvents");
    XIAllowEvents_dylibloader_wrapper_xinput2 = (__typeof__(XIAllowEvents_dylibloader_wrapper_xinput2))(intptr_t)tmp_dlsym;
#if defined(__GNUC__) && !defined(__clang__)
    __asm__ __volatile__ ("" : "+m" (XIAllowEvents_dylibloader_wrapper_xinput2));
#endif
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XIAllowTouchEvents
  {
    void *tmp_dlsym = dlsym(handle, "XIAllowTouchEvents");
    XIAllowTouchEvents_dylibloader_wrapper_xinput2 = (__typeof__(XIAllowTouchEvents_dylibloader_wrapper_xinput2))(intptr_t)tmp_dlsym;
#if defined(__GNUC__) && !defined(__clang__)
    __asm__ __volatile__ ("" : "+m" (XIAllowTouchEvents_dylibloader_wrapper_xinput2));
#endif
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XIGrabButton
  {
    void *tmp_dlsym = dlsym(handle, "XIGrabButton");
    XIGrabButton_dylibloader_wrapper_xinput2 = (__typeof__(XIGrabButton_dylibloader_wrapper_xinput2))(intptr_t)tmp_dlsym;
#if defined(__GNUC__) && !defined(__clang__)
    __asm__ __volatile__ ("" : "+m" (XIGrabButton_dylibloader_wrapper_xinput2));
#endif
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XIGrabKeycode
  {
    void *tmp_dlsym = dlsym(handle, "XIGrabKeycode");
    XIGrabKeycode_dylibloader_wrapper_xinput2 = (__typeof__(XIGrabKeycode_dylibloader_wrapper_xinput2))(intptr_t)tmp_dlsym;
#if defined(__GNUC__) && !defined(__clang__)
    __asm__ __volatile__ ("" : "+m" (XIGrabKeycode_dylibloader_wrapper_xinput2));
#endif
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XIGrabEnter
  {
    void *tmp_dlsym = dlsym(handle, "XIGrabEnter");
    XIGrabEnter_dylibloader_wrapper_xinput2 = (__typeof__(XIGrabEnter_dylibloader_wrapper_xinput2))(intptr_t)tmp_dlsym;
#if defined(__GNUC__) && !defined(__clang__)
    __asm__ __volatile__ ("" : "+m" (XIGrabEnter_dylibloader_wrapper_xinput2));
#endif
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XIGrabFocusIn
  {
    void *tmp_dlsym = dlsym(handle, "XIGrabFocusIn");
    XIGrabFocusIn_dylibloader_wrapper_xinput2 = (__typeof__(XIGrabFocusIn_dylibloader_wrapper_xinput2))(intptr_t)tmp_dlsym;
#if defined(__GNUC__) && !defined(__clang__)
    __asm__ __volatile__ ("" : "+m" (XIGrabFocusIn_dylibloader_wrapper_xinput2));
#endif
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XIGrabTouchBegin
  {
    void *tmp_dlsym = dlsym(handle, "XIGrabTouchBegin");
    XIGrabTouchBegin_dylibloader_wrapper_xinput2 = (__typeof__(XIGrabTouchBegin_dylibloader_wrapper_xinput2))(intptr_t)tmp_dlsym;
#if defined(__GNUC__) && !defined(__clang__)
    __asm__ __volatile__ ("" : "+m" (XIGrabTouchBegin_dylibloader_wrapper_xinput2));
#endif
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XIUngrabButton
  {
    void *tmp_dlsym = dlsym(handle, "XIUngrabButton");
    XIUngrabButton_dylibloader_wrapper_xinput2 = (__typeof__(XIUngrabButton_dylibloader_wrapper_xinput2))(intptr_t)tmp_dlsym;
#if defined(__GNUC__) && !defined(__clang__)
    __asm__ __volatile__ ("" : "+m" (XIUngrabButton_dylibloader_wrapper_xinput2));
#endif
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XIUngrabKeycode
  {
    void *tmp_dlsym = dlsym(handle, "XIUngrabKeycode");
    XIUngrabKeycode_dylibloader_wrapper_xinput2 = (__typeof__(XIUngrabKeycode_dylibloader_wrapper_xinput2))(intptr_t)tmp_dlsym;
#if defined(__GNUC__) && !defined(__clang__)
    __asm__ __volatile__ ("" : "+m" (XIUngrabKeycode_dylibloader_wrapper_xinput2));
#endif
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XIUngrabEnter
  {
    void *tmp_dlsym = dlsym(handle, "XIUngrabEnter");
    XIUngrabEnter_dylibloader_wrapper_xinput2 = (__typeof__(XIUngrabEnter_dylibloader_wrapper_xinput2))(intptr_t)tmp_dlsym;
#if defined(__GNUC__) && !defined(__clang__)
    __asm__ __volatile__ ("" : "+m" (XIUngrabEnter_dylibloader_wrapper_xinput2));
#endif
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XIUngrabFocusIn
  {
    void *tmp_dlsym = dlsym(handle, "XIUngrabFocusIn");
    XIUngrabFocusIn_dylibloader_wrapper_xinput2 = (__typeof__(XIUngrabFocusIn_dylibloader_wrapper_xinput2))(intptr_t)tmp_dlsym;
#if defined(__GNUC__) && !defined(__clang__)
    __asm__ __volatile__ ("" : "+m" (XIUngrabFocusIn_dylibloader_wrapper_xinput2));
#endif
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XIUngrabTouchBegin
  {
    void *tmp_dlsym = dlsym(handle, "XIUngrabTouchBegin");
    XIUngrabTouchBegin_dylibloader_wrapper_xinput2 = (__typeof__(XIUngrabTouchBegin_dylibloader_wrapper_xinput2))(intptr_t)tmp_dlsym;
#if defined(__GNUC__) && !defined(__clang__)
    __asm__ __volatile__ ("" : "+m" (XIUngrabTouchBegin_dylibloader_wrapper_xinput2));
#endif
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XIListProperties
  {
    void *tmp_dlsym = dlsym(handle, "XIListProperties");
    XIListProperties_dylibloader_wrapper_xinput2 = (__typeof__(XIListProperties_dylibloader_wrapper_xinput2))(intptr_t)tmp_dlsym;
#if defined(__GNUC__) && !defined(__clang__)
    __asm__ __volatile__ ("" : "+m" (XIListProperties_dylibloader_wrapper_xinput2));
#endif
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XIChangeProperty
  {
    void *tmp_dlsym = dlsym(handle, "XIChangeProperty");
    XIChangeProperty_dylibloader_wrapper_xinput2 = (__typeof__(XIChangeProperty_dylibloader_wrapper_xinput2))(intptr_t)tmp_dlsym;
#if defined(__GNUC__) && !defined(__clang__)
    __asm__ __volatile__ ("" : "+m" (XIChangeProperty_dylibloader_wrapper_xinput2));
#endif
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XIDeleteProperty
  {
    void *tmp_dlsym = dlsym(handle, "XIDeleteProperty");
    XIDeleteProperty_dylibloader_wrapper_xinput2 = (__typeof__(XIDeleteProperty_dylibloader_wrapper_xinput2))(intptr_t)tmp_dlsym;
#if defined(__GNUC__) && !defined(__clang__)
    __asm__ __volatile__ ("" : "+m" (XIDeleteProperty_dylibloader_wrapper_xinput2));
#endif
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XIGetProperty
  {
    void *tmp_dlsym = dlsym(handle, "XIGetProperty");
    XIGetProperty_dylibloader_wrapper_xinput2 = (__typeof__(XIGetProperty_dylibloader_wrapper_xinput2))(intptr_t)tmp_dlsym;
#if defined(__GNUC__) && !defined(__clang__)
    __asm__ __volatile__ ("" : "+m" (XIGetProperty_dylibloader_wrapper_xinput2));
#endif
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XIBarrierReleasePointers
  {
    void *tmp_dlsym = dlsym(handle, "XIBarrierReleasePointers");
    XIBarrierReleasePointers_dylibloader_wrapper_xinput2 = (__typeof__(XIBarrierReleasePointers_dylibloader_wrapper_xinput2))(intptr_t)tmp_dlsym;
#if defined(__GNUC__) && !defined(__clang__)
    __asm__ __volatile__ ("" : "+m" (XIBarrierReleasePointers_dylibloader_wrapper_xinput2));
#endif
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XIBarrierReleasePointer
  {
    void *tmp_dlsym = dlsym(handle, "XIBarrierReleasePointer");
    XIBarrierReleasePointer_dylibloader_wrapper_xinput2 = (__typeof__(XIBarrierReleasePointer_dylibloader_wrapper_xinput2))(intptr_t)tmp_dlsym;
#if defined(__GNUC__) && !defined(__clang__)
    __asm__ __volatile__ ("" : "+m" (XIBarrierReleasePointer_dylibloader_wrapper_xinput2));
#endif
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XIFreeDeviceInfo
  {
    void *tmp_dlsym = dlsym(handle, "XIFreeDeviceInfo");
    XIFreeDeviceInfo_dylibloader_wrapper_xinput2 = (__typeof__(XIFreeDeviceInfo_dylibloader_wrapper_xinput2))(intptr_t)tmp_dlsym;
#if defined(__GNUC__) && !defined(__clang__)
    __asm__ __volatile__ ("" : "+m" (XIFreeDeviceInfo_dylibloader_wrapper_xinput2));
#endif
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
return 0;
}
