// This file is generated. Do not edit!
// see https://github.com/hpvb/dynload-wrapper for details
// generated by generate-wrapper.py 0.7 on 2026-03-13 16:29:48
// flags: generate-wrapper.py --include /home/build/github/godot/thirdparty/linuxbsd_headers/X11/extensions/Xrandr.h --sys-include thirdparty/linuxbsd_headers/X11/extensions/Xrandr.h --soname libXrandr.so.2 --init-name xrandr --output-header /home/build/github/godot/platform/linuxbsd/x11/dynwrappers/xrandr-so_wrap.h --output-implementation /home/build/github/godot/platform/linuxbsd/x11/dynwrappers/xrandr-so_wrap.c --ignore-other
//
#include <stdint.h>

#define XRRQueryExtension XRRQueryExtension_dylibloader_orig_xrandr
#define XRRQueryVersion XRRQueryVersion_dylibloader_orig_xrandr
#define XRRGetScreenInfo XRRGetScreenInfo_dylibloader_orig_xrandr
#define XRRFreeScreenConfigInfo XRRFreeScreenConfigInfo_dylibloader_orig_xrandr
#define XRRSetScreenConfig XRRSetScreenConfig_dylibloader_orig_xrandr
#define XRRSetScreenConfigAndRate XRRSetScreenConfigAndRate_dylibloader_orig_xrandr
#define XRRConfigRotations XRRConfigRotations_dylibloader_orig_xrandr
#define XRRConfigTimes XRRConfigTimes_dylibloader_orig_xrandr
#define XRRConfigSizes XRRConfigSizes_dylibloader_orig_xrandr
#define XRRConfigRates XRRConfigRates_dylibloader_orig_xrandr
#define XRRConfigCurrentConfiguration XRRConfigCurrentConfiguration_dylibloader_orig_xrandr
#define XRRConfigCurrentRate XRRConfigCurrentRate_dylibloader_orig_xrandr
#define XRRRootToScreen XRRRootToScreen_dylibloader_orig_xrandr
#define XRRSelectInput XRRSelectInput_dylibloader_orig_xrandr
#define XRRRotations XRRRotations_dylibloader_orig_xrandr
#define XRRSizes XRRSizes_dylibloader_orig_xrandr
#define XRRRates XRRRates_dylibloader_orig_xrandr
#define XRRTimes XRRTimes_dylibloader_orig_xrandr
#define XRRGetScreenSizeRange XRRGetScreenSizeRange_dylibloader_orig_xrandr
#define XRRSetScreenSize XRRSetScreenSize_dylibloader_orig_xrandr
#define XRRGetScreenResources XRRGetScreenResources_dylibloader_orig_xrandr
#define XRRFreeScreenResources XRRFreeScreenResources_dylibloader_orig_xrandr
#define XRRGetOutputInfo XRRGetOutputInfo_dylibloader_orig_xrandr
#define XRRFreeOutputInfo XRRFreeOutputInfo_dylibloader_orig_xrandr
#define XRRListOutputProperties XRRListOutputProperties_dylibloader_orig_xrandr
#define XRRQueryOutputProperty XRRQueryOutputProperty_dylibloader_orig_xrandr
#define XRRConfigureOutputProperty XRRConfigureOutputProperty_dylibloader_orig_xrandr
#define XRRChangeOutputProperty XRRChangeOutputProperty_dylibloader_orig_xrandr
#define XRRDeleteOutputProperty XRRDeleteOutputProperty_dylibloader_orig_xrandr
#define XRRGetOutputProperty XRRGetOutputProperty_dylibloader_orig_xrandr
#define XRRAllocModeInfo XRRAllocModeInfo_dylibloader_orig_xrandr
#define XRRCreateMode XRRCreateMode_dylibloader_orig_xrandr
#define XRRDestroyMode XRRDestroyMode_dylibloader_orig_xrandr
#define XRRAddOutputMode XRRAddOutputMode_dylibloader_orig_xrandr
#define XRRDeleteOutputMode XRRDeleteOutputMode_dylibloader_orig_xrandr
#define XRRFreeModeInfo XRRFreeModeInfo_dylibloader_orig_xrandr
#define XRRGetCrtcInfo XRRGetCrtcInfo_dylibloader_orig_xrandr
#define XRRFreeCrtcInfo XRRFreeCrtcInfo_dylibloader_orig_xrandr
#define XRRSetCrtcConfig XRRSetCrtcConfig_dylibloader_orig_xrandr
#define XRRGetCrtcGammaSize XRRGetCrtcGammaSize_dylibloader_orig_xrandr
#define XRRGetCrtcGamma XRRGetCrtcGamma_dylibloader_orig_xrandr
#define XRRAllocGamma XRRAllocGamma_dylibloader_orig_xrandr
#define XRRSetCrtcGamma XRRSetCrtcGamma_dylibloader_orig_xrandr
#define XRRFreeGamma XRRFreeGamma_dylibloader_orig_xrandr
#define XRRGetScreenResourcesCurrent XRRGetScreenResourcesCurrent_dylibloader_orig_xrandr
#define XRRSetCrtcTransform XRRSetCrtcTransform_dylibloader_orig_xrandr
#define XRRGetCrtcTransform XRRGetCrtcTransform_dylibloader_orig_xrandr
#define XRRUpdateConfiguration XRRUpdateConfiguration_dylibloader_orig_xrandr
#define XRRGetPanning XRRGetPanning_dylibloader_orig_xrandr
#define XRRFreePanning XRRFreePanning_dylibloader_orig_xrandr
#define XRRSetPanning XRRSetPanning_dylibloader_orig_xrandr
#define XRRSetOutputPrimary XRRSetOutputPrimary_dylibloader_orig_xrandr
#define XRRGetOutputPrimary XRRGetOutputPrimary_dylibloader_orig_xrandr
#define XRRGetProviderResources XRRGetProviderResources_dylibloader_orig_xrandr
#define XRRFreeProviderResources XRRFreeProviderResources_dylibloader_orig_xrandr
#define XRRGetProviderInfo XRRGetProviderInfo_dylibloader_orig_xrandr
#define XRRFreeProviderInfo XRRFreeProviderInfo_dylibloader_orig_xrandr
#define XRRSetProviderOutputSource XRRSetProviderOutputSource_dylibloader_orig_xrandr
#define XRRSetProviderOffloadSink XRRSetProviderOffloadSink_dylibloader_orig_xrandr
#define XRRListProviderProperties XRRListProviderProperties_dylibloader_orig_xrandr
#define XRRQueryProviderProperty XRRQueryProviderProperty_dylibloader_orig_xrandr
#define XRRConfigureProviderProperty XRRConfigureProviderProperty_dylibloader_orig_xrandr
#define XRRChangeProviderProperty XRRChangeProviderProperty_dylibloader_orig_xrandr
#define XRRDeleteProviderProperty XRRDeleteProviderProperty_dylibloader_orig_xrandr
#define XRRGetProviderProperty XRRGetProviderProperty_dylibloader_orig_xrandr
#define XRRAllocateMonitor XRRAllocateMonitor_dylibloader_orig_xrandr
#define XRRGetMonitors XRRGetMonitors_dylibloader_orig_xrandr
#define XRRSetMonitor XRRSetMonitor_dylibloader_orig_xrandr
#define XRRDeleteMonitor XRRDeleteMonitor_dylibloader_orig_xrandr
#define XRRFreeMonitors XRRFreeMonitors_dylibloader_orig_xrandr
#include "thirdparty/linuxbsd_headers/X11/extensions/Xrandr.h" // IWYU pragma: export.
#undef XRRQueryExtension
#undef XRRQueryVersion
#undef XRRGetScreenInfo
#undef XRRFreeScreenConfigInfo
#undef XRRSetScreenConfig
#undef XRRSetScreenConfigAndRate
#undef XRRConfigRotations
#undef XRRConfigTimes
#undef XRRConfigSizes
#undef XRRConfigRates
#undef XRRConfigCurrentConfiguration
#undef XRRConfigCurrentRate
#undef XRRRootToScreen
#undef XRRSelectInput
#undef XRRRotations
#undef XRRSizes
#undef XRRRates
#undef XRRTimes
#undef XRRGetScreenSizeRange
#undef XRRSetScreenSize
#undef XRRGetScreenResources
#undef XRRFreeScreenResources
#undef XRRGetOutputInfo
#undef XRRFreeOutputInfo
#undef XRRListOutputProperties
#undef XRRQueryOutputProperty
#undef XRRConfigureOutputProperty
#undef XRRChangeOutputProperty
#undef XRRDeleteOutputProperty
#undef XRRGetOutputProperty
#undef XRRAllocModeInfo
#undef XRRCreateMode
#undef XRRDestroyMode
#undef XRRAddOutputMode
#undef XRRDeleteOutputMode
#undef XRRFreeModeInfo
#undef XRRGetCrtcInfo
#undef XRRFreeCrtcInfo
#undef XRRSetCrtcConfig
#undef XRRGetCrtcGammaSize
#undef XRRGetCrtcGamma
#undef XRRAllocGamma
#undef XRRSetCrtcGamma
#undef XRRFreeGamma
#undef XRRGetScreenResourcesCurrent
#undef XRRSetCrtcTransform
#undef XRRGetCrtcTransform
#undef XRRUpdateConfiguration
#undef XRRGetPanning
#undef XRRFreePanning
#undef XRRSetPanning
#undef XRRSetOutputPrimary
#undef XRRGetOutputPrimary
#undef XRRGetProviderResources
#undef XRRFreeProviderResources
#undef XRRGetProviderInfo
#undef XRRFreeProviderInfo
#undef XRRSetProviderOutputSource
#undef XRRSetProviderOffloadSink
#undef XRRListProviderProperties
#undef XRRQueryProviderProperty
#undef XRRConfigureProviderProperty
#undef XRRChangeProviderProperty
#undef XRRDeleteProviderProperty
#undef XRRGetProviderProperty
#undef XRRAllocateMonitor
#undef XRRGetMonitors
#undef XRRSetMonitor
#undef XRRDeleteMonitor
#undef XRRFreeMonitors
#include <dlfcn.h>
#include <stdio.h>
int (*XRRQueryExtension_dylibloader_wrapper_xrandr)(Display *, int *, int *);
int (*XRRQueryVersion_dylibloader_wrapper_xrandr)(Display *, int *, int *);
XRRScreenConfiguration *(*XRRGetScreenInfo_dylibloader_wrapper_xrandr)(Display *, Window);
void (*XRRFreeScreenConfigInfo_dylibloader_wrapper_xrandr)(XRRScreenConfiguration *);
int (*XRRSetScreenConfig_dylibloader_wrapper_xrandr)(Display *, XRRScreenConfiguration *, Drawable, int, Rotation, Time);
int (*XRRSetScreenConfigAndRate_dylibloader_wrapper_xrandr)(Display *, XRRScreenConfiguration *, Drawable, int, Rotation, short, Time);
Rotation (*XRRConfigRotations_dylibloader_wrapper_xrandr)(XRRScreenConfiguration *, Rotation *);
Time (*XRRConfigTimes_dylibloader_wrapper_xrandr)(XRRScreenConfiguration *, Time *);
XRRScreenSize *(*XRRConfigSizes_dylibloader_wrapper_xrandr)(XRRScreenConfiguration *, int *);
short *(*XRRConfigRates_dylibloader_wrapper_xrandr)(XRRScreenConfiguration *, int, int *);
SizeID (*XRRConfigCurrentConfiguration_dylibloader_wrapper_xrandr)(XRRScreenConfiguration *, Rotation *);
short (*XRRConfigCurrentRate_dylibloader_wrapper_xrandr)(XRRScreenConfiguration *);
int (*XRRRootToScreen_dylibloader_wrapper_xrandr)(Display *, Window);
void (*XRRSelectInput_dylibloader_wrapper_xrandr)(Display *, Window, int);
Rotation (*XRRRotations_dylibloader_wrapper_xrandr)(Display *, int, Rotation *);
XRRScreenSize *(*XRRSizes_dylibloader_wrapper_xrandr)(Display *, int, int *);
short *(*XRRRates_dylibloader_wrapper_xrandr)(Display *, int, int, int *);
Time (*XRRTimes_dylibloader_wrapper_xrandr)(Display *, int, Time *);
int (*XRRGetScreenSizeRange_dylibloader_wrapper_xrandr)(Display *, Window, int *, int *, int *, int *);
void (*XRRSetScreenSize_dylibloader_wrapper_xrandr)(Display *, Window, int, int, int, int);
XRRScreenResources *(*XRRGetScreenResources_dylibloader_wrapper_xrandr)(Display *, Window);
void (*XRRFreeScreenResources_dylibloader_wrapper_xrandr)(XRRScreenResources *);
XRROutputInfo *(*XRRGetOutputInfo_dylibloader_wrapper_xrandr)(Display *, XRRScreenResources *, RROutput);
void (*XRRFreeOutputInfo_dylibloader_wrapper_xrandr)(XRROutputInfo *);
Atom *(*XRRListOutputProperties_dylibloader_wrapper_xrandr)(Display *, RROutput, int *);
XRRPropertyInfo *(*XRRQueryOutputProperty_dylibloader_wrapper_xrandr)(Display *, RROutput, Atom);
void (*XRRConfigureOutputProperty_dylibloader_wrapper_xrandr)(Display *, RROutput, Atom, int, int, int, long *);
void (*XRRChangeOutputProperty_dylibloader_wrapper_xrandr)(Display *, RROutput, Atom, Atom, int, int, const unsigned char *, int);
void (*XRRDeleteOutputProperty_dylibloader_wrapper_xrandr)(Display *, RROutput, Atom);
int (*XRRGetOutputProperty_dylibloader_wrapper_xrandr)(Display *, RROutput, Atom, long, long, int, int, Atom, Atom *, int *, unsigned long *, unsigned long *, unsigned char **);
XRRModeInfo *(*XRRAllocModeInfo_dylibloader_wrapper_xrandr)(const char *, int);
RRMode (*XRRCreateMode_dylibloader_wrapper_xrandr)(Display *, Window, XRRModeInfo *);
void (*XRRDestroyMode_dylibloader_wrapper_xrandr)(Display *, RRMode);
void (*XRRAddOutputMode_dylibloader_wrapper_xrandr)(Display *, RROutput, RRMode);
void (*XRRDeleteOutputMode_dylibloader_wrapper_xrandr)(Display *, RROutput, RRMode);
void (*XRRFreeModeInfo_dylibloader_wrapper_xrandr)(XRRModeInfo *);
XRRCrtcInfo *(*XRRGetCrtcInfo_dylibloader_wrapper_xrandr)(Display *, XRRScreenResources *, RRCrtc);
void (*XRRFreeCrtcInfo_dylibloader_wrapper_xrandr)(XRRCrtcInfo *);
int (*XRRSetCrtcConfig_dylibloader_wrapper_xrandr)(Display *, XRRScreenResources *, RRCrtc, Time, int, int, RRMode, Rotation, RROutput *, int);
int (*XRRGetCrtcGammaSize_dylibloader_wrapper_xrandr)(Display *, RRCrtc);
XRRCrtcGamma *(*XRRGetCrtcGamma_dylibloader_wrapper_xrandr)(Display *, RRCrtc);
XRRCrtcGamma *(*XRRAllocGamma_dylibloader_wrapper_xrandr)(int);
void (*XRRSetCrtcGamma_dylibloader_wrapper_xrandr)(Display *, RRCrtc, XRRCrtcGamma *);
void (*XRRFreeGamma_dylibloader_wrapper_xrandr)(XRRCrtcGamma *);
XRRScreenResources *(*XRRGetScreenResourcesCurrent_dylibloader_wrapper_xrandr)(Display *, Window);
void (*XRRSetCrtcTransform_dylibloader_wrapper_xrandr)(Display *, RRCrtc, XTransform *, const char *, XFixed *, int);
int (*XRRGetCrtcTransform_dylibloader_wrapper_xrandr)(Display *, RRCrtc, XRRCrtcTransformAttributes **);
int (*XRRUpdateConfiguration_dylibloader_wrapper_xrandr)(XEvent *);
XRRPanning *(*XRRGetPanning_dylibloader_wrapper_xrandr)(Display *, XRRScreenResources *, RRCrtc);
void (*XRRFreePanning_dylibloader_wrapper_xrandr)(XRRPanning *);
int (*XRRSetPanning_dylibloader_wrapper_xrandr)(Display *, XRRScreenResources *, RRCrtc, XRRPanning *);
void (*XRRSetOutputPrimary_dylibloader_wrapper_xrandr)(Display *, Window, RROutput);
RROutput (*XRRGetOutputPrimary_dylibloader_wrapper_xrandr)(Display *, Window);
XRRProviderResources *(*XRRGetProviderResources_dylibloader_wrapper_xrandr)(Display *, Window);
void (*XRRFreeProviderResources_dylibloader_wrapper_xrandr)(XRRProviderResources *);
XRRProviderInfo *(*XRRGetProviderInfo_dylibloader_wrapper_xrandr)(Display *, XRRScreenResources *, RRProvider);
void (*XRRFreeProviderInfo_dylibloader_wrapper_xrandr)(XRRProviderInfo *);
int (*XRRSetProviderOutputSource_dylibloader_wrapper_xrandr)(Display *, XID, XID);
int (*XRRSetProviderOffloadSink_dylibloader_wrapper_xrandr)(Display *, XID, XID);
Atom *(*XRRListProviderProperties_dylibloader_wrapper_xrandr)(Display *, RRProvider, int *);
XRRPropertyInfo *(*XRRQueryProviderProperty_dylibloader_wrapper_xrandr)(Display *, RRProvider, Atom);
void (*XRRConfigureProviderProperty_dylibloader_wrapper_xrandr)(Display *, RRProvider, Atom, int, int, int, long *);
void (*XRRChangeProviderProperty_dylibloader_wrapper_xrandr)(Display *, RRProvider, Atom, Atom, int, int, const unsigned char *, int);
void (*XRRDeleteProviderProperty_dylibloader_wrapper_xrandr)(Display *, RRProvider, Atom);
int (*XRRGetProviderProperty_dylibloader_wrapper_xrandr)(Display *, RRProvider, Atom, long, long, int, int, Atom, Atom *, int *, unsigned long *, unsigned long *, unsigned char **);
XRRMonitorInfo *(*XRRAllocateMonitor_dylibloader_wrapper_xrandr)(Display *, int);
XRRMonitorInfo *(*XRRGetMonitors_dylibloader_wrapper_xrandr)(Display *, Window, int, int *);
void (*XRRSetMonitor_dylibloader_wrapper_xrandr)(Display *, Window, XRRMonitorInfo *);
void (*XRRDeleteMonitor_dylibloader_wrapper_xrandr)(Display *, Window, Atom);
void (*XRRFreeMonitors_dylibloader_wrapper_xrandr)(XRRMonitorInfo *);
int initialize_xrandr(int verbose) {
  void *handle;
  char *error;
#if defined(__OpenBSD__) || defined(__NetBSD__)
  handle = dlopen("libXrandr.so", RTLD_LAZY);
#else
  handle = dlopen("libXrandr.so.2", RTLD_LAZY);
#endif
  if (!handle) {
    if (verbose) {
      fprintf(stderr, "%s\n", dlerror());
    }
    return(1);
  }
  dlerror();
// XRRQueryExtension
  {
    void *tmp_dlsym = dlsym(handle, "XRRQueryExtension");
    __builtin_memcpy(&XRRQueryExtension_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRQueryVersion
  {
    void *tmp_dlsym = dlsym(handle, "XRRQueryVersion");
    __builtin_memcpy(&XRRQueryVersion_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRGetScreenInfo
  {
    void *tmp_dlsym = dlsym(handle, "XRRGetScreenInfo");
    __builtin_memcpy(&XRRGetScreenInfo_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRFreeScreenConfigInfo
  {
    void *tmp_dlsym = dlsym(handle, "XRRFreeScreenConfigInfo");
    __builtin_memcpy(&XRRFreeScreenConfigInfo_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRSetScreenConfig
  {
    void *tmp_dlsym = dlsym(handle, "XRRSetScreenConfig");
    __builtin_memcpy(&XRRSetScreenConfig_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRSetScreenConfigAndRate
  {
    void *tmp_dlsym = dlsym(handle, "XRRSetScreenConfigAndRate");
    __builtin_memcpy(&XRRSetScreenConfigAndRate_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRConfigRotations
  {
    void *tmp_dlsym = dlsym(handle, "XRRConfigRotations");
    __builtin_memcpy(&XRRConfigRotations_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRConfigTimes
  {
    void *tmp_dlsym = dlsym(handle, "XRRConfigTimes");
    __builtin_memcpy(&XRRConfigTimes_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRConfigSizes
  {
    void *tmp_dlsym = dlsym(handle, "XRRConfigSizes");
    __builtin_memcpy(&XRRConfigSizes_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRConfigRates
  {
    void *tmp_dlsym = dlsym(handle, "XRRConfigRates");
    __builtin_memcpy(&XRRConfigRates_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRConfigCurrentConfiguration
  {
    void *tmp_dlsym = dlsym(handle, "XRRConfigCurrentConfiguration");
    __builtin_memcpy(&XRRConfigCurrentConfiguration_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRConfigCurrentRate
  {
    void *tmp_dlsym = dlsym(handle, "XRRConfigCurrentRate");
    __builtin_memcpy(&XRRConfigCurrentRate_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRRootToScreen
  {
    void *tmp_dlsym = dlsym(handle, "XRRRootToScreen");
    __builtin_memcpy(&XRRRootToScreen_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRSelectInput
  {
    void *tmp_dlsym = dlsym(handle, "XRRSelectInput");
    __builtin_memcpy(&XRRSelectInput_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRRotations
  {
    void *tmp_dlsym = dlsym(handle, "XRRRotations");
    __builtin_memcpy(&XRRRotations_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRSizes
  {
    void *tmp_dlsym = dlsym(handle, "XRRSizes");
    __builtin_memcpy(&XRRSizes_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRRates
  {
    void *tmp_dlsym = dlsym(handle, "XRRRates");
    __builtin_memcpy(&XRRRates_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRTimes
  {
    void *tmp_dlsym = dlsym(handle, "XRRTimes");
    __builtin_memcpy(&XRRTimes_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRGetScreenSizeRange
  {
    void *tmp_dlsym = dlsym(handle, "XRRGetScreenSizeRange");
    __builtin_memcpy(&XRRGetScreenSizeRange_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRSetScreenSize
  {
    void *tmp_dlsym = dlsym(handle, "XRRSetScreenSize");
    __builtin_memcpy(&XRRSetScreenSize_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRGetScreenResources
  {
    void *tmp_dlsym = dlsym(handle, "XRRGetScreenResources");
    __builtin_memcpy(&XRRGetScreenResources_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRFreeScreenResources
  {
    void *tmp_dlsym = dlsym(handle, "XRRFreeScreenResources");
    __builtin_memcpy(&XRRFreeScreenResources_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRGetOutputInfo
  {
    void *tmp_dlsym = dlsym(handle, "XRRGetOutputInfo");
    __builtin_memcpy(&XRRGetOutputInfo_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRFreeOutputInfo
  {
    void *tmp_dlsym = dlsym(handle, "XRRFreeOutputInfo");
    __builtin_memcpy(&XRRFreeOutputInfo_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRListOutputProperties
  {
    void *tmp_dlsym = dlsym(handle, "XRRListOutputProperties");
    __builtin_memcpy(&XRRListOutputProperties_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRQueryOutputProperty
  {
    void *tmp_dlsym = dlsym(handle, "XRRQueryOutputProperty");
    __builtin_memcpy(&XRRQueryOutputProperty_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRConfigureOutputProperty
  {
    void *tmp_dlsym = dlsym(handle, "XRRConfigureOutputProperty");
    __builtin_memcpy(&XRRConfigureOutputProperty_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRChangeOutputProperty
  {
    void *tmp_dlsym = dlsym(handle, "XRRChangeOutputProperty");
    __builtin_memcpy(&XRRChangeOutputProperty_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRDeleteOutputProperty
  {
    void *tmp_dlsym = dlsym(handle, "XRRDeleteOutputProperty");
    __builtin_memcpy(&XRRDeleteOutputProperty_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRGetOutputProperty
  {
    void *tmp_dlsym = dlsym(handle, "XRRGetOutputProperty");
    __builtin_memcpy(&XRRGetOutputProperty_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRAllocModeInfo
  {
    void *tmp_dlsym = dlsym(handle, "XRRAllocModeInfo");
    __builtin_memcpy(&XRRAllocModeInfo_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRCreateMode
  {
    void *tmp_dlsym = dlsym(handle, "XRRCreateMode");
    __builtin_memcpy(&XRRCreateMode_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRDestroyMode
  {
    void *tmp_dlsym = dlsym(handle, "XRRDestroyMode");
    __builtin_memcpy(&XRRDestroyMode_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRAddOutputMode
  {
    void *tmp_dlsym = dlsym(handle, "XRRAddOutputMode");
    __builtin_memcpy(&XRRAddOutputMode_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRDeleteOutputMode
  {
    void *tmp_dlsym = dlsym(handle, "XRRDeleteOutputMode");
    __builtin_memcpy(&XRRDeleteOutputMode_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRFreeModeInfo
  {
    void *tmp_dlsym = dlsym(handle, "XRRFreeModeInfo");
    __builtin_memcpy(&XRRFreeModeInfo_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRGetCrtcInfo
  {
    void *tmp_dlsym = dlsym(handle, "XRRGetCrtcInfo");
    __builtin_memcpy(&XRRGetCrtcInfo_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRFreeCrtcInfo
  {
    void *tmp_dlsym = dlsym(handle, "XRRFreeCrtcInfo");
    __builtin_memcpy(&XRRFreeCrtcInfo_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRSetCrtcConfig
  {
    void *tmp_dlsym = dlsym(handle, "XRRSetCrtcConfig");
    __builtin_memcpy(&XRRSetCrtcConfig_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRGetCrtcGammaSize
  {
    void *tmp_dlsym = dlsym(handle, "XRRGetCrtcGammaSize");
    __builtin_memcpy(&XRRGetCrtcGammaSize_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRGetCrtcGamma
  {
    void *tmp_dlsym = dlsym(handle, "XRRGetCrtcGamma");
    __builtin_memcpy(&XRRGetCrtcGamma_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRAllocGamma
  {
    void *tmp_dlsym = dlsym(handle, "XRRAllocGamma");
    __builtin_memcpy(&XRRAllocGamma_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRSetCrtcGamma
  {
    void *tmp_dlsym = dlsym(handle, "XRRSetCrtcGamma");
    __builtin_memcpy(&XRRSetCrtcGamma_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRFreeGamma
  {
    void *tmp_dlsym = dlsym(handle, "XRRFreeGamma");
    __builtin_memcpy(&XRRFreeGamma_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRGetScreenResourcesCurrent
  {
    void *tmp_dlsym = dlsym(handle, "XRRGetScreenResourcesCurrent");
    __builtin_memcpy(&XRRGetScreenResourcesCurrent_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRSetCrtcTransform
  {
    void *tmp_dlsym = dlsym(handle, "XRRSetCrtcTransform");
    __builtin_memcpy(&XRRSetCrtcTransform_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRGetCrtcTransform
  {
    void *tmp_dlsym = dlsym(handle, "XRRGetCrtcTransform");
    __builtin_memcpy(&XRRGetCrtcTransform_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRUpdateConfiguration
  {
    void *tmp_dlsym = dlsym(handle, "XRRUpdateConfiguration");
    __builtin_memcpy(&XRRUpdateConfiguration_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRGetPanning
  {
    void *tmp_dlsym = dlsym(handle, "XRRGetPanning");
    __builtin_memcpy(&XRRGetPanning_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRFreePanning
  {
    void *tmp_dlsym = dlsym(handle, "XRRFreePanning");
    __builtin_memcpy(&XRRFreePanning_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRSetPanning
  {
    void *tmp_dlsym = dlsym(handle, "XRRSetPanning");
    __builtin_memcpy(&XRRSetPanning_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRSetOutputPrimary
  {
    void *tmp_dlsym = dlsym(handle, "XRRSetOutputPrimary");
    __builtin_memcpy(&XRRSetOutputPrimary_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRGetOutputPrimary
  {
    void *tmp_dlsym = dlsym(handle, "XRRGetOutputPrimary");
    __builtin_memcpy(&XRRGetOutputPrimary_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRGetProviderResources
  {
    void *tmp_dlsym = dlsym(handle, "XRRGetProviderResources");
    __builtin_memcpy(&XRRGetProviderResources_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRFreeProviderResources
  {
    void *tmp_dlsym = dlsym(handle, "XRRFreeProviderResources");
    __builtin_memcpy(&XRRFreeProviderResources_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRGetProviderInfo
  {
    void *tmp_dlsym = dlsym(handle, "XRRGetProviderInfo");
    __builtin_memcpy(&XRRGetProviderInfo_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRFreeProviderInfo
  {
    void *tmp_dlsym = dlsym(handle, "XRRFreeProviderInfo");
    __builtin_memcpy(&XRRFreeProviderInfo_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRSetProviderOutputSource
  {
    void *tmp_dlsym = dlsym(handle, "XRRSetProviderOutputSource");
    __builtin_memcpy(&XRRSetProviderOutputSource_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRSetProviderOffloadSink
  {
    void *tmp_dlsym = dlsym(handle, "XRRSetProviderOffloadSink");
    __builtin_memcpy(&XRRSetProviderOffloadSink_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRListProviderProperties
  {
    void *tmp_dlsym = dlsym(handle, "XRRListProviderProperties");
    __builtin_memcpy(&XRRListProviderProperties_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRQueryProviderProperty
  {
    void *tmp_dlsym = dlsym(handle, "XRRQueryProviderProperty");
    __builtin_memcpy(&XRRQueryProviderProperty_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRConfigureProviderProperty
  {
    void *tmp_dlsym = dlsym(handle, "XRRConfigureProviderProperty");
    __builtin_memcpy(&XRRConfigureProviderProperty_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRChangeProviderProperty
  {
    void *tmp_dlsym = dlsym(handle, "XRRChangeProviderProperty");
    __builtin_memcpy(&XRRChangeProviderProperty_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRDeleteProviderProperty
  {
    void *tmp_dlsym = dlsym(handle, "XRRDeleteProviderProperty");
    __builtin_memcpy(&XRRDeleteProviderProperty_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRGetProviderProperty
  {
    void *tmp_dlsym = dlsym(handle, "XRRGetProviderProperty");
    __builtin_memcpy(&XRRGetProviderProperty_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRAllocateMonitor
  {
    void *tmp_dlsym = dlsym(handle, "XRRAllocateMonitor");
    __builtin_memcpy(&XRRAllocateMonitor_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRGetMonitors
  {
    void *tmp_dlsym = dlsym(handle, "XRRGetMonitors");
    __builtin_memcpy(&XRRGetMonitors_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRSetMonitor
  {
    void *tmp_dlsym = dlsym(handle, "XRRSetMonitor");
    __builtin_memcpy(&XRRSetMonitor_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRDeleteMonitor
  {
    void *tmp_dlsym = dlsym(handle, "XRRDeleteMonitor");
    __builtin_memcpy(&XRRDeleteMonitor_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRRFreeMonitors
  {
    void *tmp_dlsym = dlsym(handle, "XRRFreeMonitors");
    __builtin_memcpy(&XRRFreeMonitors_dylibloader_wrapper_xrandr, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
return 0;
}
