// This file is generated. Do not edit!
// see https://github.com/hpvb/dynload-wrapper for details
// generated by generate-wrapper.py 0.7 on 2026-03-13 16:29:54
// flags: generate-wrapper.py --include /home/build/github/godot/thirdparty/linuxbsd_headers/X11/extensions/Xrender.h --sys-include thirdparty/linuxbsd_headers/X11/extensions/Xrender.h --soname libXrender.so.1 --init-name xrender --output-header /home/build/github/godot/platform/linuxbsd/x11/dynwrappers/xrender-so_wrap.h --output-implementation /home/build/github/godot/platform/linuxbsd/x11/dynwrappers/xrender-so_wrap.c --ignore-other
//
#include <stdint.h>

#define XRenderQueryExtension XRenderQueryExtension_dylibloader_orig_xrender
#define XRenderQueryVersion XRenderQueryVersion_dylibloader_orig_xrender
#define XRenderQueryFormats XRenderQueryFormats_dylibloader_orig_xrender
#define XRenderQuerySubpixelOrder XRenderQuerySubpixelOrder_dylibloader_orig_xrender
#define XRenderSetSubpixelOrder XRenderSetSubpixelOrder_dylibloader_orig_xrender
#define XRenderFindVisualFormat XRenderFindVisualFormat_dylibloader_orig_xrender
#define XRenderFindFormat XRenderFindFormat_dylibloader_orig_xrender
#define XRenderFindStandardFormat XRenderFindStandardFormat_dylibloader_orig_xrender
#define XRenderQueryPictIndexValues XRenderQueryPictIndexValues_dylibloader_orig_xrender
#define XRenderCreatePicture XRenderCreatePicture_dylibloader_orig_xrender
#define XRenderChangePicture XRenderChangePicture_dylibloader_orig_xrender
#define XRenderSetPictureClipRectangles XRenderSetPictureClipRectangles_dylibloader_orig_xrender
#define XRenderSetPictureClipRegion XRenderSetPictureClipRegion_dylibloader_orig_xrender
#define XRenderSetPictureTransform XRenderSetPictureTransform_dylibloader_orig_xrender
#define XRenderFreePicture XRenderFreePicture_dylibloader_orig_xrender
#define XRenderComposite XRenderComposite_dylibloader_orig_xrender
#define XRenderCreateGlyphSet XRenderCreateGlyphSet_dylibloader_orig_xrender
#define XRenderReferenceGlyphSet XRenderReferenceGlyphSet_dylibloader_orig_xrender
#define XRenderFreeGlyphSet XRenderFreeGlyphSet_dylibloader_orig_xrender
#define XRenderAddGlyphs XRenderAddGlyphs_dylibloader_orig_xrender
#define XRenderFreeGlyphs XRenderFreeGlyphs_dylibloader_orig_xrender
#define XRenderCompositeString8 XRenderCompositeString8_dylibloader_orig_xrender
#define XRenderCompositeString16 XRenderCompositeString16_dylibloader_orig_xrender
#define XRenderCompositeString32 XRenderCompositeString32_dylibloader_orig_xrender
#define XRenderCompositeText8 XRenderCompositeText8_dylibloader_orig_xrender
#define XRenderCompositeText16 XRenderCompositeText16_dylibloader_orig_xrender
#define XRenderCompositeText32 XRenderCompositeText32_dylibloader_orig_xrender
#define XRenderFillRectangle XRenderFillRectangle_dylibloader_orig_xrender
#define XRenderFillRectangles XRenderFillRectangles_dylibloader_orig_xrender
#define XRenderCompositeTrapezoids XRenderCompositeTrapezoids_dylibloader_orig_xrender
#define XRenderCompositeTriangles XRenderCompositeTriangles_dylibloader_orig_xrender
#define XRenderCompositeTriStrip XRenderCompositeTriStrip_dylibloader_orig_xrender
#define XRenderCompositeTriFan XRenderCompositeTriFan_dylibloader_orig_xrender
#define XRenderCompositeDoublePoly XRenderCompositeDoublePoly_dylibloader_orig_xrender
#define XRenderParseColor XRenderParseColor_dylibloader_orig_xrender
#define XRenderCreateCursor XRenderCreateCursor_dylibloader_orig_xrender
#define XRenderQueryFilters XRenderQueryFilters_dylibloader_orig_xrender
#define XRenderSetPictureFilter XRenderSetPictureFilter_dylibloader_orig_xrender
#define XRenderCreateAnimCursor XRenderCreateAnimCursor_dylibloader_orig_xrender
#define XRenderAddTraps XRenderAddTraps_dylibloader_orig_xrender
#define XRenderCreateSolidFill XRenderCreateSolidFill_dylibloader_orig_xrender
#define XRenderCreateLinearGradient XRenderCreateLinearGradient_dylibloader_orig_xrender
#define XRenderCreateRadialGradient XRenderCreateRadialGradient_dylibloader_orig_xrender
#define XRenderCreateConicalGradient XRenderCreateConicalGradient_dylibloader_orig_xrender
#include "thirdparty/linuxbsd_headers/X11/extensions/Xrender.h" // IWYU pragma: export.
#undef XRenderQueryExtension
#undef XRenderQueryVersion
#undef XRenderQueryFormats
#undef XRenderQuerySubpixelOrder
#undef XRenderSetSubpixelOrder
#undef XRenderFindVisualFormat
#undef XRenderFindFormat
#undef XRenderFindStandardFormat
#undef XRenderQueryPictIndexValues
#undef XRenderCreatePicture
#undef XRenderChangePicture
#undef XRenderSetPictureClipRectangles
#undef XRenderSetPictureClipRegion
#undef XRenderSetPictureTransform
#undef XRenderFreePicture
#undef XRenderComposite
#undef XRenderCreateGlyphSet
#undef XRenderReferenceGlyphSet
#undef XRenderFreeGlyphSet
#undef XRenderAddGlyphs
#undef XRenderFreeGlyphs
#undef XRenderCompositeString8
#undef XRenderCompositeString16
#undef XRenderCompositeString32
#undef XRenderCompositeText8
#undef XRenderCompositeText16
#undef XRenderCompositeText32
#undef XRenderFillRectangle
#undef XRenderFillRectangles
#undef XRenderCompositeTrapezoids
#undef XRenderCompositeTriangles
#undef XRenderCompositeTriStrip
#undef XRenderCompositeTriFan
#undef XRenderCompositeDoublePoly
#undef XRenderParseColor
#undef XRenderCreateCursor
#undef XRenderQueryFilters
#undef XRenderSetPictureFilter
#undef XRenderCreateAnimCursor
#undef XRenderAddTraps
#undef XRenderCreateSolidFill
#undef XRenderCreateLinearGradient
#undef XRenderCreateRadialGradient
#undef XRenderCreateConicalGradient
#include <dlfcn.h>
#include <stdio.h>
int (*XRenderQueryExtension_dylibloader_wrapper_xrender)(Display *, int *, int *);
int (*XRenderQueryVersion_dylibloader_wrapper_xrender)(Display *, int *, int *);
int (*XRenderQueryFormats_dylibloader_wrapper_xrender)(Display *);
int (*XRenderQuerySubpixelOrder_dylibloader_wrapper_xrender)(Display *, int);
int (*XRenderSetSubpixelOrder_dylibloader_wrapper_xrender)(Display *, int, int);
XRenderPictFormat *(*XRenderFindVisualFormat_dylibloader_wrapper_xrender)(Display *, const Visual *);
XRenderPictFormat *(*XRenderFindFormat_dylibloader_wrapper_xrender)(Display *, unsigned long, const XRenderPictFormat *, int);
XRenderPictFormat *(*XRenderFindStandardFormat_dylibloader_wrapper_xrender)(Display *, int);
XIndexValue *(*XRenderQueryPictIndexValues_dylibloader_wrapper_xrender)(Display *, const XRenderPictFormat *, int *);
Picture (*XRenderCreatePicture_dylibloader_wrapper_xrender)(Display *, Drawable, const XRenderPictFormat *, unsigned long, const XRenderPictureAttributes *);
void (*XRenderChangePicture_dylibloader_wrapper_xrender)(Display *, Picture, unsigned long, const XRenderPictureAttributes *);
void (*XRenderSetPictureClipRectangles_dylibloader_wrapper_xrender)(Display *, Picture, int, int, const XRectangle *, int);
void (*XRenderSetPictureClipRegion_dylibloader_wrapper_xrender)(Display *, Picture, Region);
void (*XRenderSetPictureTransform_dylibloader_wrapper_xrender)(Display *, Picture, XTransform *);
void (*XRenderFreePicture_dylibloader_wrapper_xrender)(Display *, Picture);
void (*XRenderComposite_dylibloader_wrapper_xrender)(Display *, int, Picture, Picture, Picture, int, int, int, int, int, int, unsigned int, unsigned int);
GlyphSet (*XRenderCreateGlyphSet_dylibloader_wrapper_xrender)(Display *, const XRenderPictFormat *);
GlyphSet (*XRenderReferenceGlyphSet_dylibloader_wrapper_xrender)(Display *, GlyphSet);
void (*XRenderFreeGlyphSet_dylibloader_wrapper_xrender)(Display *, GlyphSet);
void (*XRenderAddGlyphs_dylibloader_wrapper_xrender)(Display *, GlyphSet, const Glyph *, const XGlyphInfo *, int, const char *, int);
void (*XRenderFreeGlyphs_dylibloader_wrapper_xrender)(Display *, GlyphSet, const Glyph *, int);
void (*XRenderCompositeString8_dylibloader_wrapper_xrender)(Display *, int, Picture, Picture, const XRenderPictFormat *, GlyphSet, int, int, int, int, const char *, int);
void (*XRenderCompositeString16_dylibloader_wrapper_xrender)(Display *, int, Picture, Picture, const XRenderPictFormat *, GlyphSet, int, int, int, int, const unsigned short *, int);
void (*XRenderCompositeString32_dylibloader_wrapper_xrender)(Display *, int, Picture, Picture, const XRenderPictFormat *, GlyphSet, int, int, int, int, const unsigned int *, int);
void (*XRenderCompositeText8_dylibloader_wrapper_xrender)(Display *, int, Picture, Picture, const XRenderPictFormat *, int, int, int, int, const XGlyphElt8 *, int);
void (*XRenderCompositeText16_dylibloader_wrapper_xrender)(Display *, int, Picture, Picture, const XRenderPictFormat *, int, int, int, int, const XGlyphElt16 *, int);
void (*XRenderCompositeText32_dylibloader_wrapper_xrender)(Display *, int, Picture, Picture, const XRenderPictFormat *, int, int, int, int, const XGlyphElt32 *, int);
void (*XRenderFillRectangle_dylibloader_wrapper_xrender)(Display *, int, Picture, const XRenderColor *, int, int, unsigned int, unsigned int);
void (*XRenderFillRectangles_dylibloader_wrapper_xrender)(Display *, int, Picture, const XRenderColor *, const XRectangle *, int);
void (*XRenderCompositeTrapezoids_dylibloader_wrapper_xrender)(Display *, int, Picture, Picture, const XRenderPictFormat *, int, int, const XTrapezoid *, int);
void (*XRenderCompositeTriangles_dylibloader_wrapper_xrender)(Display *, int, Picture, Picture, const XRenderPictFormat *, int, int, const XTriangle *, int);
void (*XRenderCompositeTriStrip_dylibloader_wrapper_xrender)(Display *, int, Picture, Picture, const XRenderPictFormat *, int, int, const XPointFixed *, int);
void (*XRenderCompositeTriFan_dylibloader_wrapper_xrender)(Display *, int, Picture, Picture, const XRenderPictFormat *, int, int, const XPointFixed *, int);
void (*XRenderCompositeDoublePoly_dylibloader_wrapper_xrender)(Display *, int, Picture, Picture, const XRenderPictFormat *, int, int, int, int, const XPointDouble *, int, int);
int (*XRenderParseColor_dylibloader_wrapper_xrender)(Display *, char *, XRenderColor *);
Cursor (*XRenderCreateCursor_dylibloader_wrapper_xrender)(Display *, Picture, unsigned int, unsigned int);
XFilters *(*XRenderQueryFilters_dylibloader_wrapper_xrender)(Display *, Drawable);
void (*XRenderSetPictureFilter_dylibloader_wrapper_xrender)(Display *, Picture, const char *, XFixed *, int);
Cursor (*XRenderCreateAnimCursor_dylibloader_wrapper_xrender)(Display *, int, XAnimCursor *);
void (*XRenderAddTraps_dylibloader_wrapper_xrender)(Display *, Picture, int, int, const XTrap *, int);
Picture (*XRenderCreateSolidFill_dylibloader_wrapper_xrender)(Display *, const XRenderColor *);
Picture (*XRenderCreateLinearGradient_dylibloader_wrapper_xrender)(Display *, const XLinearGradient *, const XFixed *, const XRenderColor *, int);
Picture (*XRenderCreateRadialGradient_dylibloader_wrapper_xrender)(Display *, const XRadialGradient *, const XFixed *, const XRenderColor *, int);
Picture (*XRenderCreateConicalGradient_dylibloader_wrapper_xrender)(Display *, const XConicalGradient *, const XFixed *, const XRenderColor *, int);
int initialize_xrender(int verbose) {
  void *handle;
  char *error;
#if defined(__OpenBSD__) || defined(__NetBSD__)
  handle = dlopen("libXrender.so", RTLD_LAZY);
#else
  handle = dlopen("libXrender.so.1", RTLD_LAZY);
#endif
  if (!handle) {
    if (verbose) {
      fprintf(stderr, "%s\n", dlerror());
    }
    return(1);
  }
  dlerror();
// XRenderQueryExtension
  {
    void *tmp_dlsym = dlsym(handle, "XRenderQueryExtension");
    __builtin_memcpy(&XRenderQueryExtension_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderQueryVersion
  {
    void *tmp_dlsym = dlsym(handle, "XRenderQueryVersion");
    __builtin_memcpy(&XRenderQueryVersion_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderQueryFormats
  {
    void *tmp_dlsym = dlsym(handle, "XRenderQueryFormats");
    __builtin_memcpy(&XRenderQueryFormats_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderQuerySubpixelOrder
  {
    void *tmp_dlsym = dlsym(handle, "XRenderQuerySubpixelOrder");
    __builtin_memcpy(&XRenderQuerySubpixelOrder_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderSetSubpixelOrder
  {
    void *tmp_dlsym = dlsym(handle, "XRenderSetSubpixelOrder");
    __builtin_memcpy(&XRenderSetSubpixelOrder_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderFindVisualFormat
  {
    void *tmp_dlsym = dlsym(handle, "XRenderFindVisualFormat");
    __builtin_memcpy(&XRenderFindVisualFormat_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderFindFormat
  {
    void *tmp_dlsym = dlsym(handle, "XRenderFindFormat");
    __builtin_memcpy(&XRenderFindFormat_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderFindStandardFormat
  {
    void *tmp_dlsym = dlsym(handle, "XRenderFindStandardFormat");
    __builtin_memcpy(&XRenderFindStandardFormat_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderQueryPictIndexValues
  {
    void *tmp_dlsym = dlsym(handle, "XRenderQueryPictIndexValues");
    __builtin_memcpy(&XRenderQueryPictIndexValues_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderCreatePicture
  {
    void *tmp_dlsym = dlsym(handle, "XRenderCreatePicture");
    __builtin_memcpy(&XRenderCreatePicture_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderChangePicture
  {
    void *tmp_dlsym = dlsym(handle, "XRenderChangePicture");
    __builtin_memcpy(&XRenderChangePicture_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderSetPictureClipRectangles
  {
    void *tmp_dlsym = dlsym(handle, "XRenderSetPictureClipRectangles");
    __builtin_memcpy(&XRenderSetPictureClipRectangles_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderSetPictureClipRegion
  {
    void *tmp_dlsym = dlsym(handle, "XRenderSetPictureClipRegion");
    __builtin_memcpy(&XRenderSetPictureClipRegion_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderSetPictureTransform
  {
    void *tmp_dlsym = dlsym(handle, "XRenderSetPictureTransform");
    __builtin_memcpy(&XRenderSetPictureTransform_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderFreePicture
  {
    void *tmp_dlsym = dlsym(handle, "XRenderFreePicture");
    __builtin_memcpy(&XRenderFreePicture_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderComposite
  {
    void *tmp_dlsym = dlsym(handle, "XRenderComposite");
    __builtin_memcpy(&XRenderComposite_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderCreateGlyphSet
  {
    void *tmp_dlsym = dlsym(handle, "XRenderCreateGlyphSet");
    __builtin_memcpy(&XRenderCreateGlyphSet_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderReferenceGlyphSet
  {
    void *tmp_dlsym = dlsym(handle, "XRenderReferenceGlyphSet");
    __builtin_memcpy(&XRenderReferenceGlyphSet_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderFreeGlyphSet
  {
    void *tmp_dlsym = dlsym(handle, "XRenderFreeGlyphSet");
    __builtin_memcpy(&XRenderFreeGlyphSet_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderAddGlyphs
  {
    void *tmp_dlsym = dlsym(handle, "XRenderAddGlyphs");
    __builtin_memcpy(&XRenderAddGlyphs_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderFreeGlyphs
  {
    void *tmp_dlsym = dlsym(handle, "XRenderFreeGlyphs");
    __builtin_memcpy(&XRenderFreeGlyphs_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderCompositeString8
  {
    void *tmp_dlsym = dlsym(handle, "XRenderCompositeString8");
    __builtin_memcpy(&XRenderCompositeString8_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderCompositeString16
  {
    void *tmp_dlsym = dlsym(handle, "XRenderCompositeString16");
    __builtin_memcpy(&XRenderCompositeString16_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderCompositeString32
  {
    void *tmp_dlsym = dlsym(handle, "XRenderCompositeString32");
    __builtin_memcpy(&XRenderCompositeString32_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderCompositeText8
  {
    void *tmp_dlsym = dlsym(handle, "XRenderCompositeText8");
    __builtin_memcpy(&XRenderCompositeText8_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderCompositeText16
  {
    void *tmp_dlsym = dlsym(handle, "XRenderCompositeText16");
    __builtin_memcpy(&XRenderCompositeText16_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderCompositeText32
  {
    void *tmp_dlsym = dlsym(handle, "XRenderCompositeText32");
    __builtin_memcpy(&XRenderCompositeText32_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderFillRectangle
  {
    void *tmp_dlsym = dlsym(handle, "XRenderFillRectangle");
    __builtin_memcpy(&XRenderFillRectangle_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderFillRectangles
  {
    void *tmp_dlsym = dlsym(handle, "XRenderFillRectangles");
    __builtin_memcpy(&XRenderFillRectangles_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderCompositeTrapezoids
  {
    void *tmp_dlsym = dlsym(handle, "XRenderCompositeTrapezoids");
    __builtin_memcpy(&XRenderCompositeTrapezoids_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderCompositeTriangles
  {
    void *tmp_dlsym = dlsym(handle, "XRenderCompositeTriangles");
    __builtin_memcpy(&XRenderCompositeTriangles_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderCompositeTriStrip
  {
    void *tmp_dlsym = dlsym(handle, "XRenderCompositeTriStrip");
    __builtin_memcpy(&XRenderCompositeTriStrip_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderCompositeTriFan
  {
    void *tmp_dlsym = dlsym(handle, "XRenderCompositeTriFan");
    __builtin_memcpy(&XRenderCompositeTriFan_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderCompositeDoublePoly
  {
    void *tmp_dlsym = dlsym(handle, "XRenderCompositeDoublePoly");
    __builtin_memcpy(&XRenderCompositeDoublePoly_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderParseColor
  {
    void *tmp_dlsym = dlsym(handle, "XRenderParseColor");
    __builtin_memcpy(&XRenderParseColor_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderCreateCursor
  {
    void *tmp_dlsym = dlsym(handle, "XRenderCreateCursor");
    __builtin_memcpy(&XRenderCreateCursor_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderQueryFilters
  {
    void *tmp_dlsym = dlsym(handle, "XRenderQueryFilters");
    __builtin_memcpy(&XRenderQueryFilters_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderSetPictureFilter
  {
    void *tmp_dlsym = dlsym(handle, "XRenderSetPictureFilter");
    __builtin_memcpy(&XRenderSetPictureFilter_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderCreateAnimCursor
  {
    void *tmp_dlsym = dlsym(handle, "XRenderCreateAnimCursor");
    __builtin_memcpy(&XRenderCreateAnimCursor_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderAddTraps
  {
    void *tmp_dlsym = dlsym(handle, "XRenderAddTraps");
    __builtin_memcpy(&XRenderAddTraps_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderCreateSolidFill
  {
    void *tmp_dlsym = dlsym(handle, "XRenderCreateSolidFill");
    __builtin_memcpy(&XRenderCreateSolidFill_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderCreateLinearGradient
  {
    void *tmp_dlsym = dlsym(handle, "XRenderCreateLinearGradient");
    __builtin_memcpy(&XRenderCreateLinearGradient_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderCreateRadialGradient
  {
    void *tmp_dlsym = dlsym(handle, "XRenderCreateRadialGradient");
    __builtin_memcpy(&XRenderCreateRadialGradient_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// XRenderCreateConicalGradient
  {
    void *tmp_dlsym = dlsym(handle, "XRenderCreateConicalGradient");
    __builtin_memcpy(&XRenderCreateConicalGradient_dylibloader_wrapper_xrender, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
return 0;
}
