#!/usr/bin/env python

Import("env")

if "GLES2_GLSL" in env["BUILDERS"]:
    # find all include files
    gl_include_files = [str(f) for f in Glob("*_inc.glsl")]

    # find all shader code(all glsl files excluding our include files)
    glsl_files = [str(f) for f in Glob("*.glsl") if str(f) not in gl_include_files]

    # make sure we recompile shaders if include files change
    env.Depends([f + ".gen.h" for f in glsl_files], gl_include_files + ["#gles2_builders.py"])

    # compile shaders

    # Include them all even if they don't work
    env.GLES2_GLSL(source="canvas.glsl")
    env.GLES2_GLSL(source="feed.glsl")
    env.GLES2_GLSL(source="scene.glsl")
    env.GLES2_GLSL(source="sky.glsl")
    env.GLES2_GLSL(source="cube_to_dp.glsl")
    env.GLES2_GLSL(source="effect_blur.glsl")
    env.GLES2_GLSL(source="canvas_shadow.glsl")
    env.GLES2_GLSL(source="lens_distorted.glsl")
    env.GLES2_GLSL(source="tonemap.glsl")
    env.GLES2_GLSL(source="skeleton.glsl")
    env.GLES2_GLSL(source="particles.glsl")

SConscript("effects/SCsub")