// This file is generated. Do not edit!
// see https://github.com/hpvb/dynload-wrapper for details
// generated by generate-wrapper.py 0.7 on 2026-03-13 16:36:53
// flags: generate-wrapper.py --include /home/build/github/godot/thirdparty/linuxbsd_headers/libdecor-0/libdecor.h --sys-include <libdecor.h> --soname libdecor-0.so.0 --init-name libdecor --output-header /home/build/github/godot/platform/linuxbsd/wayland/dynwrappers/libdecor-so_wrap.h --output-implementation /home/build/github/godot/platform/linuxbsd/wayland/dynwrappers/libdecor-so_wrap.c --omit-prefix wl_
//
#include <stdint.h>

#define libdecor_unref libdecor_unref_dylibloader_orig_libdecor
#define libdecor_new libdecor_new_dylibloader_orig_libdecor
#define libdecor_get_fd libdecor_get_fd_dylibloader_orig_libdecor
#define libdecor_dispatch libdecor_dispatch_dylibloader_orig_libdecor
#define libdecor_decorate libdecor_decorate_dylibloader_orig_libdecor
#define libdecor_frame_ref libdecor_frame_ref_dylibloader_orig_libdecor
#define libdecor_frame_unref libdecor_frame_unref_dylibloader_orig_libdecor
#define libdecor_frame_set_visibility libdecor_frame_set_visibility_dylibloader_orig_libdecor
#define libdecor_frame_is_visible libdecor_frame_is_visible_dylibloader_orig_libdecor
#define libdecor_frame_set_parent libdecor_frame_set_parent_dylibloader_orig_libdecor
#define libdecor_frame_set_title libdecor_frame_set_title_dylibloader_orig_libdecor
#define libdecor_frame_get_title libdecor_frame_get_title_dylibloader_orig_libdecor
#define libdecor_frame_set_app_id libdecor_frame_set_app_id_dylibloader_orig_libdecor
#define libdecor_frame_set_capabilities libdecor_frame_set_capabilities_dylibloader_orig_libdecor
#define libdecor_frame_unset_capabilities libdecor_frame_unset_capabilities_dylibloader_orig_libdecor
#define libdecor_frame_has_capability libdecor_frame_has_capability_dylibloader_orig_libdecor
#define libdecor_frame_show_window_menu libdecor_frame_show_window_menu_dylibloader_orig_libdecor
#define libdecor_frame_popup_grab libdecor_frame_popup_grab_dylibloader_orig_libdecor
#define libdecor_frame_popup_ungrab libdecor_frame_popup_ungrab_dylibloader_orig_libdecor
#define libdecor_frame_translate_coordinate libdecor_frame_translate_coordinate_dylibloader_orig_libdecor
#define libdecor_frame_set_min_content_size libdecor_frame_set_min_content_size_dylibloader_orig_libdecor
#define libdecor_frame_set_max_content_size libdecor_frame_set_max_content_size_dylibloader_orig_libdecor
#define libdecor_frame_get_min_content_size libdecor_frame_get_min_content_size_dylibloader_orig_libdecor
#define libdecor_frame_get_max_content_size libdecor_frame_get_max_content_size_dylibloader_orig_libdecor
#define libdecor_frame_resize libdecor_frame_resize_dylibloader_orig_libdecor
#define libdecor_frame_move libdecor_frame_move_dylibloader_orig_libdecor
#define libdecor_frame_commit libdecor_frame_commit_dylibloader_orig_libdecor
#define libdecor_frame_set_minimized libdecor_frame_set_minimized_dylibloader_orig_libdecor
#define libdecor_frame_set_maximized libdecor_frame_set_maximized_dylibloader_orig_libdecor
#define libdecor_frame_unset_maximized libdecor_frame_unset_maximized_dylibloader_orig_libdecor
#define libdecor_frame_set_fullscreen libdecor_frame_set_fullscreen_dylibloader_orig_libdecor
#define libdecor_frame_unset_fullscreen libdecor_frame_unset_fullscreen_dylibloader_orig_libdecor
#define libdecor_frame_is_floating libdecor_frame_is_floating_dylibloader_orig_libdecor
#define libdecor_frame_close libdecor_frame_close_dylibloader_orig_libdecor
#define libdecor_frame_map libdecor_frame_map_dylibloader_orig_libdecor
#define libdecor_frame_get_xdg_surface libdecor_frame_get_xdg_surface_dylibloader_orig_libdecor
#define libdecor_frame_get_xdg_toplevel libdecor_frame_get_xdg_toplevel_dylibloader_orig_libdecor
#define libdecor_state_new libdecor_state_new_dylibloader_orig_libdecor
#define libdecor_state_free libdecor_state_free_dylibloader_orig_libdecor
#define libdecor_configuration_get_content_size libdecor_configuration_get_content_size_dylibloader_orig_libdecor
#define libdecor_configuration_get_window_state libdecor_configuration_get_window_state_dylibloader_orig_libdecor
#include <libdecor.h> // IWYU pragma: export.
#undef libdecor_unref
#undef libdecor_new
#undef libdecor_get_fd
#undef libdecor_dispatch
#undef libdecor_decorate
#undef libdecor_frame_ref
#undef libdecor_frame_unref
#undef libdecor_frame_set_visibility
#undef libdecor_frame_is_visible
#undef libdecor_frame_set_parent
#undef libdecor_frame_set_title
#undef libdecor_frame_get_title
#undef libdecor_frame_set_app_id
#undef libdecor_frame_set_capabilities
#undef libdecor_frame_unset_capabilities
#undef libdecor_frame_has_capability
#undef libdecor_frame_show_window_menu
#undef libdecor_frame_popup_grab
#undef libdecor_frame_popup_ungrab
#undef libdecor_frame_translate_coordinate
#undef libdecor_frame_set_min_content_size
#undef libdecor_frame_set_max_content_size
#undef libdecor_frame_get_min_content_size
#undef libdecor_frame_get_max_content_size
#undef libdecor_frame_resize
#undef libdecor_frame_move
#undef libdecor_frame_commit
#undef libdecor_frame_set_minimized
#undef libdecor_frame_set_maximized
#undef libdecor_frame_unset_maximized
#undef libdecor_frame_set_fullscreen
#undef libdecor_frame_unset_fullscreen
#undef libdecor_frame_is_floating
#undef libdecor_frame_close
#undef libdecor_frame_map
#undef libdecor_frame_get_xdg_surface
#undef libdecor_frame_get_xdg_toplevel
#undef libdecor_state_new
#undef libdecor_state_free
#undef libdecor_configuration_get_content_size
#undef libdecor_configuration_get_window_state
#include <dlfcn.h>
#include <stdio.h>
void (*libdecor_unref_dylibloader_wrapper_libdecor)(struct libdecor *);
struct libdecor *(*libdecor_new_dylibloader_wrapper_libdecor)(struct wl_display *, struct libdecor_interface *);
int (*libdecor_get_fd_dylibloader_wrapper_libdecor)(struct libdecor *);
int (*libdecor_dispatch_dylibloader_wrapper_libdecor)(struct libdecor *, int);
struct libdecor_frame *(*libdecor_decorate_dylibloader_wrapper_libdecor)(struct libdecor *, struct wl_surface *, struct libdecor_frame_interface *, void *);
void (*libdecor_frame_ref_dylibloader_wrapper_libdecor)(struct libdecor_frame *);
void (*libdecor_frame_unref_dylibloader_wrapper_libdecor)(struct libdecor_frame *);
void (*libdecor_frame_set_visibility_dylibloader_wrapper_libdecor)(struct libdecor_frame *, bool);
bool (*libdecor_frame_is_visible_dylibloader_wrapper_libdecor)(struct libdecor_frame *);
void (*libdecor_frame_set_parent_dylibloader_wrapper_libdecor)(struct libdecor_frame *, struct libdecor_frame *);
void (*libdecor_frame_set_title_dylibloader_wrapper_libdecor)(struct libdecor_frame *, const char *);
const char *(*libdecor_frame_get_title_dylibloader_wrapper_libdecor)(struct libdecor_frame *);
void (*libdecor_frame_set_app_id_dylibloader_wrapper_libdecor)(struct libdecor_frame *, const char *);
void (*libdecor_frame_set_capabilities_dylibloader_wrapper_libdecor)(struct libdecor_frame *, enum libdecor_capabilities);
void (*libdecor_frame_unset_capabilities_dylibloader_wrapper_libdecor)(struct libdecor_frame *, enum libdecor_capabilities);
bool (*libdecor_frame_has_capability_dylibloader_wrapper_libdecor)(struct libdecor_frame *, enum libdecor_capabilities);
void (*libdecor_frame_show_window_menu_dylibloader_wrapper_libdecor)(struct libdecor_frame *, struct wl_seat*, uint32_t, int, int);
void (*libdecor_frame_popup_grab_dylibloader_wrapper_libdecor)(struct libdecor_frame *, const char *);
void (*libdecor_frame_popup_ungrab_dylibloader_wrapper_libdecor)(struct libdecor_frame *, const char *);
void (*libdecor_frame_translate_coordinate_dylibloader_wrapper_libdecor)(struct libdecor_frame *, int, int, int *, int *);
void (*libdecor_frame_set_min_content_size_dylibloader_wrapper_libdecor)(struct libdecor_frame *, int, int);
void (*libdecor_frame_set_max_content_size_dylibloader_wrapper_libdecor)(struct libdecor_frame *, int, int);
void (*libdecor_frame_get_min_content_size_dylibloader_wrapper_libdecor)(const struct libdecor_frame *, int *, int *);
void (*libdecor_frame_get_max_content_size_dylibloader_wrapper_libdecor)(const struct libdecor_frame *, int *, int *);
void (*libdecor_frame_resize_dylibloader_wrapper_libdecor)(struct libdecor_frame *, struct wl_seat*, uint32_t, enum libdecor_resize_edge);
void (*libdecor_frame_move_dylibloader_wrapper_libdecor)(struct libdecor_frame *, struct wl_seat*, uint32_t);
void (*libdecor_frame_commit_dylibloader_wrapper_libdecor)(struct libdecor_frame *, struct libdecor_state *, struct libdecor_configuration *);
void (*libdecor_frame_set_minimized_dylibloader_wrapper_libdecor)(struct libdecor_frame *);
void (*libdecor_frame_set_maximized_dylibloader_wrapper_libdecor)(struct libdecor_frame *);
void (*libdecor_frame_unset_maximized_dylibloader_wrapper_libdecor)(struct libdecor_frame *);
void (*libdecor_frame_set_fullscreen_dylibloader_wrapper_libdecor)(struct libdecor_frame *, struct wl_output *);
void (*libdecor_frame_unset_fullscreen_dylibloader_wrapper_libdecor)(struct libdecor_frame *);
bool (*libdecor_frame_is_floating_dylibloader_wrapper_libdecor)(struct libdecor_frame *);
void (*libdecor_frame_close_dylibloader_wrapper_libdecor)(struct libdecor_frame *);
void (*libdecor_frame_map_dylibloader_wrapper_libdecor)(struct libdecor_frame *);
struct xdg_surface *(*libdecor_frame_get_xdg_surface_dylibloader_wrapper_libdecor)(struct libdecor_frame *);
struct xdg_toplevel *(*libdecor_frame_get_xdg_toplevel_dylibloader_wrapper_libdecor)(struct libdecor_frame *);
struct libdecor_state *(*libdecor_state_new_dylibloader_wrapper_libdecor)(int, int);
void (*libdecor_state_free_dylibloader_wrapper_libdecor)(struct libdecor_state *);
bool (*libdecor_configuration_get_content_size_dylibloader_wrapper_libdecor)(struct libdecor_configuration *, struct libdecor_frame *, int *, int *);
bool (*libdecor_configuration_get_window_state_dylibloader_wrapper_libdecor)(struct libdecor_configuration *, enum libdecor_window_state *);
int initialize_libdecor(int verbose) {
  void *handle;
  char *error;
#if defined(__OpenBSD__) || defined(__NetBSD__)
  handle = dlopen("libdecor-0.so", RTLD_LAZY);
#else
  handle = dlopen("libdecor-0.so.0", RTLD_LAZY);
#endif
  if (!handle) {
    if (verbose) {
      fprintf(stderr, "%s\n", dlerror());
    }
    return(1);
  }
  dlerror();
// libdecor_unref
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_unref");
    __builtin_memcpy(&libdecor_unref_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_new
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_new");
    __builtin_memcpy(&libdecor_new_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_get_fd
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_get_fd");
    __builtin_memcpy(&libdecor_get_fd_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_dispatch
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_dispatch");
    __builtin_memcpy(&libdecor_dispatch_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_decorate
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_decorate");
    __builtin_memcpy(&libdecor_decorate_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_frame_ref
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_frame_ref");
    __builtin_memcpy(&libdecor_frame_ref_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_frame_unref
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_frame_unref");
    __builtin_memcpy(&libdecor_frame_unref_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_frame_set_visibility
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_frame_set_visibility");
    __builtin_memcpy(&libdecor_frame_set_visibility_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_frame_is_visible
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_frame_is_visible");
    __builtin_memcpy(&libdecor_frame_is_visible_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_frame_set_parent
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_frame_set_parent");
    __builtin_memcpy(&libdecor_frame_set_parent_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_frame_set_title
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_frame_set_title");
    __builtin_memcpy(&libdecor_frame_set_title_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_frame_get_title
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_frame_get_title");
    __builtin_memcpy(&libdecor_frame_get_title_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_frame_set_app_id
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_frame_set_app_id");
    __builtin_memcpy(&libdecor_frame_set_app_id_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_frame_set_capabilities
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_frame_set_capabilities");
    __builtin_memcpy(&libdecor_frame_set_capabilities_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_frame_unset_capabilities
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_frame_unset_capabilities");
    __builtin_memcpy(&libdecor_frame_unset_capabilities_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_frame_has_capability
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_frame_has_capability");
    __builtin_memcpy(&libdecor_frame_has_capability_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_frame_show_window_menu
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_frame_show_window_menu");
    __builtin_memcpy(&libdecor_frame_show_window_menu_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_frame_popup_grab
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_frame_popup_grab");
    __builtin_memcpy(&libdecor_frame_popup_grab_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_frame_popup_ungrab
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_frame_popup_ungrab");
    __builtin_memcpy(&libdecor_frame_popup_ungrab_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_frame_translate_coordinate
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_frame_translate_coordinate");
    __builtin_memcpy(&libdecor_frame_translate_coordinate_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_frame_set_min_content_size
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_frame_set_min_content_size");
    __builtin_memcpy(&libdecor_frame_set_min_content_size_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_frame_set_max_content_size
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_frame_set_max_content_size");
    __builtin_memcpy(&libdecor_frame_set_max_content_size_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_frame_get_min_content_size
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_frame_get_min_content_size");
    __builtin_memcpy(&libdecor_frame_get_min_content_size_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_frame_get_max_content_size
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_frame_get_max_content_size");
    __builtin_memcpy(&libdecor_frame_get_max_content_size_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_frame_resize
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_frame_resize");
    __builtin_memcpy(&libdecor_frame_resize_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_frame_move
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_frame_move");
    __builtin_memcpy(&libdecor_frame_move_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_frame_commit
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_frame_commit");
    __builtin_memcpy(&libdecor_frame_commit_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_frame_set_minimized
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_frame_set_minimized");
    __builtin_memcpy(&libdecor_frame_set_minimized_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_frame_set_maximized
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_frame_set_maximized");
    __builtin_memcpy(&libdecor_frame_set_maximized_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_frame_unset_maximized
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_frame_unset_maximized");
    __builtin_memcpy(&libdecor_frame_unset_maximized_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_frame_set_fullscreen
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_frame_set_fullscreen");
    __builtin_memcpy(&libdecor_frame_set_fullscreen_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_frame_unset_fullscreen
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_frame_unset_fullscreen");
    __builtin_memcpy(&libdecor_frame_unset_fullscreen_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_frame_is_floating
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_frame_is_floating");
    __builtin_memcpy(&libdecor_frame_is_floating_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_frame_close
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_frame_close");
    __builtin_memcpy(&libdecor_frame_close_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_frame_map
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_frame_map");
    __builtin_memcpy(&libdecor_frame_map_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_frame_get_xdg_surface
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_frame_get_xdg_surface");
    __builtin_memcpy(&libdecor_frame_get_xdg_surface_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_frame_get_xdg_toplevel
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_frame_get_xdg_toplevel");
    __builtin_memcpy(&libdecor_frame_get_xdg_toplevel_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_state_new
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_state_new");
    __builtin_memcpy(&libdecor_state_new_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_state_free
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_state_free");
    __builtin_memcpy(&libdecor_state_free_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_configuration_get_content_size
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_configuration_get_content_size");
    __builtin_memcpy(&libdecor_configuration_get_content_size_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// libdecor_configuration_get_window_state
  {
    void *tmp_dlsym = dlsym(handle, "libdecor_configuration_get_window_state");
    __builtin_memcpy(&libdecor_configuration_get_window_state_dylibloader_wrapper_libdecor, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
return 0;
}
