#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

# find all include files
gl_include_files = [str(f) for f in Glob("*_inc.glsl")]

# find all shader code(all glsl files excluding our include files)
glsl_files = [str(f) for f in Glob("*.glsl") if str(f) not in gl_include_files]

shaders_to_compile = [
    "canvas.glsl",
    "feed.glsl",
    "scene.glsl",
    "sky.glsl",
    "canvas_occlusion.glsl",
    "canvas_sdf.glsl",
    "particles.glsl",
    "particles_copy.glsl",
    "skeleton.glsl"
]

# compile shaders
for shader in shaders_to_compile:
    if "GLES2_GLSL" in env["BUILDERS"]:
        target_gles2 = f"#drivers/gles2/shaders/{shader}.gen.h"
        
        # Explicitly bind the target and source (to let SCons know)
        node_gles2 = env.GLES2_GLSL(target=target_gles2, source=shader)
        env.Depends(node_gles2, gl_include_files + ["#gles2_builders.py"])

    if "GLES1_GLSL" in env["BUILDERS"]:
        target_gles1 = f"#drivers/gles1/shaders/{shader}.gen.h"
        
        node_gles1 = env.GLES1_GLSL(target=target_gles1, source=shader)
        env.Depends(node_gles1, gl_include_files + ["#gles1_builders.py"])

SConscript("effects/SCsub")
