#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

thirdparty_obj = []
thirdparty_dir = "#thirdparty/vulkan"
thirdparty_volk_dir = "#thirdparty/volk"

# Use bundled Vulkan headers
env.Prepend(CPPPATH=[thirdparty_dir, thirdparty_dir + "/include"])

if env["use_volk"]:
    env.AppendUnique(CPPDEFINES=["USE_VOLK"])
    env.Prepend(CPPPATH=[thirdparty_volk_dir])

if env["platform"] == "android":
    env.AppendUnique(CPPDEFINES=["VK_USE_PLATFORM_ANDROID_KHR"])
    if env["swappy"]:
        env.Prepend(CPPPATH=[
            "#thirdparty/swappy-frame-pacing",
            "#thirdparty/swappy-frame-pacing/include",
            "#thirdparty/swappy-frame-pacing/common/os",
            "#thirdparty/swappy-frame-pacing/common/swappy",
            "#thirdparty/swappy-frame-pacing/common/system",
            "#thirdparty/swappy-frame-pacing/vulkan",
        ])
        swappy_sources = [
            # common/os
            "#thirdparty/swappy-frame-pacing/common/os/ChoreographerFilter.cpp",
            "#thirdparty/swappy-frame-pacing/common/os/ChoreographerThread.cpp",
            "#thirdparty/swappy-frame-pacing/common/os/CpuInfo.cpp",
            "#thirdparty/swappy-frame-pacing/common/os/CPUTracer.cpp",
            
            # common/swappy
            "#thirdparty/swappy-frame-pacing/common/swappy/SwappyCommon.cpp",
            "#thirdparty/swappy-frame-pacing/common/swappy/SwappyDisplayManager.cpp",
            "#thirdparty/swappy-frame-pacing/common/swappy/swappy_c.cpp",
            
            # common/system
            "#thirdparty/swappy-frame-pacing/common/system/FrameStatistics.cpp",
            "#thirdparty/swappy-frame-pacing/common/system/Settings.cpp",
            "#thirdparty/swappy-frame-pacing/common/system/system_utils.cpp",
            "#thirdparty/swappy-frame-pacing/common/system/Thread.cpp",
            
            # vulkan
            "#thirdparty/swappy-frame-pacing/vulkan/SwappyVk.cpp",
            "#thirdparty/swappy-frame-pacing/vulkan/SwappyVkBase.cpp",
            "#thirdparty/swappy-frame-pacing/vulkan/SwappyVkFallback.cpp",
            "#thirdparty/swappy-frame-pacing/vulkan/SwappyVkGoogleDisplayTiming.cpp",
            "#thirdparty/swappy-frame-pacing/vulkan/swappyVk_c.cpp"
        ]

        env_thirdparty_swappy = env.Clone()
        env_thirdparty_swappy.disable_warnings()
        # Instruct Swappy to bypass looking for the embedded binary dex symbols
        env_thirdparty_swappy.AppendUnique(CPPDEFINES=["ANDROIDGAMESDK_NO_BINARY_DEX_LINKAGE"])
        
        env_thirdparty_swappy.add_source_files(thirdparty_obj, swappy_sources)
            
elif env["platform"] == "ios":
    env.AppendUnique(CPPDEFINES=["VK_USE_PLATFORM_IOS_MVK", "VK_USE_PLATFORM_METAL_EXT"])
elif env["platform"] == "linuxbsd":
    if env["x11"]:
        env.AppendUnique(CPPDEFINES=["VK_USE_PLATFORM_XLIB_KHR"])
    if env["wayland"]:
        env.AppendUnique(CPPDEFINES=["VK_USE_PLATFORM_WAYLAND_KHR"])
elif env["platform"] == "macos":
    env.AppendUnique(CPPDEFINES=["VK_USE_PLATFORM_MACOS_MVK", "VK_USE_PLATFORM_METAL_EXT"])
elif env["platform"] == "windows":
    env.AppendUnique(CPPDEFINES=["VK_USE_PLATFORM_WIN32_KHR"])
elif env["platform"] == "openharmony":
    env.AppendUnique(CPPDEFINES=["VK_USE_PLATFORM_OHOS"])

# Build Vulkan memory allocator and volk

# We don't use it for now, and it depends on Windows APIs.
env.AppendUnique(CPPDEFINES=["VMA_EXTERNAL_MEMORY_WIN32=0"])

env_thirdparty_vma = env.Clone()
env_thirdparty_vma.disable_warnings()
thirdparty_sources_vma = [thirdparty_dir + "/vk_mem_alloc.cpp"]

if env["use_volk"]:
    env_thirdparty_vma.AppendUnique(CPPDEFINES=["VMA_STATIC_VULKAN_FUNCTIONS=1"])
    env_thirdparty_volk = env.Clone()
    env_thirdparty_volk.disable_warnings()

    thirdparty_sources_volk = [thirdparty_volk_dir + "/volk.c"]
    env_thirdparty_volk.add_source_files(thirdparty_obj, thirdparty_sources_volk)
elif env["platform"] == "android":
    # Our current NDK version only provides old Vulkan headers,
    # so we have to limit VMA.
    env_thirdparty_vma.AppendUnique(CPPDEFINES=["VMA_VULKAN_VERSION=1000000"])
elif env["platform"] == "macos" or env["platform"] == "ios":
    # MoltenVK supports only Vulkan 1.1 API, limit VMA to the same version.
    env_thirdparty_vma.AppendUnique(CPPDEFINES=["VMA_VULKAN_VERSION=1001000"])

env_thirdparty_vma.add_source_files(thirdparty_obj, thirdparty_sources_vma)


env.drivers_sources += thirdparty_obj


# Godot source files

driver_obj = []

env.add_source_files(driver_obj, "*.cpp")
env.drivers_sources += driver_obj

# Needed to force rebuilding the driver files when the thirdparty code is updated.
env.Depends(driver_obj, thirdparty_obj)
