/**************************************************************************/
/*  win_vista_thunks.c                                                    */
/**************************************************************************/
/*                         This file is part of:                          */
/*                             GODOT ENGINE                               */
/*                        https://godotengine.org                         */
/**************************************************************************/
/* Copyright (c) 2014-present Godot Engine contributors (see AUTHORS.md). */
/* Copyright (c) 2007-2014 Juan Linietsky, Ariel Manzur.                  */
/*                                                                        */
/* Permission is hereby granted, free of charge, to any person obtaining  */
/* a copy of this software and associated documentation files (the        */
/* "Software"), to deal in the Software without restriction, including    */
/* without limitation the rights to use, copy, modify, merge, publish,    */
/* distribute, sublicense, and/or sell copies of the Software, and to     */
/* permit persons to whom the Software is furnished to do so, subject to  */
/* the following conditions:                                              */
/*                                                                        */
/* The above copyright notice and this permission notice shall be         */
/* included in all copies or substantial portions of the Software.        */
/*                                                                        */
/* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,        */
/* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF     */
/* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. */
/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY   */
/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,   */
/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE      */
/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                 */
/**************************************************************************/

// These will always be compiled-in, but if the developer
// wants 7 or higher, these will be compiled-out
// because on 7 they're guaranteed to exist.

#if defined(WINVER) && WINVER < 0x0601

#include <windows.h>

// Structs

typedef struct _PROCESSOR_NUMBER_INTERNAL {
	WORD   Group;
	BYTE   Number;
	BYTE   Reserved;
} PROCESSOR_NUMBER_INTERNAL;

// Forward declarations
static BOOLEAN WINAPI VistaInternal_TryAcquireSRWLockExclusive(PSRWLOCK SRWLock);
static BOOLEAN WINAPI VistaInternal_TryAcquireSRWLockShared(PSRWLOCK SRWLock);
static BOOL WINAPI VistaInternal_K32EnumProcessModulesEx(HANDLE hProcess, HMODULE* lphModule, DWORD cb, LPDWORD lpcbNeeded, DWORD dwFilterFlag);
static DWORD WINAPI VistaInternal_K32GetModuleBaseNameW(HANDLE hProcess, HMODULE hModule, LPWSTR lpBaseName, DWORD nSize);
static BOOL WINAPI VistaInternal_K32GetModuleInformation(HANDLE hProcess, HMODULE hModule, void* lpmodinfo, DWORD cb);
static VOID WINAPI VistaInternal_GetCurrentProcessorNumberEx(PROCESSOR_NUMBER_INTERNAL* ProcNumber);
static BOOL WINAPI VistaInternal_GetLogicalProcessorInformationEx(int RelationshipType, void* Buffer, PDWORD ReturnedLength);
static BOOL WINAPI VistaInternal_GetThreadGroupAffinity(HANDLE hThread, void* GroupAffinity);
static BOOL WINAPI VistaInternal_SetThreadGroupAffinity(HANDLE hThread, const void* GroupAffinity, void* PreviousGroupAffinity);
static BOOL WINAPI VistaInternal_K32EnumProcessModules(HANDLE hProcess, HMODULE* lphModule, DWORD cb, LPDWORD lpcbNeeded);

/* =========================================================================== */
/* Linker exports & explicit intercept pointers                                */
/* =========================================================================== */
// These function pointers satisfy __declspec(dllimport) paths generated by
// compilers expecting to find these functions in external DLLs.

#if defined(_M_IX86) || defined(__i386__)

// 32-bit require symbol decorations

#if defined(__clang__)
// For clang-cl, we bypass /alternatename completely because lld-link treats it as a weak alias.
// Instead, we define the __imp_ symbols directly as strong global variables using __asm__.
BOOLEAN (WINAPI *__imp_TryAcquireSRWLockExclusive)(PSRWLOCK) __asm__("__imp__TryAcquireSRWLockExclusive@4") = VistaInternal_TryAcquireSRWLockExclusive;
BOOLEAN (WINAPI *__imp_TryAcquireSRWLockShared)(PSRWLOCK) __asm__("__imp__TryAcquireSRWLockShared@4") = VistaInternal_TryAcquireSRWLockShared;
BOOL (WINAPI *__imp_K32EnumProcessModulesEx)(HANDLE, HMODULE*, DWORD, LPDWORD, DWORD) __asm__("__imp__K32EnumProcessModulesEx@20") = VistaInternal_K32EnumProcessModulesEx;
DWORD (WINAPI *__imp_K32GetModuleBaseNameW)(HANDLE, HMODULE, LPWSTR, DWORD) __asm__("__imp__K32GetModuleBaseNameW@16") = VistaInternal_K32GetModuleBaseNameW;
BOOL (WINAPI *__imp_K32GetModuleInformation)(HANDLE, HMODULE, void*, DWORD) __asm__("__imp__K32GetModuleInformation@16") = VistaInternal_K32GetModuleInformation;
VOID (WINAPI *__imp_GetCurrentProcessorNumberEx)(PROCESSOR_NUMBER_INTERNAL*) __asm__("__imp__GetCurrentProcessorNumberEx@4") = VistaInternal_GetCurrentProcessorNumberEx;
BOOL (WINAPI *__imp_GetLogicalProcessorInformationEx)(int, void*, PDWORD) __asm__("__imp__GetLogicalProcessorInformationEx@12") = VistaInternal_GetLogicalProcessorInformationEx;
BOOL (WINAPI *__imp_GetThreadGroupAffinity)(HANDLE, void*) __asm__("__imp__GetThreadGroupAffinity@8") = VistaInternal_GetThreadGroupAffinity;
BOOL (WINAPI *__imp_SetThreadGroupAffinity)(HANDLE, const void*, void*) __asm__("__imp__SetThreadGroupAffinity@12") = VistaInternal_SetThreadGroupAffinity;
BOOL (WINAPI *__imp_K32EnumProcessModules)(HANDLE, HMODULE*, DWORD, LPDWORD) __asm__("__imp__K32EnumProcessModules@16") = VistaInternal_K32EnumProcessModules;

#else

// Fallback for native MSVC link
BOOLEAN (WINAPI *imp_TryAcquireSRWLockExclusive_ptr)(PSRWLOCK) = VistaInternal_TryAcquireSRWLockExclusive;
BOOLEAN (WINAPI *imp_TryAcquireSRWLockShared_ptr)(PSRWLOCK) = VistaInternal_TryAcquireSRWLockShared;
BOOL (WINAPI *imp_K32EnumProcessModulesEx_ptr)(HANDLE, HMODULE*, DWORD, LPDWORD, DWORD) = VistaInternal_K32EnumProcessModulesEx;
DWORD (WINAPI *imp_K32GetModuleBaseNameW_ptr)(HANDLE, HMODULE, LPWSTR, DWORD) = VistaInternal_K32GetModuleBaseNameW;
BOOL (WINAPI *imp_K32GetModuleInformation_ptr)(HANDLE, HMODULE, void*, DWORD) = VistaInternal_K32GetModuleInformation;
VOID (WINAPI *imp_GetCurrentProcessorNumberEx_ptr)(PROCESSOR_NUMBER_INTERNAL*) = VistaInternal_GetCurrentProcessorNumberEx;
BOOL (WINAPI *imp_GetLogicalProcessorInformationEx_ptr)(int, void*, PDWORD) = VistaInternal_GetLogicalProcessorInformationEx;
BOOL (WINAPI *imp_GetThreadGroupAffinity_ptr)(HANDLE, void*) = VistaInternal_GetThreadGroupAffinity;
BOOL (WINAPI *imp_SetThreadGroupAffinity_ptr)(HANDLE, const void*, void*) = VistaInternal_SetThreadGroupAffinity;
BOOL (WINAPI *imp_K32EnumProcessModules_ptr)(HANDLE, HMODULE*, DWORD, LPDWORD) = VistaInternal_K32EnumProcessModules;

#pragma comment(linker, "/alternatename:__imp__TryAcquireSRWLockExclusive@4=_imp_TryAcquireSRWLockExclusive_ptr")
#pragma comment(linker, "/alternatename:__imp__TryAcquireSRWLockShared@4=_imp_TryAcquireSRWLockShared_ptr")
#pragma comment(linker, "/alternatename:__imp__K32EnumProcessModulesEx@20=_imp_K32EnumProcessModulesEx_ptr")
#pragma comment(linker, "/alternatename:__imp__K32GetModuleBaseNameW@16=_imp_K32GetModuleBaseNameW_ptr")
#pragma comment(linker, "/alternatename:__imp__K32GetModuleInformation@16=_imp_K32GetModuleInformation_ptr")
#pragma comment(linker, "/alternatename:__imp__GetCurrentProcessorNumberEx@4=_imp_GetCurrentProcessorNumberEx_ptr")
#pragma comment(linker, "/alternatename:__imp__GetLogicalProcessorInformationEx@12=_imp_GetLogicalProcessorInformationEx_ptr")
#pragma comment(linker, "/alternatename:__imp__GetThreadGroupAffinity@8=_imp_GetThreadGroupAffinity_ptr")
#pragma comment(linker, "/alternatename:__imp__SetThreadGroupAffinity@12=_imp_SetThreadGroupAffinity_ptr")
#pragma comment(linker, "/alternatename:__imp__K32EnumProcessModules@16=_imp_K32EnumProcessModules_ptr")

#endif // __clang__

// Map naked export tables to the 32-bit internal decorated symbols
#if defined(__clang__)

#pragma comment(linker, "/export:TryAcquireSRWLockExclusive=_TryAcquireSRWLockExclusive@4")
#pragma comment(linker, "/export:TryAcquireSRWLockShared=_TryAcquireSRWLockShared@4")
#pragma comment(linker, "/export:K32EnumProcessModulesEx=_K32EnumProcessModulesEx@20")
#pragma comment(linker, "/export:K32GetModuleBaseNameW=_K32GetModuleBaseNameW@16")
#pragma comment(linker, "/export:K32GetModuleInformation=_K32GetModuleInformation@16")
#pragma comment(linker, "/export:GetCurrentProcessorNumberEx=_GetCurrentProcessorNumberEx@4")
#pragma comment(linker, "/export:GetLogicalProcessorInformationEx=_GetLogicalProcessorInformationEx@12")
#pragma comment(linker, "/export:GetThreadGroupAffinity=_GetThreadGroupAffinity@8")
#pragma comment(linker, "/export:SetThreadGroupAffinity=_SetThreadGroupAffinity@12")
#pragma comment(linker, "/export:K32EnumProcessModules=_K32EnumProcessModules@16")

#else

#pragma comment(linker, "/export:TryAcquireSRWLockExclusive=_Godot_TryAcquireSRWLockExclusive@4")
#pragma comment(linker, "/export:TryAcquireSRWLockShared=_Godot_TryAcquireSRWLockShared@4")
#pragma comment(linker, "/export:K32EnumProcessModulesEx=_Godot_K32EnumProcessModulesEx@20")
#pragma comment(linker, "/export:K32GetModuleBaseNameW=_Godot_K32GetModuleBaseNameW@16")
#pragma comment(linker, "/export:K32GetModuleInformation=_Godot_K32GetModuleInformation@16")
#pragma comment(linker, "/export:GetCurrentProcessorNumberEx=_Godot_GetCurrentProcessorNumberEx@4")
#pragma comment(linker, "/export:GetLogicalProcessorInformationEx=_Godot_GetLogicalProcessorInformationEx@12")
#pragma comment(linker, "/export:GetThreadGroupAffinity=_Godot_GetThreadGroupAffinity@8")
#pragma comment(linker, "/export:SetThreadGroupAffinity=_Godot_SetThreadGroupAffinity@12")
#pragma comment(linker, "/export:K32EnumProcessModules=_Godot_K32EnumProcessModules@16")

#endif // __clang__

#else // 64-bit

BOOLEAN (WINAPI *__imp_TryAcquireSRWLockExclusive)(PSRWLOCK) = VistaInternal_TryAcquireSRWLockExclusive;
BOOLEAN (WINAPI *__imp_TryAcquireSRWLockShared)(PSRWLOCK) = VistaInternal_TryAcquireSRWLockShared;
BOOL (WINAPI *__imp_K32EnumProcessModulesEx)(HANDLE, HMODULE*, DWORD, LPDWORD, DWORD) = VistaInternal_K32EnumProcessModulesEx;
DWORD (WINAPI *__imp_K32GetModuleBaseNameW)(HANDLE, HMODULE, LPWSTR, DWORD) = VistaInternal_K32GetModuleBaseNameW;
BOOL (WINAPI *__imp_K32GetModuleInformation)(HANDLE, HMODULE, void*, DWORD) = VistaInternal_K32GetModuleInformation;
VOID (WINAPI *__imp_GetCurrentProcessorNumberEx)(PROCESSOR_NUMBER_INTERNAL*) = VistaInternal_GetCurrentProcessorNumberEx;
BOOL (WINAPI *__imp_GetLogicalProcessorInformationEx)(int, void*, PDWORD) = VistaInternal_GetLogicalProcessorInformationEx;
BOOL (WINAPI *__imp_GetThreadGroupAffinity)(HANDLE, void*) = VistaInternal_GetThreadGroupAffinity;
BOOL (WINAPI *__imp_SetThreadGroupAffinity)(HANDLE, const void*, void*) = VistaInternal_SetThreadGroupAffinity;
BOOL (WINAPI *__imp_K32EnumProcessModules)(HANDLE, HMODULE*, DWORD, LPDWORD) = VistaInternal_K32EnumProcessModules;

#if defined(__clang__)

#pragma comment(linker, "/export:TryAcquireSRWLockExclusive")
#pragma comment(linker, "/export:TryAcquireSRWLockShared")
#pragma comment(linker, "/export:K32EnumProcessModulesEx")
#pragma comment(linker, "/export:K32GetModuleBaseNameW")
#pragma comment(linker, "/export:K32GetModuleInformation")
#pragma comment(linker, "/export:GetCurrentProcessorNumberEx")
#pragma comment(linker, "/export:GetLogicalProcessorInformationEx")
#pragma comment(linker, "/export:GetThreadGroupAffinity")
#pragma comment(linker, "/export:SetThreadGroupAffinity")
#pragma comment(linker, "/export:K32EnumProcessModules")

#else // Native MSVC

#pragma comment(linker, "/export:TryAcquireSRWLockExclusive=Godot_TryAcquireSRWLockExclusive")
#pragma comment(linker, "/export:TryAcquireSRWLockShared=Godot_TryAcquireSRWLockShared")
#pragma comment(linker, "/export:K32EnumProcessModulesEx=Godot_K32EnumProcessModulesEx")
#pragma comment(linker, "/export:K32GetModuleBaseNameW=Godot_K32GetModuleBaseNameW")
#pragma comment(linker, "/export:K32GetModuleInformation=Godot_K32GetModuleInformation")
#pragma comment(linker, "/export:GetCurrentProcessorNumberEx=Godot_GetCurrentProcessorNumberEx")
#pragma comment(linker, "/export:GetLogicalProcessorInformationEx=Godot_GetLogicalProcessorInformationEx")
#pragma comment(linker, "/export:GetThreadGroupAffinity=Godot_GetThreadGroupAffinity")
#pragma comment(linker, "/export:SetThreadGroupAffinity=Godot_SetThreadGroupAffinity")
#pragma comment(linker, "/export:K32EnumProcessModules=Godot_K32EnumProcessModules")

// Map direct 64-bit calls to our local implementations
#pragma comment(linker, "/alternatename:TryAcquireSRWLockExclusive=Godot_TryAcquireSRWLockExclusive")
#pragma comment(linker, "/alternatename:TryAcquireSRWLockShared=Godot_TryAcquireSRWLockShared")
#pragma comment(linker, "/alternatename:K32EnumProcessModulesEx=Godot_K32EnumProcessModulesEx")
#pragma comment(linker, "/alternatename:K32GetModuleBaseNameW=Godot_K32GetModuleBaseNameW")
#pragma comment(linker, "/alternatename:K32GetModuleInformation=Godot_K32GetModuleInformation")
#pragma comment(linker, "/alternatename:GetCurrentProcessorNumberEx=Godot_GetCurrentProcessorNumberEx")
#pragma comment(linker, "/alternatename:GetLogicalProcessorInformationEx=Godot_GetLogicalProcessorInformationEx")
#pragma comment(linker, "/alternatename:GetThreadGroupAffinity=Godot_GetThreadGroupAffinity")
#pragma comment(linker, "/alternatename:SetThreadGroupAffinity=Godot_SetThreadGroupAffinity")
#pragma comment(linker, "/alternatename:K32EnumProcessModules=Godot_K32EnumProcessModules")

#endif // __clang__

#endif // _M_IX86 || __i386__

/* =========================================================================== */
/* Direct bare paths                                                           */
/* =========================================================================== */

#if defined(__clang__)
#if defined(_M_IX86) || defined(__i386__)

// Forward Declarations with exact 32-bit mangled names as asm symbols
BOOL WINAPI Godot_K32EnumProcessModulesEx(HANDLE hProcess, HMODULE * lphModule, DWORD cb, LPDWORD lpcbNeeded, DWORD dwFilterFlag) __asm__("_K32EnumProcessModulesEx@20");
DWORD WINAPI Godot_K32GetModuleBaseNameW(HANDLE hProcess, HMODULE hModule, LPWSTR lpBaseName, DWORD nSize) __asm__("_K32GetModuleBaseNameW@16");
BOOL WINAPI Godot_K32GetModuleInformation(HANDLE hProcess, HMODULE hModule, void * lpmodinfo, DWORD cb) __asm__("_K32GetModuleInformation@16");
VOID WINAPI Godot_GetCurrentProcessorNumberEx(PROCESSOR_NUMBER_INTERNAL * ProcNumber) __asm__("_GetCurrentProcessorNumberEx@4");
BOOLEAN WINAPI Godot_TryAcquireSRWLockExclusive(PSRWLOCK SRWLock) __asm__("_TryAcquireSRWLockExclusive@4");
BOOLEAN WINAPI Godot_TryAcquireSRWLockShared(PSRWLOCK SRWLock) __asm__("_TryAcquireSRWLockShared@4");
BOOL WINAPI Godot_GetLogicalProcessorInformationEx(int RelationshipType, void * Buffer, PDWORD ReturnedLength) __asm__("_GetLogicalProcessorInformationEx@12");
BOOL WINAPI Godot_GetThreadGroupAffinity(HANDLE hThread, void * GroupAffinity) __asm__("_GetThreadGroupAffinity@8");
BOOL WINAPI Godot_SetThreadGroupAffinity(HANDLE hThread, const void * GroupAffinity, void * PreviousGroupAffinity) __asm__("_SetThreadGroupAffinity@12");
BOOL WINAPI Godot_K32EnumProcessModules(HANDLE hProcess, HMODULE * lphModule, DWORD cb, LPDWORD lpcbNeeded) __asm__("_K32EnumProcessModules@16");

// Definitions
BOOL WINAPI Godot_K32EnumProcessModulesEx(HANDLE hProcess, HMODULE * lphModule, DWORD cb, LPDWORD lpcbNeeded, DWORD dwFilterFlag) {
	return VistaInternal_K32EnumProcessModulesEx(hProcess, lphModule, cb, lpcbNeeded, dwFilterFlag);
}
DWORD WINAPI Godot_K32GetModuleBaseNameW(HANDLE hProcess, HMODULE hModule, LPWSTR lpBaseName, DWORD nSize) {
	return VistaInternal_K32GetModuleBaseNameW(hProcess, hModule, lpBaseName, nSize);
}
BOOL WINAPI Godot_K32GetModuleInformation(HANDLE hProcess, HMODULE hModule, void * lpmodinfo, DWORD cb) {
	return VistaInternal_K32GetModuleInformation(hProcess, hModule, lpmodinfo, cb);
}
VOID WINAPI Godot_GetCurrentProcessorNumberEx(PROCESSOR_NUMBER_INTERNAL * ProcNumber) {
	VistaInternal_GetCurrentProcessorNumberEx(ProcNumber);
}
BOOLEAN WINAPI Godot_TryAcquireSRWLockExclusive(PSRWLOCK SRWLock) {
	return VistaInternal_TryAcquireSRWLockExclusive(SRWLock);
}
BOOLEAN WINAPI Godot_TryAcquireSRWLockShared(PSRWLOCK SRWLock) {
	return VistaInternal_TryAcquireSRWLockShared(SRWLock);
}
BOOL WINAPI Godot_GetLogicalProcessorInformationEx(int RelationshipType, void * Buffer, PDWORD ReturnedLength) {
	return VistaInternal_GetLogicalProcessorInformationEx(RelationshipType, Buffer, ReturnedLength);
}
BOOL WINAPI Godot_GetThreadGroupAffinity(HANDLE hThread, void * GroupAffinity) {
    return VistaInternal_GetThreadGroupAffinity(hThread, GroupAffinity);
}
BOOL WINAPI Godot_SetThreadGroupAffinity(HANDLE hThread, const void * GroupAffinity, void * PreviousGroupAffinity) {
    return VistaInternal_SetThreadGroupAffinity(hThread, GroupAffinity, PreviousGroupAffinity);
}
BOOL WINAPI Godot_K32EnumProcessModules(HANDLE hProcess, HMODULE * lphModule, DWORD cb, LPDWORD lpcbNeeded) {
    return VistaInternal_K32EnumProcessModules(hProcess, lphModule, cb, lpcbNeeded);
}

#else

// Forward Declarations with exact 64-bit names as asm symbols
BOOL WINAPI Godot_K32EnumProcessModulesEx(HANDLE hProcess, HMODULE * lphModule, DWORD cb, LPDWORD lpcbNeeded, DWORD dwFilterFlag) __asm__("K32EnumProcessModulesEx");
DWORD WINAPI Godot_K32GetModuleBaseNameW(HANDLE hProcess, HMODULE hModule, LPWSTR lpBaseName, DWORD nSize) __asm__("K32GetModuleBaseNameW");
BOOL WINAPI Godot_K32GetModuleInformation(HANDLE hProcess, HMODULE hModule, void * lpmodinfo, DWORD cb) __asm__("K32GetModuleInformation");
VOID WINAPI Godot_GetCurrentProcessorNumberEx(PROCESSOR_NUMBER_INTERNAL * ProcNumber) __asm__("GetCurrentProcessorNumberEx");
BOOLEAN WINAPI Godot_TryAcquireSRWLockExclusive(PSRWLOCK SRWLock) __asm__("TryAcquireSRWLockExclusive");
BOOLEAN WINAPI Godot_TryAcquireSRWLockShared(PSRWLOCK SRWLock) __asm__("TryAcquireSRWLockShared");
BOOL WINAPI Godot_GetLogicalProcessorInformationEx(int RelationshipType, void * Buffer, PDWORD ReturnedLength) __asm__("GetLogicalProcessorInformationEx");
BOOL WINAPI Godot_GetThreadGroupAffinity(HANDLE hThread, void * GroupAffinity) __asm__("GetThreadGroupAffinity");
BOOL WINAPI Godot_SetThreadGroupAffinity(HANDLE hThread, const void * GroupAffinity, void * PreviousGroupAffinity) __asm__("SetThreadGroupAffinity");
BOOL WINAPI Godot_K32EnumProcessModules(HANDLE hProcess, HMODULE * lphModule, DWORD cb, LPDWORD lpcbNeeded) __asm__("K32EnumProcessModules");

// Definitions
BOOL WINAPI Godot_K32EnumProcessModulesEx(HANDLE hProcess, HMODULE * lphModule, DWORD cb, LPDWORD lpcbNeeded, DWORD dwFilterFlag) {
	return VistaInternal_K32EnumProcessModulesEx(hProcess, lphModule, cb, lpcbNeeded, dwFilterFlag);
}
DWORD WINAPI Godot_K32GetModuleBaseNameW(HANDLE hProcess, HMODULE hModule, LPWSTR lpBaseName, DWORD nSize) {
	return VistaInternal_K32GetModuleBaseNameW(hProcess, hModule, lpBaseName, nSize);
}
BOOL WINAPI Godot_K32GetModuleInformation(HANDLE hProcess, HMODULE hModule, void * lpmodinfo, DWORD cb) {
	return VistaInternal_K32GetModuleInformation(hProcess, hModule, lpmodinfo, cb);
}
VOID WINAPI Godot_GetCurrentProcessorNumberEx(PROCESSOR_NUMBER_INTERNAL * ProcNumber) {
	VistaInternal_GetCurrentProcessorNumberEx(ProcNumber);
}
BOOLEAN WINAPI Godot_TryAcquireSRWLockExclusive(PSRWLOCK SRWLock) {
	return VistaInternal_TryAcquireSRWLockExclusive(SRWLock);
}
BOOLEAN WINAPI Godot_TryAcquireSRWLockShared(PSRWLOCK SRWLock) {
	return VistaInternal_TryAcquireSRWLockShared(SRWLock);
}
BOOL WINAPI Godot_GetLogicalProcessorInformationEx(int RelationshipType, void * Buffer, PDWORD ReturnedLength) {
	return VistaInternal_GetLogicalProcessorInformationEx(RelationshipType, Buffer, ReturnedLength);
}
BOOL WINAPI Godot_GetThreadGroupAffinity(HANDLE hThread, void * GroupAffinity) {
    return VistaInternal_GetThreadGroupAffinity(hThread, GroupAffinity);
}
BOOL WINAPI Godot_SetThreadGroupAffinity(HANDLE hThread, const void * GroupAffinity, void * PreviousGroupAffinity) {
    return VistaInternal_SetThreadGroupAffinity(hThread, GroupAffinity, PreviousGroupAffinity);
}
BOOL WINAPI Godot_K32EnumProcessModules(HANDLE hProcess, HMODULE * lphModule, DWORD cb, LPDWORD lpcbNeeded) {
    return VistaInternal_K32EnumProcessModules(hProcess, lphModule, cb, lpcbNeeded);
}

#endif // M_IX86 || __i386__

#else

// Fallback code for MSVC compiler
BOOL WINAPI Godot_K32EnumProcessModulesEx(HANDLE hProcess, HMODULE * lphModule, DWORD cb, LPDWORD lpcbNeeded, DWORD dwFilterFlag) {
	return VistaInternal_K32EnumProcessModulesEx(hProcess, lphModule, cb, lpcbNeeded, dwFilterFlag);
}
DWORD WINAPI Godot_K32GetModuleBaseNameW(HANDLE hProcess, HMODULE hModule, LPWSTR lpBaseName, DWORD nSize) {
	return VistaInternal_K32GetModuleBaseNameW(hProcess, hModule, lpBaseName, nSize);
}
BOOL WINAPI Godot_K32GetModuleInformation(HANDLE hProcess, HMODULE hModule, void * lpmodinfo, DWORD cb) {
	return VistaInternal_K32GetModuleInformation(hProcess, hModule, lpmodinfo, cb);
}
VOID WINAPI Godot_GetCurrentProcessorNumberEx(PROCESSOR_NUMBER_INTERNAL * ProcNumber) {
	VistaInternal_GetCurrentProcessorNumberEx(ProcNumber);
}
BOOLEAN WINAPI Godot_TryAcquireSRWLockExclusive(PSRWLOCK SRWLock) {
	return VistaInternal_TryAcquireSRWLockExclusive(SRWLock);
}
BOOLEAN WINAPI Godot_TryAcquireSRWLockShared(PSRWLOCK SRWLock) {
	return VistaInternal_TryAcquireSRWLockShared(SRWLock);
}
BOOL WINAPI Godot_GetLogicalProcessorInformationEx(int RelationshipType, void * Buffer, PDWORD ReturnedLength) {
	return VistaInternal_GetLogicalProcessorInformationEx(RelationshipType, Buffer, ReturnedLength);
}
BOOL WINAPI Godot_GetThreadGroupAffinity(HANDLE hThread, void * GroupAffinity) {
    return VistaInternal_GetThreadGroupAffinity(hThread, GroupAffinity);
}
BOOL WINAPI Godot_SetThreadGroupAffinity(HANDLE hThread, const void * GroupAffinity, void * PreviousGroupAffinity) {
    return VistaInternal_SetThreadGroupAffinity(hThread, GroupAffinity, PreviousGroupAffinity);
}
BOOL WINAPI Godot_K32EnumProcessModules(HANDLE hProcess, HMODULE * lphModule, DWORD cb, LPDWORD lpcbNeeded) {
    return VistaInternal_K32EnumProcessModules(hProcess, lphModule, cb, lpcbNeeded);
}

#endif // __clang__

/* =========================================================================== */
/* Thunks implementations                                                      */
/* =========================================================================== */

typedef BOOLEAN (WINAPI *PFN_TryAcquireSRWLock)(PSRWLOCK);
typedef DWORD (WINAPI *PFN_GetModuleBaseNameW)(HANDLE, HMODULE, LPWSTR, DWORD);
typedef BOOL (WINAPI *PFN_GetModuleInformation)(HANDLE, HMODULE, void*, DWORD);
typedef BOOL (WINAPI *PFN_EnumProcessModulesEx)(HANDLE, HMODULE*, DWORD, LPDWORD, DWORD);
typedef VOID (WINAPI *PFN_GetCurrentProcessorNumberEx)(PROCESSOR_NUMBER_INTERNAL*);
typedef BOOL (WINAPI *PFN_GetLogicalProcessorInformationEx)(int, void*, PDWORD);
typedef BOOL (WINAPI *PFN_GetThreadGroupAffinity)(HANDLE, void*);
typedef BOOL (WINAPI *PFN_SetThreadGroupAffinity)(HANDLE, const void*, void*);
typedef BOOL (WINAPI *PFN_EnumProcessModules)(HANDLE, HMODULE*, DWORD, LPDWORD);

static BOOLEAN WINAPI VistaInternal_TryAcquireSRWLockExclusive(PSRWLOCK SRWLock) {
	static PFN_TryAcquireSRWLock pRealFunc = NULL;
	if (!pRealFunc) {
		pRealFunc = (PFN_TryAcquireSRWLock)GetProcAddress(GetModuleHandleW(L"kernel32.dll"), "TryAcquireSRWLockExclusive");
	}
	if (pRealFunc) {
		return pRealFunc(SRWLock);
	}
	return FALSE; 
}

static BOOLEAN WINAPI VistaInternal_TryAcquireSRWLockShared(PSRWLOCK SRWLock) {
	static PFN_TryAcquireSRWLock pRealFunc = NULL;
	if (!pRealFunc) {
		pRealFunc = (PFN_TryAcquireSRWLock)GetProcAddress(GetModuleHandleW(L"kernel32.dll"), "TryAcquireSRWLockShared");
	}
	if (pRealFunc) {
		return pRealFunc(SRWLock);
	}
	return FALSE; 
}

static BOOL WINAPI VistaInternal_K32EnumProcessModulesEx(HANDLE hProcess, HMODULE* lphModule, DWORD cb, LPDWORD lpcbNeeded, DWORD dwFilterFlag) {
	static PFN_EnumProcessModulesEx pRealFunc = NULL;
	if (!pRealFunc) {
		pRealFunc = (PFN_EnumProcessModulesEx)GetProcAddress(GetModuleHandleW(L"kernel32.dll"), "K32EnumProcessModulesEx");
	}
	if (pRealFunc) {
		return pRealFunc(hProcess, lphModule, cb, lpcbNeeded, dwFilterFlag);
	}

	// Fallback via psapi.dll
	static PFN_EnumProcessModulesEx pFallbackFunc = NULL;
	static BOOL fallback_init = FALSE;
	if (!fallback_init) {
		HMODULE hPsapi = GetModuleHandleW(L"psapi.dll");
		if (!hPsapi) {
			hPsapi = LoadLibraryW(L"psapi.dll");
		}
		if (hPsapi) {
			pFallbackFunc = (PFN_EnumProcessModulesEx)GetProcAddress(hPsapi, "EnumProcessModulesEx");
		}
		fallback_init = TRUE;
	}
	if (pFallbackFunc) {
		return pFallbackFunc(hProcess, lphModule, cb, lpcbNeeded, dwFilterFlag);
	}
	return FALSE;
}

static DWORD WINAPI VistaInternal_K32GetModuleBaseNameW(HANDLE hProcess, HMODULE hModule, LPWSTR lpBaseName, DWORD nSize) {
	static PFN_GetModuleBaseNameW pRealFunc = NULL;
	if (!pRealFunc) {
		pRealFunc = (PFN_GetModuleBaseNameW)GetProcAddress(GetModuleHandleW(L"kernel32.dll"), "K32GetModuleBaseNameW");
	}
	if (pRealFunc) {
		return pRealFunc(hProcess, hModule, lpBaseName, nSize);
	}

	// Fallback via psapi.dll
	static PFN_GetModuleBaseNameW pFallbackFunc = NULL;
	static BOOL fallback_init = FALSE;
	if (!fallback_init) {
		HMODULE hPsapi = GetModuleHandleW(L"psapi.dll");
		if (!hPsapi) {
			hPsapi = LoadLibraryW(L"psapi.dll");
		}
		if (hPsapi) {
			pFallbackFunc = (PFN_GetModuleBaseNameW)GetProcAddress(hPsapi, "GetModuleBaseNameW");
		}
		fallback_init = TRUE;
	}
	if (pFallbackFunc) {
		return pFallbackFunc(hProcess, hModule, lpBaseName, nSize);
	}
	return 0;
}

static BOOL WINAPI VistaInternal_K32GetModuleInformation(HANDLE hProcess, HMODULE hModule, void* lpmodinfo, DWORD cb) {
	static PFN_GetModuleInformation pRealFunc = NULL;
	if (!pRealFunc) {
		pRealFunc = (PFN_GetModuleInformation)GetProcAddress(GetModuleHandleW(L"kernel32.dll"), "K32GetModuleInformation");
	}
	if (pRealFunc) {
		return pRealFunc(hProcess, hModule, lpmodinfo, cb);
	}

	// Fallback via psapi.dll
	static PFN_GetModuleInformation pFallbackFunc = NULL;
	static BOOL fallback_init = FALSE;
	if (!fallback_init) {
		HMODULE hPsapi = GetModuleHandleW(L"psapi.dll");
		if (!hPsapi) {
			hPsapi = LoadLibraryW(L"psapi.dll");
		}
		if (hPsapi) {
			pFallbackFunc = (PFN_GetModuleInformation)GetProcAddress(hPsapi, "GetModuleInformation");
		}
		fallback_init = TRUE;
	}

	if (pFallbackFunc) {
		return pFallbackFunc(hProcess, hModule, lpmodinfo, cb);
	}
	return FALSE;
}

static VOID WINAPI VistaInternal_GetCurrentProcessorNumberEx(PROCESSOR_NUMBER_INTERNAL* ProcNumber) {
	static PFN_GetCurrentProcessorNumberEx pRealFunc = NULL;
	if (!pRealFunc) {
		pRealFunc = (PFN_GetCurrentProcessorNumberEx)GetProcAddress(GetModuleHandleW(L"kernel32.dll"), "GetCurrentProcessorNumberEx");
	}
	if (pRealFunc) {
		pRealFunc(ProcNumber);
		return;
	}

	// Fallback with bare minimum of what the API
	// expects
	if (ProcNumber) {
		ProcNumber->Group = 0; 
		ProcNumber->Number = (BYTE)GetCurrentProcessorNumber();
		ProcNumber->Reserved = 0;
	}
}

static BOOL WINAPI VistaInternal_GetLogicalProcessorInformationEx(int RelationshipType, void* Buffer, PDWORD ReturnedLength) {
	static PFN_GetLogicalProcessorInformationEx pRealFunc = NULL;
	if (!pRealFunc) {
		pRealFunc = (PFN_GetLogicalProcessorInformationEx)GetProcAddress(GetModuleHandleW(L"kernel32.dll"), "GetLogicalProcessorInformationEx");
	}
	if (pRealFunc) {
		return pRealFunc(RelationshipType, Buffer, ReturnedLength);
	}
	
	if (ReturnedLength) {
		*ReturnedLength = 0;
	}
	SetLastError(ERROR_CALL_NOT_IMPLEMENTED);
	return FALSE;
}

static BOOL WINAPI VistaInternal_GetThreadGroupAffinity(HANDLE hThread, void* GroupAffinity) {
	static PFN_GetThreadGroupAffinity pRealFunc = NULL;
	if (!pRealFunc) {
		pRealFunc = (PFN_GetThreadGroupAffinity)GetProcAddress(GetModuleHandleW(L"kernel32.dll"), "GetThreadGroupAffinity");
	}
	if (pRealFunc) {
		return pRealFunc(hThread, GroupAffinity);
	}
	
	SetLastError(ERROR_CALL_NOT_IMPLEMENTED);
	return FALSE;
}

static BOOL WINAPI VistaInternal_SetThreadGroupAffinity(HANDLE hThread, const void* GroupAffinity, void* PreviousGroupAffinity) {
	static PFN_SetThreadGroupAffinity pRealFunc = NULL;
	if (!pRealFunc) {
		pRealFunc = (PFN_SetThreadGroupAffinity)GetProcAddress(GetModuleHandleW(L"kernel32.dll"), "SetThreadGroupAffinity");
	}
	if (pRealFunc) {
		return pRealFunc(hThread, GroupAffinity, PreviousGroupAffinity);
	}
	
	SetLastError(ERROR_CALL_NOT_IMPLEMENTED);
	return FALSE;
}

static BOOL WINAPI VistaInternal_K32EnumProcessModules(HANDLE hProcess, HMODULE* lphModule, DWORD cb, LPDWORD lpcbNeeded) {
	static PFN_EnumProcessModules pRealFunc = NULL;
	if (!pRealFunc) {
		pRealFunc = (PFN_EnumProcessModules)GetProcAddress(GetModuleHandleW(L"kernel32.dll"), "K32EnumProcessModules");
	}
	if (pRealFunc) {
		return pRealFunc(hProcess, lphModule, cb, lpcbNeeded);
	}

	// Fallback via psapi.dll
	static PFN_EnumProcessModules pFallbackFunc = NULL;
	static BOOL fallback_init = FALSE;
	if (!fallback_init) {
		HMODULE hPsapi = GetModuleHandleW(L"psapi.dll");
		if (!hPsapi) {
			hPsapi = LoadLibraryW(L"psapi.dll");
		}
		if (hPsapi) {
			pFallbackFunc = (PFN_EnumProcessModules)GetProcAddress(hPsapi, "EnumProcessModules");
		}
		fallback_init = TRUE;
	}
	if (pFallbackFunc) {
		return pFallbackFunc(hProcess, lphModule, cb, lpcbNeeded);
	}
	return FALSE;
}

#endif // defined(WINVER) && WINVER < 0x0601