// This file is generated. Do not edit!
// see https://github.com/hpvb/dynload-wrapper for details
// generated by generate-wrapper.py 0.7 on 2026-03-13 16:30:46
// flags: generate-wrapper.py --include /home/build/github/godot/thirdparty/linuxbsd_headers/fontconfig/fontconfig.h --sys-include thirdparty/linuxbsd_headers/fontconfig/fontconfig.h --soname libfontconfig.so.1 --init-name fontconfig --omit-prefix FcCharSetFirst --omit-prefix FcCharSetNext --output-header /home/build/github/godot/platform/linuxbsd/fontconfig-so_wrap.h --output-implementation /home/build/github/godot/platform/linuxbsd/fontconfig-so_wrap.c
//
#include <stdint.h>

#define FcBlanksCreate FcBlanksCreate_dylibloader_orig_fontconfig
#define FcBlanksDestroy FcBlanksDestroy_dylibloader_orig_fontconfig
#define FcBlanksAdd FcBlanksAdd_dylibloader_orig_fontconfig
#define FcBlanksIsMember FcBlanksIsMember_dylibloader_orig_fontconfig
#define FcCacheDir FcCacheDir_dylibloader_orig_fontconfig
#define FcCacheCopySet FcCacheCopySet_dylibloader_orig_fontconfig
#define FcCacheSubdir FcCacheSubdir_dylibloader_orig_fontconfig
#define FcCacheNumSubdir FcCacheNumSubdir_dylibloader_orig_fontconfig
#define FcCacheNumFont FcCacheNumFont_dylibloader_orig_fontconfig
#define FcDirCacheUnlink FcDirCacheUnlink_dylibloader_orig_fontconfig
#define FcDirCacheValid FcDirCacheValid_dylibloader_orig_fontconfig
#define FcDirCacheClean FcDirCacheClean_dylibloader_orig_fontconfig
#define FcCacheCreateTagFile FcCacheCreateTagFile_dylibloader_orig_fontconfig
#define FcConfigHome FcConfigHome_dylibloader_orig_fontconfig
#define FcConfigEnableHome FcConfigEnableHome_dylibloader_orig_fontconfig
#define FcConfigFilename FcConfigFilename_dylibloader_orig_fontconfig
#define FcConfigCreate FcConfigCreate_dylibloader_orig_fontconfig
#define FcConfigReference FcConfigReference_dylibloader_orig_fontconfig
#define FcConfigDestroy FcConfigDestroy_dylibloader_orig_fontconfig
#define FcConfigSetCurrent FcConfigSetCurrent_dylibloader_orig_fontconfig
#define FcConfigGetCurrent FcConfigGetCurrent_dylibloader_orig_fontconfig
#define FcConfigUptoDate FcConfigUptoDate_dylibloader_orig_fontconfig
#define FcConfigBuildFonts FcConfigBuildFonts_dylibloader_orig_fontconfig
#define FcConfigGetFontDirs FcConfigGetFontDirs_dylibloader_orig_fontconfig
#define FcConfigGetConfigDirs FcConfigGetConfigDirs_dylibloader_orig_fontconfig
#define FcConfigGetConfigFiles FcConfigGetConfigFiles_dylibloader_orig_fontconfig
#define FcConfigGetCache FcConfigGetCache_dylibloader_orig_fontconfig
#define FcConfigGetBlanks FcConfigGetBlanks_dylibloader_orig_fontconfig
#define FcConfigGetCacheDirs FcConfigGetCacheDirs_dylibloader_orig_fontconfig
#define FcConfigGetRescanInterval FcConfigGetRescanInterval_dylibloader_orig_fontconfig
#define FcConfigSetRescanInterval FcConfigSetRescanInterval_dylibloader_orig_fontconfig
#define FcConfigGetFonts FcConfigGetFonts_dylibloader_orig_fontconfig
#define FcConfigAppFontAddFile FcConfigAppFontAddFile_dylibloader_orig_fontconfig
#define FcConfigAppFontAddDir FcConfigAppFontAddDir_dylibloader_orig_fontconfig
#define FcConfigAppFontClear FcConfigAppFontClear_dylibloader_orig_fontconfig
#define FcConfigSubstituteWithPat FcConfigSubstituteWithPat_dylibloader_orig_fontconfig
#define FcConfigSubstitute FcConfigSubstitute_dylibloader_orig_fontconfig
#define FcConfigGetSysRoot FcConfigGetSysRoot_dylibloader_orig_fontconfig
#define FcConfigSetSysRoot FcConfigSetSysRoot_dylibloader_orig_fontconfig
#define FcCharSetCreate FcCharSetCreate_dylibloader_orig_fontconfig
#define FcCharSetNew FcCharSetNew_dylibloader_orig_fontconfig
#define FcCharSetDestroy FcCharSetDestroy_dylibloader_orig_fontconfig
#define FcCharSetAddChar FcCharSetAddChar_dylibloader_orig_fontconfig
#define FcCharSetDelChar FcCharSetDelChar_dylibloader_orig_fontconfig
#define FcCharSetCopy FcCharSetCopy_dylibloader_orig_fontconfig
#define FcCharSetEqual FcCharSetEqual_dylibloader_orig_fontconfig
#define FcCharSetIntersect FcCharSetIntersect_dylibloader_orig_fontconfig
#define FcCharSetUnion FcCharSetUnion_dylibloader_orig_fontconfig
#define FcCharSetSubtract FcCharSetSubtract_dylibloader_orig_fontconfig
#define FcCharSetMerge FcCharSetMerge_dylibloader_orig_fontconfig
#define FcCharSetHasChar FcCharSetHasChar_dylibloader_orig_fontconfig
#define FcCharSetCount FcCharSetCount_dylibloader_orig_fontconfig
#define FcCharSetIntersectCount FcCharSetIntersectCount_dylibloader_orig_fontconfig
#define FcCharSetSubtractCount FcCharSetSubtractCount_dylibloader_orig_fontconfig
#define FcCharSetIsSubset FcCharSetIsSubset_dylibloader_orig_fontconfig
#define FcCharSetCoverage FcCharSetCoverage_dylibloader_orig_fontconfig
#define FcValuePrint FcValuePrint_dylibloader_orig_fontconfig
#define FcPatternPrint FcPatternPrint_dylibloader_orig_fontconfig
#define FcFontSetPrint FcFontSetPrint_dylibloader_orig_fontconfig
#define FcGetDefaultLangs FcGetDefaultLangs_dylibloader_orig_fontconfig
#define FcDefaultSubstitute FcDefaultSubstitute_dylibloader_orig_fontconfig
#define FcFileIsDir FcFileIsDir_dylibloader_orig_fontconfig
#define FcFileScan FcFileScan_dylibloader_orig_fontconfig
#define FcDirScan FcDirScan_dylibloader_orig_fontconfig
#define FcDirSave FcDirSave_dylibloader_orig_fontconfig
#define FcDirCacheLoad FcDirCacheLoad_dylibloader_orig_fontconfig
#define FcDirCacheRescan FcDirCacheRescan_dylibloader_orig_fontconfig
#define FcDirCacheRead FcDirCacheRead_dylibloader_orig_fontconfig
#define FcDirCacheLoadFile FcDirCacheLoadFile_dylibloader_orig_fontconfig
#define FcDirCacheUnload FcDirCacheUnload_dylibloader_orig_fontconfig
#define FcFreeTypeQuery FcFreeTypeQuery_dylibloader_orig_fontconfig
#define FcFontSetCreate FcFontSetCreate_dylibloader_orig_fontconfig
#define FcFontSetDestroy FcFontSetDestroy_dylibloader_orig_fontconfig
#define FcFontSetAdd FcFontSetAdd_dylibloader_orig_fontconfig
#define FcInitLoadConfig FcInitLoadConfig_dylibloader_orig_fontconfig
#define FcInitLoadConfigAndFonts FcInitLoadConfigAndFonts_dylibloader_orig_fontconfig
#define FcInit FcInit_dylibloader_orig_fontconfig
#define FcFini FcFini_dylibloader_orig_fontconfig
#define FcGetVersion FcGetVersion_dylibloader_orig_fontconfig
#define FcInitReinitialize FcInitReinitialize_dylibloader_orig_fontconfig
#define FcInitBringUptoDate FcInitBringUptoDate_dylibloader_orig_fontconfig
#define FcGetLangs FcGetLangs_dylibloader_orig_fontconfig
#define FcLangNormalize FcLangNormalize_dylibloader_orig_fontconfig
#define FcLangGetCharSet FcLangGetCharSet_dylibloader_orig_fontconfig
#define FcLangSetCreate FcLangSetCreate_dylibloader_orig_fontconfig
#define FcLangSetDestroy FcLangSetDestroy_dylibloader_orig_fontconfig
#define FcLangSetCopy FcLangSetCopy_dylibloader_orig_fontconfig
#define FcLangSetAdd FcLangSetAdd_dylibloader_orig_fontconfig
#define FcLangSetDel FcLangSetDel_dylibloader_orig_fontconfig
#define FcLangSetHasLang FcLangSetHasLang_dylibloader_orig_fontconfig
#define FcLangSetCompare FcLangSetCompare_dylibloader_orig_fontconfig
#define FcLangSetContains FcLangSetContains_dylibloader_orig_fontconfig
#define FcLangSetEqual FcLangSetEqual_dylibloader_orig_fontconfig
#define FcLangSetHash FcLangSetHash_dylibloader_orig_fontconfig
#define FcLangSetGetLangs FcLangSetGetLangs_dylibloader_orig_fontconfig
#define FcLangSetUnion FcLangSetUnion_dylibloader_orig_fontconfig
#define FcLangSetSubtract FcLangSetSubtract_dylibloader_orig_fontconfig
#define FcObjectSetCreate FcObjectSetCreate_dylibloader_orig_fontconfig
#define FcObjectSetAdd FcObjectSetAdd_dylibloader_orig_fontconfig
#define FcObjectSetDestroy FcObjectSetDestroy_dylibloader_orig_fontconfig
#define FcObjectSetVaBuild FcObjectSetVaBuild_dylibloader_orig_fontconfig
#define FcObjectSetBuild FcObjectSetBuild_dylibloader_orig_fontconfig
#define FcFontSetList FcFontSetList_dylibloader_orig_fontconfig
#define FcFontList FcFontList_dylibloader_orig_fontconfig
#define FcAtomicCreate FcAtomicCreate_dylibloader_orig_fontconfig
#define FcAtomicLock FcAtomicLock_dylibloader_orig_fontconfig
#define FcAtomicNewFile FcAtomicNewFile_dylibloader_orig_fontconfig
#define FcAtomicOrigFile FcAtomicOrigFile_dylibloader_orig_fontconfig
#define FcAtomicReplaceOrig FcAtomicReplaceOrig_dylibloader_orig_fontconfig
#define FcAtomicDeleteNew FcAtomicDeleteNew_dylibloader_orig_fontconfig
#define FcAtomicUnlock FcAtomicUnlock_dylibloader_orig_fontconfig
#define FcAtomicDestroy FcAtomicDestroy_dylibloader_orig_fontconfig
#define FcFontSetMatch FcFontSetMatch_dylibloader_orig_fontconfig
#define FcFontMatch FcFontMatch_dylibloader_orig_fontconfig
#define FcFontRenderPrepare FcFontRenderPrepare_dylibloader_orig_fontconfig
#define FcFontSetSort FcFontSetSort_dylibloader_orig_fontconfig
#define FcFontSort FcFontSort_dylibloader_orig_fontconfig
#define FcFontSetSortDestroy FcFontSetSortDestroy_dylibloader_orig_fontconfig
#define FcMatrixCopy FcMatrixCopy_dylibloader_orig_fontconfig
#define FcMatrixEqual FcMatrixEqual_dylibloader_orig_fontconfig
#define FcMatrixMultiply FcMatrixMultiply_dylibloader_orig_fontconfig
#define FcMatrixRotate FcMatrixRotate_dylibloader_orig_fontconfig
#define FcMatrixScale FcMatrixScale_dylibloader_orig_fontconfig
#define FcMatrixShear FcMatrixShear_dylibloader_orig_fontconfig
#define FcNameRegisterObjectTypes FcNameRegisterObjectTypes_dylibloader_orig_fontconfig
#define FcNameUnregisterObjectTypes FcNameUnregisterObjectTypes_dylibloader_orig_fontconfig
#define FcNameGetObjectType FcNameGetObjectType_dylibloader_orig_fontconfig
#define FcNameRegisterConstants FcNameRegisterConstants_dylibloader_orig_fontconfig
#define FcNameUnregisterConstants FcNameUnregisterConstants_dylibloader_orig_fontconfig
#define FcNameGetConstant FcNameGetConstant_dylibloader_orig_fontconfig
#define FcNameConstant FcNameConstant_dylibloader_orig_fontconfig
#define FcNameParse FcNameParse_dylibloader_orig_fontconfig
#define FcNameUnparse FcNameUnparse_dylibloader_orig_fontconfig
#define FcPatternCreate FcPatternCreate_dylibloader_orig_fontconfig
#define FcPatternDuplicate FcPatternDuplicate_dylibloader_orig_fontconfig
#define FcPatternReference FcPatternReference_dylibloader_orig_fontconfig
#define FcPatternFilter FcPatternFilter_dylibloader_orig_fontconfig
#define FcValueDestroy FcValueDestroy_dylibloader_orig_fontconfig
#define FcValueEqual FcValueEqual_dylibloader_orig_fontconfig
#define FcValueSave FcValueSave_dylibloader_orig_fontconfig
#define FcPatternDestroy FcPatternDestroy_dylibloader_orig_fontconfig
#define FcPatternEqual FcPatternEqual_dylibloader_orig_fontconfig
#define FcPatternEqualSubset FcPatternEqualSubset_dylibloader_orig_fontconfig
#define FcPatternHash FcPatternHash_dylibloader_orig_fontconfig
#define FcPatternAdd FcPatternAdd_dylibloader_orig_fontconfig
#define FcPatternAddWeak FcPatternAddWeak_dylibloader_orig_fontconfig
#define FcPatternGet FcPatternGet_dylibloader_orig_fontconfig
#define FcPatternGetWithBinding FcPatternGetWithBinding_dylibloader_orig_fontconfig
#define FcPatternDel FcPatternDel_dylibloader_orig_fontconfig
#define FcPatternRemove FcPatternRemove_dylibloader_orig_fontconfig
#define FcPatternAddInteger FcPatternAddInteger_dylibloader_orig_fontconfig
#define FcPatternAddDouble FcPatternAddDouble_dylibloader_orig_fontconfig
#define FcPatternAddString FcPatternAddString_dylibloader_orig_fontconfig
#define FcPatternAddMatrix FcPatternAddMatrix_dylibloader_orig_fontconfig
#define FcPatternAddCharSet FcPatternAddCharSet_dylibloader_orig_fontconfig
#define FcPatternAddBool FcPatternAddBool_dylibloader_orig_fontconfig
#define FcPatternAddLangSet FcPatternAddLangSet_dylibloader_orig_fontconfig
#define FcPatternAddRange FcPatternAddRange_dylibloader_orig_fontconfig
#define FcPatternGetInteger FcPatternGetInteger_dylibloader_orig_fontconfig
#define FcPatternGetDouble FcPatternGetDouble_dylibloader_orig_fontconfig
#define FcPatternGetString FcPatternGetString_dylibloader_orig_fontconfig
#define FcPatternGetMatrix FcPatternGetMatrix_dylibloader_orig_fontconfig
#define FcPatternGetCharSet FcPatternGetCharSet_dylibloader_orig_fontconfig
#define FcPatternGetBool FcPatternGetBool_dylibloader_orig_fontconfig
#define FcPatternGetLangSet FcPatternGetLangSet_dylibloader_orig_fontconfig
#define FcPatternGetRange FcPatternGetRange_dylibloader_orig_fontconfig
#define FcPatternVaBuild FcPatternVaBuild_dylibloader_orig_fontconfig
#define FcPatternBuild FcPatternBuild_dylibloader_orig_fontconfig
#define FcPatternFormat FcPatternFormat_dylibloader_orig_fontconfig
#define FcRangeCreateDouble FcRangeCreateDouble_dylibloader_orig_fontconfig
#define FcRangeCreateInteger FcRangeCreateInteger_dylibloader_orig_fontconfig
#define FcRangeDestroy FcRangeDestroy_dylibloader_orig_fontconfig
#define FcRangeCopy FcRangeCopy_dylibloader_orig_fontconfig
#define FcRangeGetDouble FcRangeGetDouble_dylibloader_orig_fontconfig
#define FcWeightFromOpenType FcWeightFromOpenType_dylibloader_orig_fontconfig
#define FcWeightToOpenType FcWeightToOpenType_dylibloader_orig_fontconfig
#define FcStrCopy FcStrCopy_dylibloader_orig_fontconfig
#define FcStrCopyFilename FcStrCopyFilename_dylibloader_orig_fontconfig
#define FcStrPlus FcStrPlus_dylibloader_orig_fontconfig
#define FcStrFree FcStrFree_dylibloader_orig_fontconfig
#define FcStrDowncase FcStrDowncase_dylibloader_orig_fontconfig
#define FcStrCmpIgnoreCase FcStrCmpIgnoreCase_dylibloader_orig_fontconfig
#define FcStrCmp FcStrCmp_dylibloader_orig_fontconfig
#define FcStrStrIgnoreCase FcStrStrIgnoreCase_dylibloader_orig_fontconfig
#define FcStrStr FcStrStr_dylibloader_orig_fontconfig
#define FcUtf8ToUcs4 FcUtf8ToUcs4_dylibloader_orig_fontconfig
#define FcUtf8Len FcUtf8Len_dylibloader_orig_fontconfig
#define FcUcs4ToUtf8 FcUcs4ToUtf8_dylibloader_orig_fontconfig
#define FcUtf16ToUcs4 FcUtf16ToUcs4_dylibloader_orig_fontconfig
#define FcUtf16Len FcUtf16Len_dylibloader_orig_fontconfig
#define FcStrDirname FcStrDirname_dylibloader_orig_fontconfig
#define FcStrBasename FcStrBasename_dylibloader_orig_fontconfig
#define FcStrSetCreate FcStrSetCreate_dylibloader_orig_fontconfig
#define FcStrSetMember FcStrSetMember_dylibloader_orig_fontconfig
#define FcStrSetEqual FcStrSetEqual_dylibloader_orig_fontconfig
#define FcStrSetAdd FcStrSetAdd_dylibloader_orig_fontconfig
#define FcStrSetAddFilename FcStrSetAddFilename_dylibloader_orig_fontconfig
#define FcStrSetDel FcStrSetDel_dylibloader_orig_fontconfig
#define FcStrSetDestroy FcStrSetDestroy_dylibloader_orig_fontconfig
#define FcStrListCreate FcStrListCreate_dylibloader_orig_fontconfig
#define FcStrListFirst FcStrListFirst_dylibloader_orig_fontconfig
#define FcStrListNext FcStrListNext_dylibloader_orig_fontconfig
#define FcStrListDone FcStrListDone_dylibloader_orig_fontconfig
#define FcConfigParseAndLoad FcConfigParseAndLoad_dylibloader_orig_fontconfig
#define FcConfigParseAndLoadFromMemory FcConfigParseAndLoadFromMemory_dylibloader_orig_fontconfig
#include "thirdparty/linuxbsd_headers/fontconfig/fontconfig.h" // IWYU pragma: export.
#undef FcBlanksCreate
#undef FcBlanksDestroy
#undef FcBlanksAdd
#undef FcBlanksIsMember
#undef FcCacheDir
#undef FcCacheCopySet
#undef FcCacheSubdir
#undef FcCacheNumSubdir
#undef FcCacheNumFont
#undef FcDirCacheUnlink
#undef FcDirCacheValid
#undef FcDirCacheClean
#undef FcCacheCreateTagFile
#undef FcConfigHome
#undef FcConfigEnableHome
#undef FcConfigFilename
#undef FcConfigCreate
#undef FcConfigReference
#undef FcConfigDestroy
#undef FcConfigSetCurrent
#undef FcConfigGetCurrent
#undef FcConfigUptoDate
#undef FcConfigBuildFonts
#undef FcConfigGetFontDirs
#undef FcConfigGetConfigDirs
#undef FcConfigGetConfigFiles
#undef FcConfigGetCache
#undef FcConfigGetBlanks
#undef FcConfigGetCacheDirs
#undef FcConfigGetRescanInterval
#undef FcConfigSetRescanInterval
#undef FcConfigGetFonts
#undef FcConfigAppFontAddFile
#undef FcConfigAppFontAddDir
#undef FcConfigAppFontClear
#undef FcConfigSubstituteWithPat
#undef FcConfigSubstitute
#undef FcConfigGetSysRoot
#undef FcConfigSetSysRoot
#undef FcCharSetCreate
#undef FcCharSetNew
#undef FcCharSetDestroy
#undef FcCharSetAddChar
#undef FcCharSetDelChar
#undef FcCharSetCopy
#undef FcCharSetEqual
#undef FcCharSetIntersect
#undef FcCharSetUnion
#undef FcCharSetSubtract
#undef FcCharSetMerge
#undef FcCharSetHasChar
#undef FcCharSetCount
#undef FcCharSetIntersectCount
#undef FcCharSetSubtractCount
#undef FcCharSetIsSubset
#undef FcCharSetCoverage
#undef FcValuePrint
#undef FcPatternPrint
#undef FcFontSetPrint
#undef FcGetDefaultLangs
#undef FcDefaultSubstitute
#undef FcFileIsDir
#undef FcFileScan
#undef FcDirScan
#undef FcDirSave
#undef FcDirCacheLoad
#undef FcDirCacheRescan
#undef FcDirCacheRead
#undef FcDirCacheLoadFile
#undef FcDirCacheUnload
#undef FcFreeTypeQuery
#undef FcFontSetCreate
#undef FcFontSetDestroy
#undef FcFontSetAdd
#undef FcInitLoadConfig
#undef FcInitLoadConfigAndFonts
#undef FcInit
#undef FcFini
#undef FcGetVersion
#undef FcInitReinitialize
#undef FcInitBringUptoDate
#undef FcGetLangs
#undef FcLangNormalize
#undef FcLangGetCharSet
#undef FcLangSetCreate
#undef FcLangSetDestroy
#undef FcLangSetCopy
#undef FcLangSetAdd
#undef FcLangSetDel
#undef FcLangSetHasLang
#undef FcLangSetCompare
#undef FcLangSetContains
#undef FcLangSetEqual
#undef FcLangSetHash
#undef FcLangSetGetLangs
#undef FcLangSetUnion
#undef FcLangSetSubtract
#undef FcObjectSetCreate
#undef FcObjectSetAdd
#undef FcObjectSetDestroy
#undef FcObjectSetVaBuild
#undef FcObjectSetBuild
#undef FcFontSetList
#undef FcFontList
#undef FcAtomicCreate
#undef FcAtomicLock
#undef FcAtomicNewFile
#undef FcAtomicOrigFile
#undef FcAtomicReplaceOrig
#undef FcAtomicDeleteNew
#undef FcAtomicUnlock
#undef FcAtomicDestroy
#undef FcFontSetMatch
#undef FcFontMatch
#undef FcFontRenderPrepare
#undef FcFontSetSort
#undef FcFontSort
#undef FcFontSetSortDestroy
#undef FcMatrixCopy
#undef FcMatrixEqual
#undef FcMatrixMultiply
#undef FcMatrixRotate
#undef FcMatrixScale
#undef FcMatrixShear
#undef FcNameRegisterObjectTypes
#undef FcNameUnregisterObjectTypes
#undef FcNameGetObjectType
#undef FcNameRegisterConstants
#undef FcNameUnregisterConstants
#undef FcNameGetConstant
#undef FcNameConstant
#undef FcNameParse
#undef FcNameUnparse
#undef FcPatternCreate
#undef FcPatternDuplicate
#undef FcPatternReference
#undef FcPatternFilter
#undef FcValueDestroy
#undef FcValueEqual
#undef FcValueSave
#undef FcPatternDestroy
#undef FcPatternEqual
#undef FcPatternEqualSubset
#undef FcPatternHash
#undef FcPatternAdd
#undef FcPatternAddWeak
#undef FcPatternGet
#undef FcPatternGetWithBinding
#undef FcPatternDel
#undef FcPatternRemove
#undef FcPatternAddInteger
#undef FcPatternAddDouble
#undef FcPatternAddString
#undef FcPatternAddMatrix
#undef FcPatternAddCharSet
#undef FcPatternAddBool
#undef FcPatternAddLangSet
#undef FcPatternAddRange
#undef FcPatternGetInteger
#undef FcPatternGetDouble
#undef FcPatternGetString
#undef FcPatternGetMatrix
#undef FcPatternGetCharSet
#undef FcPatternGetBool
#undef FcPatternGetLangSet
#undef FcPatternGetRange
#undef FcPatternVaBuild
#undef FcPatternBuild
#undef FcPatternFormat
#undef FcRangeCreateDouble
#undef FcRangeCreateInteger
#undef FcRangeDestroy
#undef FcRangeCopy
#undef FcRangeGetDouble
#undef FcWeightFromOpenType
#undef FcWeightToOpenType
#undef FcStrCopy
#undef FcStrCopyFilename
#undef FcStrPlus
#undef FcStrFree
#undef FcStrDowncase
#undef FcStrCmpIgnoreCase
#undef FcStrCmp
#undef FcStrStrIgnoreCase
#undef FcStrStr
#undef FcUtf8ToUcs4
#undef FcUtf8Len
#undef FcUcs4ToUtf8
#undef FcUtf16ToUcs4
#undef FcUtf16Len
#undef FcStrDirname
#undef FcStrBasename
#undef FcStrSetCreate
#undef FcStrSetMember
#undef FcStrSetEqual
#undef FcStrSetAdd
#undef FcStrSetAddFilename
#undef FcStrSetDel
#undef FcStrSetDestroy
#undef FcStrListCreate
#undef FcStrListFirst
#undef FcStrListNext
#undef FcStrListDone
#undef FcConfigParseAndLoad
#undef FcConfigParseAndLoadFromMemory
#include <dlfcn.h>
#include <stdio.h>
FcBlanks *(*FcBlanksCreate_dylibloader_wrapper_fontconfig)(void);
void (*FcBlanksDestroy_dylibloader_wrapper_fontconfig)(FcBlanks *);
FcBool (*FcBlanksAdd_dylibloader_wrapper_fontconfig)(FcBlanks *, FcChar32);
FcBool (*FcBlanksIsMember_dylibloader_wrapper_fontconfig)(FcBlanks *, FcChar32);
const FcChar8 *(*FcCacheDir_dylibloader_wrapper_fontconfig)(const FcCache *);
FcFontSet *(*FcCacheCopySet_dylibloader_wrapper_fontconfig)(const FcCache *);
const FcChar8 *(*FcCacheSubdir_dylibloader_wrapper_fontconfig)(const FcCache *, int);
int (*FcCacheNumSubdir_dylibloader_wrapper_fontconfig)(const FcCache *);
int (*FcCacheNumFont_dylibloader_wrapper_fontconfig)(const FcCache *);
FcBool (*FcDirCacheUnlink_dylibloader_wrapper_fontconfig)(const FcChar8 *, FcConfig *);
FcBool (*FcDirCacheValid_dylibloader_wrapper_fontconfig)(const FcChar8 *);
FcBool (*FcDirCacheClean_dylibloader_wrapper_fontconfig)(const FcChar8 *, FcBool);
void (*FcCacheCreateTagFile_dylibloader_wrapper_fontconfig)(const FcConfig *);
FcChar8 *(*FcConfigHome_dylibloader_wrapper_fontconfig)(void);
FcBool (*FcConfigEnableHome_dylibloader_wrapper_fontconfig)(FcBool);
FcChar8 *(*FcConfigFilename_dylibloader_wrapper_fontconfig)(const FcChar8 *);
FcConfig *(*FcConfigCreate_dylibloader_wrapper_fontconfig)(void);
FcConfig *(*FcConfigReference_dylibloader_wrapper_fontconfig)(FcConfig *);
void (*FcConfigDestroy_dylibloader_wrapper_fontconfig)(FcConfig *);
FcBool (*FcConfigSetCurrent_dylibloader_wrapper_fontconfig)(FcConfig *);
FcConfig *(*FcConfigGetCurrent_dylibloader_wrapper_fontconfig)(void);
FcBool (*FcConfigUptoDate_dylibloader_wrapper_fontconfig)(FcConfig *);
FcBool (*FcConfigBuildFonts_dylibloader_wrapper_fontconfig)(FcConfig *);
FcStrList *(*FcConfigGetFontDirs_dylibloader_wrapper_fontconfig)(FcConfig *);
FcStrList *(*FcConfigGetConfigDirs_dylibloader_wrapper_fontconfig)(FcConfig *);
FcStrList *(*FcConfigGetConfigFiles_dylibloader_wrapper_fontconfig)(FcConfig *);
FcChar8 *(*FcConfigGetCache_dylibloader_wrapper_fontconfig)(FcConfig *);
FcBlanks *(*FcConfigGetBlanks_dylibloader_wrapper_fontconfig)(FcConfig *);
FcStrList *(*FcConfigGetCacheDirs_dylibloader_wrapper_fontconfig)(const FcConfig *);
int (*FcConfigGetRescanInterval_dylibloader_wrapper_fontconfig)(FcConfig *);
FcBool (*FcConfigSetRescanInterval_dylibloader_wrapper_fontconfig)(FcConfig *, int);
FcFontSet *(*FcConfigGetFonts_dylibloader_wrapper_fontconfig)(FcConfig *, FcSetName);
FcBool (*FcConfigAppFontAddFile_dylibloader_wrapper_fontconfig)(FcConfig *, const FcChar8 *);
FcBool (*FcConfigAppFontAddDir_dylibloader_wrapper_fontconfig)(FcConfig *, const FcChar8 *);
void (*FcConfigAppFontClear_dylibloader_wrapper_fontconfig)(FcConfig *);
FcBool (*FcConfigSubstituteWithPat_dylibloader_wrapper_fontconfig)(FcConfig *, FcPattern *, FcPattern *, FcMatchKind);
FcBool (*FcConfigSubstitute_dylibloader_wrapper_fontconfig)(FcConfig *, FcPattern *, FcMatchKind);
const FcChar8 *(*FcConfigGetSysRoot_dylibloader_wrapper_fontconfig)(const FcConfig *);
void (*FcConfigSetSysRoot_dylibloader_wrapper_fontconfig)(FcConfig *, const FcChar8 *);
FcCharSet *(*FcCharSetCreate_dylibloader_wrapper_fontconfig)(void);
FcCharSet *(*FcCharSetNew_dylibloader_wrapper_fontconfig)(void);
void (*FcCharSetDestroy_dylibloader_wrapper_fontconfig)(FcCharSet *);
FcBool (*FcCharSetAddChar_dylibloader_wrapper_fontconfig)(FcCharSet *, FcChar32);
FcBool (*FcCharSetDelChar_dylibloader_wrapper_fontconfig)(FcCharSet *, FcChar32);
FcCharSet *(*FcCharSetCopy_dylibloader_wrapper_fontconfig)(FcCharSet *);
FcBool (*FcCharSetEqual_dylibloader_wrapper_fontconfig)(const FcCharSet *, const FcCharSet *);
FcCharSet *(*FcCharSetIntersect_dylibloader_wrapper_fontconfig)(const FcCharSet *, const FcCharSet *);
FcCharSet *(*FcCharSetUnion_dylibloader_wrapper_fontconfig)(const FcCharSet *, const FcCharSet *);
FcCharSet *(*FcCharSetSubtract_dylibloader_wrapper_fontconfig)(const FcCharSet *, const FcCharSet *);
FcBool (*FcCharSetMerge_dylibloader_wrapper_fontconfig)(FcCharSet *, const FcCharSet *, FcBool *);
FcBool (*FcCharSetHasChar_dylibloader_wrapper_fontconfig)(const FcCharSet *, FcChar32);
FcChar32 (*FcCharSetCount_dylibloader_wrapper_fontconfig)(const FcCharSet *);
FcChar32 (*FcCharSetIntersectCount_dylibloader_wrapper_fontconfig)(const FcCharSet *, const FcCharSet *);
FcChar32 (*FcCharSetSubtractCount_dylibloader_wrapper_fontconfig)(const FcCharSet *, const FcCharSet *);
FcBool (*FcCharSetIsSubset_dylibloader_wrapper_fontconfig)(const FcCharSet *, const FcCharSet *);
FcChar32 (*FcCharSetCoverage_dylibloader_wrapper_fontconfig)(const FcCharSet *, FcChar32, FcChar32 *);
void (*FcValuePrint_dylibloader_wrapper_fontconfig)(const FcValue);
void (*FcPatternPrint_dylibloader_wrapper_fontconfig)(const FcPattern *);
void (*FcFontSetPrint_dylibloader_wrapper_fontconfig)(const FcFontSet *);
FcStrSet *(*FcGetDefaultLangs_dylibloader_wrapper_fontconfig)(void);
void (*FcDefaultSubstitute_dylibloader_wrapper_fontconfig)(FcPattern *);
FcBool (*FcFileIsDir_dylibloader_wrapper_fontconfig)(const FcChar8 *);
FcBool (*FcFileScan_dylibloader_wrapper_fontconfig)(FcFontSet *, FcStrSet *, FcFileCache *, FcBlanks *, const FcChar8 *, FcBool);
FcBool (*FcDirScan_dylibloader_wrapper_fontconfig)(FcFontSet *, FcStrSet *, FcFileCache *, FcBlanks *, const FcChar8 *, FcBool);
FcBool (*FcDirSave_dylibloader_wrapper_fontconfig)(FcFontSet *, FcStrSet *, const FcChar8 *);
FcCache *(*FcDirCacheLoad_dylibloader_wrapper_fontconfig)(const FcChar8 *, FcConfig *, FcChar8 **);
FcCache *(*FcDirCacheRescan_dylibloader_wrapper_fontconfig)(const FcChar8 *, FcConfig *);
FcCache *(*FcDirCacheRead_dylibloader_wrapper_fontconfig)(const FcChar8 *, FcBool, FcConfig *);
FcCache *(*FcDirCacheLoadFile_dylibloader_wrapper_fontconfig)(const FcChar8 *, struct stat *);
void (*FcDirCacheUnload_dylibloader_wrapper_fontconfig)(FcCache *);
FcPattern *(*FcFreeTypeQuery_dylibloader_wrapper_fontconfig)(const FcChar8 *, int, FcBlanks *, int *);
FcFontSet *(*FcFontSetCreate_dylibloader_wrapper_fontconfig)(void);
void (*FcFontSetDestroy_dylibloader_wrapper_fontconfig)(FcFontSet *);
FcBool (*FcFontSetAdd_dylibloader_wrapper_fontconfig)(FcFontSet *, FcPattern *);
FcConfig *(*FcInitLoadConfig_dylibloader_wrapper_fontconfig)(void);
FcConfig *(*FcInitLoadConfigAndFonts_dylibloader_wrapper_fontconfig)(void);
FcBool (*FcInit_dylibloader_wrapper_fontconfig)(void);
void (*FcFini_dylibloader_wrapper_fontconfig)(void);
int (*FcGetVersion_dylibloader_wrapper_fontconfig)(void);
FcBool (*FcInitReinitialize_dylibloader_wrapper_fontconfig)(void);
FcBool (*FcInitBringUptoDate_dylibloader_wrapper_fontconfig)(void);
FcStrSet *(*FcGetLangs_dylibloader_wrapper_fontconfig)(void);
FcChar8 *(*FcLangNormalize_dylibloader_wrapper_fontconfig)(const FcChar8 *);
const FcCharSet *(*FcLangGetCharSet_dylibloader_wrapper_fontconfig)(const FcChar8 *);
FcLangSet *(*FcLangSetCreate_dylibloader_wrapper_fontconfig)(void);
void (*FcLangSetDestroy_dylibloader_wrapper_fontconfig)(FcLangSet *);
FcLangSet *(*FcLangSetCopy_dylibloader_wrapper_fontconfig)(const FcLangSet *);
FcBool (*FcLangSetAdd_dylibloader_wrapper_fontconfig)(FcLangSet *, const FcChar8 *);
FcBool (*FcLangSetDel_dylibloader_wrapper_fontconfig)(FcLangSet *, const FcChar8 *);
FcLangResult (*FcLangSetHasLang_dylibloader_wrapper_fontconfig)(const FcLangSet *, const FcChar8 *);
FcLangResult (*FcLangSetCompare_dylibloader_wrapper_fontconfig)(const FcLangSet *, const FcLangSet *);
FcBool (*FcLangSetContains_dylibloader_wrapper_fontconfig)(const FcLangSet *, const FcLangSet *);
FcBool (*FcLangSetEqual_dylibloader_wrapper_fontconfig)(const FcLangSet *, const FcLangSet *);
FcChar32 (*FcLangSetHash_dylibloader_wrapper_fontconfig)(const FcLangSet *);
FcStrSet *(*FcLangSetGetLangs_dylibloader_wrapper_fontconfig)(const FcLangSet *);
FcLangSet *(*FcLangSetUnion_dylibloader_wrapper_fontconfig)(const FcLangSet *, const FcLangSet *);
FcLangSet *(*FcLangSetSubtract_dylibloader_wrapper_fontconfig)(const FcLangSet *, const FcLangSet *);
FcObjectSet *(*FcObjectSetCreate_dylibloader_wrapper_fontconfig)(void);
FcBool (*FcObjectSetAdd_dylibloader_wrapper_fontconfig)(FcObjectSet *, const char *);
void (*FcObjectSetDestroy_dylibloader_wrapper_fontconfig)(FcObjectSet *);
FcObjectSet *(*FcObjectSetVaBuild_dylibloader_wrapper_fontconfig)(const char *, va_list);
FcObjectSet *(*FcObjectSetBuild_dylibloader_wrapper_fontconfig)(const char *, ...);
FcFontSet *(*FcFontSetList_dylibloader_wrapper_fontconfig)(FcConfig *, FcFontSet **, int, FcPattern *, FcObjectSet *);
FcFontSet *(*FcFontList_dylibloader_wrapper_fontconfig)(FcConfig *, FcPattern *, FcObjectSet *);
FcAtomic *(*FcAtomicCreate_dylibloader_wrapper_fontconfig)(const FcChar8 *);
FcBool (*FcAtomicLock_dylibloader_wrapper_fontconfig)(FcAtomic *);
FcChar8 *(*FcAtomicNewFile_dylibloader_wrapper_fontconfig)(FcAtomic *);
FcChar8 *(*FcAtomicOrigFile_dylibloader_wrapper_fontconfig)(FcAtomic *);
FcBool (*FcAtomicReplaceOrig_dylibloader_wrapper_fontconfig)(FcAtomic *);
void (*FcAtomicDeleteNew_dylibloader_wrapper_fontconfig)(FcAtomic *);
void (*FcAtomicUnlock_dylibloader_wrapper_fontconfig)(FcAtomic *);
void (*FcAtomicDestroy_dylibloader_wrapper_fontconfig)(FcAtomic *);
FcPattern *(*FcFontSetMatch_dylibloader_wrapper_fontconfig)(FcConfig *, FcFontSet **, int, FcPattern *, FcResult *);
FcPattern *(*FcFontMatch_dylibloader_wrapper_fontconfig)(FcConfig *, FcPattern *, FcResult *);
FcPattern *(*FcFontRenderPrepare_dylibloader_wrapper_fontconfig)(FcConfig *, FcPattern *, FcPattern *);
FcFontSet *(*FcFontSetSort_dylibloader_wrapper_fontconfig)(FcConfig *, FcFontSet **, int, FcPattern *, FcBool, FcCharSet **, FcResult *);
FcFontSet *(*FcFontSort_dylibloader_wrapper_fontconfig)(FcConfig *, FcPattern *, FcBool, FcCharSet **, FcResult *);
void (*FcFontSetSortDestroy_dylibloader_wrapper_fontconfig)(FcFontSet *);
FcMatrix *(*FcMatrixCopy_dylibloader_wrapper_fontconfig)(const FcMatrix *);
FcBool (*FcMatrixEqual_dylibloader_wrapper_fontconfig)(const FcMatrix *, const FcMatrix *);
void (*FcMatrixMultiply_dylibloader_wrapper_fontconfig)(FcMatrix *, const FcMatrix *, const FcMatrix *);
void (*FcMatrixRotate_dylibloader_wrapper_fontconfig)(FcMatrix *, double, double);
void (*FcMatrixScale_dylibloader_wrapper_fontconfig)(FcMatrix *, double, double);
void (*FcMatrixShear_dylibloader_wrapper_fontconfig)(FcMatrix *, double, double);
FcBool (*FcNameRegisterObjectTypes_dylibloader_wrapper_fontconfig)(const FcObjectType *, int);
FcBool (*FcNameUnregisterObjectTypes_dylibloader_wrapper_fontconfig)(const FcObjectType *, int);
const FcObjectType *(*FcNameGetObjectType_dylibloader_wrapper_fontconfig)(const char *);
FcBool (*FcNameRegisterConstants_dylibloader_wrapper_fontconfig)(const FcConstant *, int);
FcBool (*FcNameUnregisterConstants_dylibloader_wrapper_fontconfig)(const FcConstant *, int);
const FcConstant *(*FcNameGetConstant_dylibloader_wrapper_fontconfig)(const FcChar8 *);
FcBool (*FcNameConstant_dylibloader_wrapper_fontconfig)(const FcChar8 *, int *);
FcPattern *(*FcNameParse_dylibloader_wrapper_fontconfig)(const FcChar8 *);
FcChar8 *(*FcNameUnparse_dylibloader_wrapper_fontconfig)(FcPattern *);
FcPattern *(*FcPatternCreate_dylibloader_wrapper_fontconfig)(void);
FcPattern *(*FcPatternDuplicate_dylibloader_wrapper_fontconfig)(const FcPattern *);
void (*FcPatternReference_dylibloader_wrapper_fontconfig)(FcPattern *);
FcPattern *(*FcPatternFilter_dylibloader_wrapper_fontconfig)(FcPattern *, const FcObjectSet *);
void (*FcValueDestroy_dylibloader_wrapper_fontconfig)(FcValue);
FcBool (*FcValueEqual_dylibloader_wrapper_fontconfig)(FcValue, FcValue);
FcValue (*FcValueSave_dylibloader_wrapper_fontconfig)(FcValue);
void (*FcPatternDestroy_dylibloader_wrapper_fontconfig)(FcPattern *);
FcBool (*FcPatternEqual_dylibloader_wrapper_fontconfig)(const FcPattern *, const FcPattern *);
FcBool (*FcPatternEqualSubset_dylibloader_wrapper_fontconfig)(const FcPattern *, const FcPattern *, const FcObjectSet *);
FcChar32 (*FcPatternHash_dylibloader_wrapper_fontconfig)(const FcPattern *);
FcBool (*FcPatternAdd_dylibloader_wrapper_fontconfig)(FcPattern *, const char *, FcValue, FcBool);
FcBool (*FcPatternAddWeak_dylibloader_wrapper_fontconfig)(FcPattern *, const char *, FcValue, FcBool);
FcResult (*FcPatternGet_dylibloader_wrapper_fontconfig)(const FcPattern *, const char *, int, FcValue *);
FcResult (*FcPatternGetWithBinding_dylibloader_wrapper_fontconfig)(const FcPattern *, const char *, int, FcValue *, FcValueBinding *);
FcBool (*FcPatternDel_dylibloader_wrapper_fontconfig)(FcPattern *, const char *);
FcBool (*FcPatternRemove_dylibloader_wrapper_fontconfig)(FcPattern *, const char *, int);
FcBool (*FcPatternAddInteger_dylibloader_wrapper_fontconfig)(FcPattern *, const char *, int);
FcBool (*FcPatternAddDouble_dylibloader_wrapper_fontconfig)(FcPattern *, const char *, double);
FcBool (*FcPatternAddString_dylibloader_wrapper_fontconfig)(FcPattern *, const char *, const FcChar8 *);
FcBool (*FcPatternAddMatrix_dylibloader_wrapper_fontconfig)(FcPattern *, const char *, const FcMatrix *);
FcBool (*FcPatternAddCharSet_dylibloader_wrapper_fontconfig)(FcPattern *, const char *, const FcCharSet *);
FcBool (*FcPatternAddBool_dylibloader_wrapper_fontconfig)(FcPattern *, const char *, FcBool);
FcBool (*FcPatternAddLangSet_dylibloader_wrapper_fontconfig)(FcPattern *, const char *, const FcLangSet *);
FcBool (*FcPatternAddRange_dylibloader_wrapper_fontconfig)(FcPattern *, const char *, const FcRange *);
FcResult (*FcPatternGetInteger_dylibloader_wrapper_fontconfig)(const FcPattern *, const char *, int, int *);
FcResult (*FcPatternGetDouble_dylibloader_wrapper_fontconfig)(const FcPattern *, const char *, int, double *);
FcResult (*FcPatternGetString_dylibloader_wrapper_fontconfig)(const FcPattern *, const char *, int, FcChar8 **);
FcResult (*FcPatternGetMatrix_dylibloader_wrapper_fontconfig)(const FcPattern *, const char *, int, FcMatrix **);
FcResult (*FcPatternGetCharSet_dylibloader_wrapper_fontconfig)(const FcPattern *, const char *, int, FcCharSet **);
FcResult (*FcPatternGetBool_dylibloader_wrapper_fontconfig)(const FcPattern *, const char *, int, FcBool *);
FcResult (*FcPatternGetLangSet_dylibloader_wrapper_fontconfig)(const FcPattern *, const char *, int, FcLangSet **);
FcResult (*FcPatternGetRange_dylibloader_wrapper_fontconfig)(const FcPattern *, const char *, int, FcRange **);
FcPattern *(*FcPatternVaBuild_dylibloader_wrapper_fontconfig)(FcPattern *, va_list);
FcPattern *(*FcPatternBuild_dylibloader_wrapper_fontconfig)(FcPattern *, ...);
FcChar8 *(*FcPatternFormat_dylibloader_wrapper_fontconfig)(FcPattern *, const FcChar8 *);
FcRange *(*FcRangeCreateDouble_dylibloader_wrapper_fontconfig)(double, double);
FcRange *(*FcRangeCreateInteger_dylibloader_wrapper_fontconfig)(FcChar32, FcChar32);
void (*FcRangeDestroy_dylibloader_wrapper_fontconfig)(FcRange *);
FcRange *(*FcRangeCopy_dylibloader_wrapper_fontconfig)(const FcRange *);
FcBool (*FcRangeGetDouble_dylibloader_wrapper_fontconfig)(const FcRange *, double *, double *);
int (*FcWeightFromOpenType_dylibloader_wrapper_fontconfig)(int);
int (*FcWeightToOpenType_dylibloader_wrapper_fontconfig)(int);
FcChar8 *(*FcStrCopy_dylibloader_wrapper_fontconfig)(const FcChar8 *);
FcChar8 *(*FcStrCopyFilename_dylibloader_wrapper_fontconfig)(const FcChar8 *);
FcChar8 *(*FcStrPlus_dylibloader_wrapper_fontconfig)(const FcChar8 *, const FcChar8 *);
void (*FcStrFree_dylibloader_wrapper_fontconfig)(FcChar8 *);
FcChar8 *(*FcStrDowncase_dylibloader_wrapper_fontconfig)(const FcChar8 *);
int (*FcStrCmpIgnoreCase_dylibloader_wrapper_fontconfig)(const FcChar8 *, const FcChar8 *);
int (*FcStrCmp_dylibloader_wrapper_fontconfig)(const FcChar8 *, const FcChar8 *);
const FcChar8 *(*FcStrStrIgnoreCase_dylibloader_wrapper_fontconfig)(const FcChar8 *, const FcChar8 *);
const FcChar8 *(*FcStrStr_dylibloader_wrapper_fontconfig)(const FcChar8 *, const FcChar8 *);
int (*FcUtf8ToUcs4_dylibloader_wrapper_fontconfig)(const FcChar8 *, FcChar32 *, int);
FcBool (*FcUtf8Len_dylibloader_wrapper_fontconfig)(const FcChar8 *, int, int *, int *);
int (*FcUcs4ToUtf8_dylibloader_wrapper_fontconfig)(FcChar32, FcChar8 [6]);
int (*FcUtf16ToUcs4_dylibloader_wrapper_fontconfig)(const FcChar8 *, FcEndian, FcChar32 *, int);
FcBool (*FcUtf16Len_dylibloader_wrapper_fontconfig)(const FcChar8 *, FcEndian, int, int *, int *);
FcChar8 *(*FcStrDirname_dylibloader_wrapper_fontconfig)(const FcChar8 *);
FcChar8 *(*FcStrBasename_dylibloader_wrapper_fontconfig)(const FcChar8 *);
FcStrSet *(*FcStrSetCreate_dylibloader_wrapper_fontconfig)(void);
FcBool (*FcStrSetMember_dylibloader_wrapper_fontconfig)(FcStrSet *, const FcChar8 *);
FcBool (*FcStrSetEqual_dylibloader_wrapper_fontconfig)(FcStrSet *, FcStrSet *);
FcBool (*FcStrSetAdd_dylibloader_wrapper_fontconfig)(FcStrSet *, const FcChar8 *);
FcBool (*FcStrSetAddFilename_dylibloader_wrapper_fontconfig)(FcStrSet *, const FcChar8 *);
FcBool (*FcStrSetDel_dylibloader_wrapper_fontconfig)(FcStrSet *, const FcChar8 *);
void (*FcStrSetDestroy_dylibloader_wrapper_fontconfig)(FcStrSet *);
FcStrList *(*FcStrListCreate_dylibloader_wrapper_fontconfig)(FcStrSet *);
void (*FcStrListFirst_dylibloader_wrapper_fontconfig)(FcStrList *);
FcChar8 *(*FcStrListNext_dylibloader_wrapper_fontconfig)(FcStrList *);
void (*FcStrListDone_dylibloader_wrapper_fontconfig)(FcStrList *);
FcBool (*FcConfigParseAndLoad_dylibloader_wrapper_fontconfig)(FcConfig *, const FcChar8 *, FcBool);
FcBool (*FcConfigParseAndLoadFromMemory_dylibloader_wrapper_fontconfig)(FcConfig *, const FcChar8 *, FcBool);
int initialize_fontconfig(int verbose) {
  void *handle;
  char *error;
#if defined(__OpenBSD__) || defined(__NetBSD__)
  handle = dlopen("libfontconfig.so", RTLD_LAZY);
#else
  handle = dlopen("libfontconfig.so.1", RTLD_LAZY);
#endif
  if (!handle) {
    if (verbose) {
      fprintf(stderr, "%s\n", dlerror());
    }
    return(1);
  }
  dlerror();
// FcBlanksCreate
  {
    void *tmp_dlsym = dlsym(handle, "FcBlanksCreate");
    __builtin_memcpy(&FcBlanksCreate_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcBlanksDestroy
  {
    void *tmp_dlsym = dlsym(handle, "FcBlanksDestroy");
    __builtin_memcpy(&FcBlanksDestroy_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcBlanksAdd
  {
    void *tmp_dlsym = dlsym(handle, "FcBlanksAdd");
    __builtin_memcpy(&FcBlanksAdd_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcBlanksIsMember
  {
    void *tmp_dlsym = dlsym(handle, "FcBlanksIsMember");
    __builtin_memcpy(&FcBlanksIsMember_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcCacheDir
  {
    void *tmp_dlsym = dlsym(handle, "FcCacheDir");
    __builtin_memcpy(&FcCacheDir_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcCacheCopySet
  {
    void *tmp_dlsym = dlsym(handle, "FcCacheCopySet");
    __builtin_memcpy(&FcCacheCopySet_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcCacheSubdir
  {
    void *tmp_dlsym = dlsym(handle, "FcCacheSubdir");
    __builtin_memcpy(&FcCacheSubdir_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcCacheNumSubdir
  {
    void *tmp_dlsym = dlsym(handle, "FcCacheNumSubdir");
    __builtin_memcpy(&FcCacheNumSubdir_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcCacheNumFont
  {
    void *tmp_dlsym = dlsym(handle, "FcCacheNumFont");
    __builtin_memcpy(&FcCacheNumFont_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcDirCacheUnlink
  {
    void *tmp_dlsym = dlsym(handle, "FcDirCacheUnlink");
    __builtin_memcpy(&FcDirCacheUnlink_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcDirCacheValid
  {
    void *tmp_dlsym = dlsym(handle, "FcDirCacheValid");
    __builtin_memcpy(&FcDirCacheValid_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcDirCacheClean
  {
    void *tmp_dlsym = dlsym(handle, "FcDirCacheClean");
    __builtin_memcpy(&FcDirCacheClean_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcCacheCreateTagFile
  {
    void *tmp_dlsym = dlsym(handle, "FcCacheCreateTagFile");
    __builtin_memcpy(&FcCacheCreateTagFile_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcConfigHome
  {
    void *tmp_dlsym = dlsym(handle, "FcConfigHome");
    __builtin_memcpy(&FcConfigHome_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcConfigEnableHome
  {
    void *tmp_dlsym = dlsym(handle, "FcConfigEnableHome");
    __builtin_memcpy(&FcConfigEnableHome_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcConfigFilename
  {
    void *tmp_dlsym = dlsym(handle, "FcConfigFilename");
    __builtin_memcpy(&FcConfigFilename_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcConfigCreate
  {
    void *tmp_dlsym = dlsym(handle, "FcConfigCreate");
    __builtin_memcpy(&FcConfigCreate_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcConfigReference
  {
    void *tmp_dlsym = dlsym(handle, "FcConfigReference");
    __builtin_memcpy(&FcConfigReference_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcConfigDestroy
  {
    void *tmp_dlsym = dlsym(handle, "FcConfigDestroy");
    __builtin_memcpy(&FcConfigDestroy_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcConfigSetCurrent
  {
    void *tmp_dlsym = dlsym(handle, "FcConfigSetCurrent");
    __builtin_memcpy(&FcConfigSetCurrent_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcConfigGetCurrent
  {
    void *tmp_dlsym = dlsym(handle, "FcConfigGetCurrent");
    __builtin_memcpy(&FcConfigGetCurrent_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcConfigUptoDate
  {
    void *tmp_dlsym = dlsym(handle, "FcConfigUptoDate");
    __builtin_memcpy(&FcConfigUptoDate_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcConfigBuildFonts
  {
    void *tmp_dlsym = dlsym(handle, "FcConfigBuildFonts");
    __builtin_memcpy(&FcConfigBuildFonts_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcConfigGetFontDirs
  {
    void *tmp_dlsym = dlsym(handle, "FcConfigGetFontDirs");
    __builtin_memcpy(&FcConfigGetFontDirs_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcConfigGetConfigDirs
  {
    void *tmp_dlsym = dlsym(handle, "FcConfigGetConfigDirs");
    __builtin_memcpy(&FcConfigGetConfigDirs_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcConfigGetConfigFiles
  {
    void *tmp_dlsym = dlsym(handle, "FcConfigGetConfigFiles");
    __builtin_memcpy(&FcConfigGetConfigFiles_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcConfigGetCache
  {
    void *tmp_dlsym = dlsym(handle, "FcConfigGetCache");
    __builtin_memcpy(&FcConfigGetCache_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcConfigGetBlanks
  {
    void *tmp_dlsym = dlsym(handle, "FcConfigGetBlanks");
    __builtin_memcpy(&FcConfigGetBlanks_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcConfigGetCacheDirs
  {
    void *tmp_dlsym = dlsym(handle, "FcConfigGetCacheDirs");
    __builtin_memcpy(&FcConfigGetCacheDirs_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcConfigGetRescanInterval
  {
    void *tmp_dlsym = dlsym(handle, "FcConfigGetRescanInterval");
    __builtin_memcpy(&FcConfigGetRescanInterval_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcConfigSetRescanInterval
  {
    void *tmp_dlsym = dlsym(handle, "FcConfigSetRescanInterval");
    __builtin_memcpy(&FcConfigSetRescanInterval_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcConfigGetFonts
  {
    void *tmp_dlsym = dlsym(handle, "FcConfigGetFonts");
    __builtin_memcpy(&FcConfigGetFonts_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcConfigAppFontAddFile
  {
    void *tmp_dlsym = dlsym(handle, "FcConfigAppFontAddFile");
    __builtin_memcpy(&FcConfigAppFontAddFile_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcConfigAppFontAddDir
  {
    void *tmp_dlsym = dlsym(handle, "FcConfigAppFontAddDir");
    __builtin_memcpy(&FcConfigAppFontAddDir_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcConfigAppFontClear
  {
    void *tmp_dlsym = dlsym(handle, "FcConfigAppFontClear");
    __builtin_memcpy(&FcConfigAppFontClear_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcConfigSubstituteWithPat
  {
    void *tmp_dlsym = dlsym(handle, "FcConfigSubstituteWithPat");
    __builtin_memcpy(&FcConfigSubstituteWithPat_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcConfigSubstitute
  {
    void *tmp_dlsym = dlsym(handle, "FcConfigSubstitute");
    __builtin_memcpy(&FcConfigSubstitute_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcConfigGetSysRoot
  {
    void *tmp_dlsym = dlsym(handle, "FcConfigGetSysRoot");
    __builtin_memcpy(&FcConfigGetSysRoot_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcConfigSetSysRoot
  {
    void *tmp_dlsym = dlsym(handle, "FcConfigSetSysRoot");
    __builtin_memcpy(&FcConfigSetSysRoot_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcCharSetCreate
  {
    void *tmp_dlsym = dlsym(handle, "FcCharSetCreate");
    __builtin_memcpy(&FcCharSetCreate_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcCharSetNew
  {
    void *tmp_dlsym = dlsym(handle, "FcCharSetNew");
    __builtin_memcpy(&FcCharSetNew_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcCharSetDestroy
  {
    void *tmp_dlsym = dlsym(handle, "FcCharSetDestroy");
    __builtin_memcpy(&FcCharSetDestroy_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcCharSetAddChar
  {
    void *tmp_dlsym = dlsym(handle, "FcCharSetAddChar");
    __builtin_memcpy(&FcCharSetAddChar_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcCharSetDelChar
  {
    void *tmp_dlsym = dlsym(handle, "FcCharSetDelChar");
    __builtin_memcpy(&FcCharSetDelChar_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcCharSetCopy
  {
    void *tmp_dlsym = dlsym(handle, "FcCharSetCopy");
    __builtin_memcpy(&FcCharSetCopy_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcCharSetEqual
  {
    void *tmp_dlsym = dlsym(handle, "FcCharSetEqual");
    __builtin_memcpy(&FcCharSetEqual_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcCharSetIntersect
  {
    void *tmp_dlsym = dlsym(handle, "FcCharSetIntersect");
    __builtin_memcpy(&FcCharSetIntersect_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcCharSetUnion
  {
    void *tmp_dlsym = dlsym(handle, "FcCharSetUnion");
    __builtin_memcpy(&FcCharSetUnion_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcCharSetSubtract
  {
    void *tmp_dlsym = dlsym(handle, "FcCharSetSubtract");
    __builtin_memcpy(&FcCharSetSubtract_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcCharSetMerge
  {
    void *tmp_dlsym = dlsym(handle, "FcCharSetMerge");
    __builtin_memcpy(&FcCharSetMerge_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcCharSetHasChar
  {
    void *tmp_dlsym = dlsym(handle, "FcCharSetHasChar");
    __builtin_memcpy(&FcCharSetHasChar_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcCharSetCount
  {
    void *tmp_dlsym = dlsym(handle, "FcCharSetCount");
    __builtin_memcpy(&FcCharSetCount_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcCharSetIntersectCount
  {
    void *tmp_dlsym = dlsym(handle, "FcCharSetIntersectCount");
    __builtin_memcpy(&FcCharSetIntersectCount_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcCharSetSubtractCount
  {
    void *tmp_dlsym = dlsym(handle, "FcCharSetSubtractCount");
    __builtin_memcpy(&FcCharSetSubtractCount_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcCharSetIsSubset
  {
    void *tmp_dlsym = dlsym(handle, "FcCharSetIsSubset");
    __builtin_memcpy(&FcCharSetIsSubset_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcCharSetCoverage
  {
    void *tmp_dlsym = dlsym(handle, "FcCharSetCoverage");
    __builtin_memcpy(&FcCharSetCoverage_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcValuePrint
  {
    void *tmp_dlsym = dlsym(handle, "FcValuePrint");
    __builtin_memcpy(&FcValuePrint_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcPatternPrint
  {
    void *tmp_dlsym = dlsym(handle, "FcPatternPrint");
    __builtin_memcpy(&FcPatternPrint_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcFontSetPrint
  {
    void *tmp_dlsym = dlsym(handle, "FcFontSetPrint");
    __builtin_memcpy(&FcFontSetPrint_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcGetDefaultLangs
  {
    void *tmp_dlsym = dlsym(handle, "FcGetDefaultLangs");
    __builtin_memcpy(&FcGetDefaultLangs_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcDefaultSubstitute
  {
    void *tmp_dlsym = dlsym(handle, "FcDefaultSubstitute");
    __builtin_memcpy(&FcDefaultSubstitute_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcFileIsDir
  {
    void *tmp_dlsym = dlsym(handle, "FcFileIsDir");
    __builtin_memcpy(&FcFileIsDir_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcFileScan
  {
    void *tmp_dlsym = dlsym(handle, "FcFileScan");
    __builtin_memcpy(&FcFileScan_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcDirScan
  {
    void *tmp_dlsym = dlsym(handle, "FcDirScan");
    __builtin_memcpy(&FcDirScan_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcDirSave
  {
    void *tmp_dlsym = dlsym(handle, "FcDirSave");
    __builtin_memcpy(&FcDirSave_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcDirCacheLoad
  {
    void *tmp_dlsym = dlsym(handle, "FcDirCacheLoad");
    __builtin_memcpy(&FcDirCacheLoad_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcDirCacheRescan
  {
    void *tmp_dlsym = dlsym(handle, "FcDirCacheRescan");
    __builtin_memcpy(&FcDirCacheRescan_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcDirCacheRead
  {
    void *tmp_dlsym = dlsym(handle, "FcDirCacheRead");
    __builtin_memcpy(&FcDirCacheRead_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcDirCacheLoadFile
  {
    void *tmp_dlsym = dlsym(handle, "FcDirCacheLoadFile");
    __builtin_memcpy(&FcDirCacheLoadFile_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcDirCacheUnload
  {
    void *tmp_dlsym = dlsym(handle, "FcDirCacheUnload");
    __builtin_memcpy(&FcDirCacheUnload_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcFreeTypeQuery
  {
    void *tmp_dlsym = dlsym(handle, "FcFreeTypeQuery");
    __builtin_memcpy(&FcFreeTypeQuery_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcFontSetCreate
  {
    void *tmp_dlsym = dlsym(handle, "FcFontSetCreate");
    __builtin_memcpy(&FcFontSetCreate_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcFontSetDestroy
  {
    void *tmp_dlsym = dlsym(handle, "FcFontSetDestroy");
    __builtin_memcpy(&FcFontSetDestroy_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcFontSetAdd
  {
    void *tmp_dlsym = dlsym(handle, "FcFontSetAdd");
    __builtin_memcpy(&FcFontSetAdd_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcInitLoadConfig
  {
    void *tmp_dlsym = dlsym(handle, "FcInitLoadConfig");
    __builtin_memcpy(&FcInitLoadConfig_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcInitLoadConfigAndFonts
  {
    void *tmp_dlsym = dlsym(handle, "FcInitLoadConfigAndFonts");
    __builtin_memcpy(&FcInitLoadConfigAndFonts_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcInit
  {
    void *tmp_dlsym = dlsym(handle, "FcInit");
    __builtin_memcpy(&FcInit_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcFini
  {
    void *tmp_dlsym = dlsym(handle, "FcFini");
    __builtin_memcpy(&FcFini_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcGetVersion
  {
    void *tmp_dlsym = dlsym(handle, "FcGetVersion");
    __builtin_memcpy(&FcGetVersion_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcInitReinitialize
  {
    void *tmp_dlsym = dlsym(handle, "FcInitReinitialize");
    __builtin_memcpy(&FcInitReinitialize_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcInitBringUptoDate
  {
    void *tmp_dlsym = dlsym(handle, "FcInitBringUptoDate");
    __builtin_memcpy(&FcInitBringUptoDate_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcGetLangs
  {
    void *tmp_dlsym = dlsym(handle, "FcGetLangs");
    __builtin_memcpy(&FcGetLangs_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcLangNormalize
  {
    void *tmp_dlsym = dlsym(handle, "FcLangNormalize");
    __builtin_memcpy(&FcLangNormalize_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcLangGetCharSet
  {
    void *tmp_dlsym = dlsym(handle, "FcLangGetCharSet");
    __builtin_memcpy(&FcLangGetCharSet_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcLangSetCreate
  {
    void *tmp_dlsym = dlsym(handle, "FcLangSetCreate");
    __builtin_memcpy(&FcLangSetCreate_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcLangSetDestroy
  {
    void *tmp_dlsym = dlsym(handle, "FcLangSetDestroy");
    __builtin_memcpy(&FcLangSetDestroy_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcLangSetCopy
  {
    void *tmp_dlsym = dlsym(handle, "FcLangSetCopy");
    __builtin_memcpy(&FcLangSetCopy_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcLangSetAdd
  {
    void *tmp_dlsym = dlsym(handle, "FcLangSetAdd");
    __builtin_memcpy(&FcLangSetAdd_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcLangSetDel
  {
    void *tmp_dlsym = dlsym(handle, "FcLangSetDel");
    __builtin_memcpy(&FcLangSetDel_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcLangSetHasLang
  {
    void *tmp_dlsym = dlsym(handle, "FcLangSetHasLang");
    __builtin_memcpy(&FcLangSetHasLang_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcLangSetCompare
  {
    void *tmp_dlsym = dlsym(handle, "FcLangSetCompare");
    __builtin_memcpy(&FcLangSetCompare_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcLangSetContains
  {
    void *tmp_dlsym = dlsym(handle, "FcLangSetContains");
    __builtin_memcpy(&FcLangSetContains_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcLangSetEqual
  {
    void *tmp_dlsym = dlsym(handle, "FcLangSetEqual");
    __builtin_memcpy(&FcLangSetEqual_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcLangSetHash
  {
    void *tmp_dlsym = dlsym(handle, "FcLangSetHash");
    __builtin_memcpy(&FcLangSetHash_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcLangSetGetLangs
  {
    void *tmp_dlsym = dlsym(handle, "FcLangSetGetLangs");
    __builtin_memcpy(&FcLangSetGetLangs_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcLangSetUnion
  {
    void *tmp_dlsym = dlsym(handle, "FcLangSetUnion");
    __builtin_memcpy(&FcLangSetUnion_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcLangSetSubtract
  {
    void *tmp_dlsym = dlsym(handle, "FcLangSetSubtract");
    __builtin_memcpy(&FcLangSetSubtract_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcObjectSetCreate
  {
    void *tmp_dlsym = dlsym(handle, "FcObjectSetCreate");
    __builtin_memcpy(&FcObjectSetCreate_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcObjectSetAdd
  {
    void *tmp_dlsym = dlsym(handle, "FcObjectSetAdd");
    __builtin_memcpy(&FcObjectSetAdd_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcObjectSetDestroy
  {
    void *tmp_dlsym = dlsym(handle, "FcObjectSetDestroy");
    __builtin_memcpy(&FcObjectSetDestroy_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcObjectSetVaBuild
  {
    void *tmp_dlsym = dlsym(handle, "FcObjectSetVaBuild");
    __builtin_memcpy(&FcObjectSetVaBuild_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcObjectSetBuild
  {
    void *tmp_dlsym = dlsym(handle, "FcObjectSetBuild");
    __builtin_memcpy(&FcObjectSetBuild_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcFontSetList
  {
    void *tmp_dlsym = dlsym(handle, "FcFontSetList");
    __builtin_memcpy(&FcFontSetList_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcFontList
  {
    void *tmp_dlsym = dlsym(handle, "FcFontList");
    __builtin_memcpy(&FcFontList_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcAtomicCreate
  {
    void *tmp_dlsym = dlsym(handle, "FcAtomicCreate");
    __builtin_memcpy(&FcAtomicCreate_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcAtomicLock
  {
    void *tmp_dlsym = dlsym(handle, "FcAtomicLock");
    __builtin_memcpy(&FcAtomicLock_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcAtomicNewFile
  {
    void *tmp_dlsym = dlsym(handle, "FcAtomicNewFile");
    __builtin_memcpy(&FcAtomicNewFile_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcAtomicOrigFile
  {
    void *tmp_dlsym = dlsym(handle, "FcAtomicOrigFile");
    __builtin_memcpy(&FcAtomicOrigFile_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcAtomicReplaceOrig
  {
    void *tmp_dlsym = dlsym(handle, "FcAtomicReplaceOrig");
    __builtin_memcpy(&FcAtomicReplaceOrig_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcAtomicDeleteNew
  {
    void *tmp_dlsym = dlsym(handle, "FcAtomicDeleteNew");
    __builtin_memcpy(&FcAtomicDeleteNew_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcAtomicUnlock
  {
    void *tmp_dlsym = dlsym(handle, "FcAtomicUnlock");
    __builtin_memcpy(&FcAtomicUnlock_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcAtomicDestroy
  {
    void *tmp_dlsym = dlsym(handle, "FcAtomicDestroy");
    __builtin_memcpy(&FcAtomicDestroy_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcFontSetMatch
  {
    void *tmp_dlsym = dlsym(handle, "FcFontSetMatch");
    __builtin_memcpy(&FcFontSetMatch_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcFontMatch
  {
    void *tmp_dlsym = dlsym(handle, "FcFontMatch");
    __builtin_memcpy(&FcFontMatch_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcFontRenderPrepare
  {
    void *tmp_dlsym = dlsym(handle, "FcFontRenderPrepare");
    __builtin_memcpy(&FcFontRenderPrepare_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcFontSetSort
  {
    void *tmp_dlsym = dlsym(handle, "FcFontSetSort");
    __builtin_memcpy(&FcFontSetSort_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcFontSort
  {
    void *tmp_dlsym = dlsym(handle, "FcFontSort");
    __builtin_memcpy(&FcFontSort_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcFontSetSortDestroy
  {
    void *tmp_dlsym = dlsym(handle, "FcFontSetSortDestroy");
    __builtin_memcpy(&FcFontSetSortDestroy_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcMatrixCopy
  {
    void *tmp_dlsym = dlsym(handle, "FcMatrixCopy");
    __builtin_memcpy(&FcMatrixCopy_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcMatrixEqual
  {
    void *tmp_dlsym = dlsym(handle, "FcMatrixEqual");
    __builtin_memcpy(&FcMatrixEqual_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcMatrixMultiply
  {
    void *tmp_dlsym = dlsym(handle, "FcMatrixMultiply");
    __builtin_memcpy(&FcMatrixMultiply_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcMatrixRotate
  {
    void *tmp_dlsym = dlsym(handle, "FcMatrixRotate");
    __builtin_memcpy(&FcMatrixRotate_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcMatrixScale
  {
    void *tmp_dlsym = dlsym(handle, "FcMatrixScale");
    __builtin_memcpy(&FcMatrixScale_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcMatrixShear
  {
    void *tmp_dlsym = dlsym(handle, "FcMatrixShear");
    __builtin_memcpy(&FcMatrixShear_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcNameRegisterObjectTypes
  {
    void *tmp_dlsym = dlsym(handle, "FcNameRegisterObjectTypes");
    __builtin_memcpy(&FcNameRegisterObjectTypes_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcNameUnregisterObjectTypes
  {
    void *tmp_dlsym = dlsym(handle, "FcNameUnregisterObjectTypes");
    __builtin_memcpy(&FcNameUnregisterObjectTypes_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcNameGetObjectType
  {
    void *tmp_dlsym = dlsym(handle, "FcNameGetObjectType");
    __builtin_memcpy(&FcNameGetObjectType_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcNameRegisterConstants
  {
    void *tmp_dlsym = dlsym(handle, "FcNameRegisterConstants");
    __builtin_memcpy(&FcNameRegisterConstants_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcNameUnregisterConstants
  {
    void *tmp_dlsym = dlsym(handle, "FcNameUnregisterConstants");
    __builtin_memcpy(&FcNameUnregisterConstants_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcNameGetConstant
  {
    void *tmp_dlsym = dlsym(handle, "FcNameGetConstant");
    __builtin_memcpy(&FcNameGetConstant_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcNameConstant
  {
    void *tmp_dlsym = dlsym(handle, "FcNameConstant");
    __builtin_memcpy(&FcNameConstant_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcNameParse
  {
    void *tmp_dlsym = dlsym(handle, "FcNameParse");
    __builtin_memcpy(&FcNameParse_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcNameUnparse
  {
    void *tmp_dlsym = dlsym(handle, "FcNameUnparse");
    __builtin_memcpy(&FcNameUnparse_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcPatternCreate
  {
    void *tmp_dlsym = dlsym(handle, "FcPatternCreate");
    __builtin_memcpy(&FcPatternCreate_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcPatternDuplicate
  {
    void *tmp_dlsym = dlsym(handle, "FcPatternDuplicate");
    __builtin_memcpy(&FcPatternDuplicate_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcPatternReference
  {
    void *tmp_dlsym = dlsym(handle, "FcPatternReference");
    __builtin_memcpy(&FcPatternReference_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcPatternFilter
  {
    void *tmp_dlsym = dlsym(handle, "FcPatternFilter");
    __builtin_memcpy(&FcPatternFilter_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcValueDestroy
  {
    void *tmp_dlsym = dlsym(handle, "FcValueDestroy");
    __builtin_memcpy(&FcValueDestroy_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcValueEqual
  {
    void *tmp_dlsym = dlsym(handle, "FcValueEqual");
    __builtin_memcpy(&FcValueEqual_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcValueSave
  {
    void *tmp_dlsym = dlsym(handle, "FcValueSave");
    __builtin_memcpy(&FcValueSave_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcPatternDestroy
  {
    void *tmp_dlsym = dlsym(handle, "FcPatternDestroy");
    __builtin_memcpy(&FcPatternDestroy_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcPatternEqual
  {
    void *tmp_dlsym = dlsym(handle, "FcPatternEqual");
    __builtin_memcpy(&FcPatternEqual_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcPatternEqualSubset
  {
    void *tmp_dlsym = dlsym(handle, "FcPatternEqualSubset");
    __builtin_memcpy(&FcPatternEqualSubset_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcPatternHash
  {
    void *tmp_dlsym = dlsym(handle, "FcPatternHash");
    __builtin_memcpy(&FcPatternHash_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcPatternAdd
  {
    void *tmp_dlsym = dlsym(handle, "FcPatternAdd");
    __builtin_memcpy(&FcPatternAdd_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcPatternAddWeak
  {
    void *tmp_dlsym = dlsym(handle, "FcPatternAddWeak");
    __builtin_memcpy(&FcPatternAddWeak_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcPatternGet
  {
    void *tmp_dlsym = dlsym(handle, "FcPatternGet");
    __builtin_memcpy(&FcPatternGet_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcPatternGetWithBinding
  {
    void *tmp_dlsym = dlsym(handle, "FcPatternGetWithBinding");
    __builtin_memcpy(&FcPatternGetWithBinding_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcPatternDel
  {
    void *tmp_dlsym = dlsym(handle, "FcPatternDel");
    __builtin_memcpy(&FcPatternDel_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcPatternRemove
  {
    void *tmp_dlsym = dlsym(handle, "FcPatternRemove");
    __builtin_memcpy(&FcPatternRemove_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcPatternAddInteger
  {
    void *tmp_dlsym = dlsym(handle, "FcPatternAddInteger");
    __builtin_memcpy(&FcPatternAddInteger_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcPatternAddDouble
  {
    void *tmp_dlsym = dlsym(handle, "FcPatternAddDouble");
    __builtin_memcpy(&FcPatternAddDouble_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcPatternAddString
  {
    void *tmp_dlsym = dlsym(handle, "FcPatternAddString");
    __builtin_memcpy(&FcPatternAddString_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcPatternAddMatrix
  {
    void *tmp_dlsym = dlsym(handle, "FcPatternAddMatrix");
    __builtin_memcpy(&FcPatternAddMatrix_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcPatternAddCharSet
  {
    void *tmp_dlsym = dlsym(handle, "FcPatternAddCharSet");
    __builtin_memcpy(&FcPatternAddCharSet_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcPatternAddBool
  {
    void *tmp_dlsym = dlsym(handle, "FcPatternAddBool");
    __builtin_memcpy(&FcPatternAddBool_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcPatternAddLangSet
  {
    void *tmp_dlsym = dlsym(handle, "FcPatternAddLangSet");
    __builtin_memcpy(&FcPatternAddLangSet_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcPatternAddRange
  {
    void *tmp_dlsym = dlsym(handle, "FcPatternAddRange");
    __builtin_memcpy(&FcPatternAddRange_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcPatternGetInteger
  {
    void *tmp_dlsym = dlsym(handle, "FcPatternGetInteger");
    __builtin_memcpy(&FcPatternGetInteger_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcPatternGetDouble
  {
    void *tmp_dlsym = dlsym(handle, "FcPatternGetDouble");
    __builtin_memcpy(&FcPatternGetDouble_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcPatternGetString
  {
    void *tmp_dlsym = dlsym(handle, "FcPatternGetString");
    __builtin_memcpy(&FcPatternGetString_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcPatternGetMatrix
  {
    void *tmp_dlsym = dlsym(handle, "FcPatternGetMatrix");
    __builtin_memcpy(&FcPatternGetMatrix_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcPatternGetCharSet
  {
    void *tmp_dlsym = dlsym(handle, "FcPatternGetCharSet");
    __builtin_memcpy(&FcPatternGetCharSet_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcPatternGetBool
  {
    void *tmp_dlsym = dlsym(handle, "FcPatternGetBool");
    __builtin_memcpy(&FcPatternGetBool_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcPatternGetLangSet
  {
    void *tmp_dlsym = dlsym(handle, "FcPatternGetLangSet");
    __builtin_memcpy(&FcPatternGetLangSet_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcPatternGetRange
  {
    void *tmp_dlsym = dlsym(handle, "FcPatternGetRange");
    __builtin_memcpy(&FcPatternGetRange_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcPatternVaBuild
  {
    void *tmp_dlsym = dlsym(handle, "FcPatternVaBuild");
    __builtin_memcpy(&FcPatternVaBuild_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcPatternBuild
  {
    void *tmp_dlsym = dlsym(handle, "FcPatternBuild");
    __builtin_memcpy(&FcPatternBuild_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcPatternFormat
  {
    void *tmp_dlsym = dlsym(handle, "FcPatternFormat");
    __builtin_memcpy(&FcPatternFormat_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcRangeCreateDouble
  {
    void *tmp_dlsym = dlsym(handle, "FcRangeCreateDouble");
    __builtin_memcpy(&FcRangeCreateDouble_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcRangeCreateInteger
  {
    void *tmp_dlsym = dlsym(handle, "FcRangeCreateInteger");
    __builtin_memcpy(&FcRangeCreateInteger_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcRangeDestroy
  {
    void *tmp_dlsym = dlsym(handle, "FcRangeDestroy");
    __builtin_memcpy(&FcRangeDestroy_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcRangeCopy
  {
    void *tmp_dlsym = dlsym(handle, "FcRangeCopy");
    __builtin_memcpy(&FcRangeCopy_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcRangeGetDouble
  {
    void *tmp_dlsym = dlsym(handle, "FcRangeGetDouble");
    __builtin_memcpy(&FcRangeGetDouble_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcWeightFromOpenType
  {
    void *tmp_dlsym = dlsym(handle, "FcWeightFromOpenType");
    __builtin_memcpy(&FcWeightFromOpenType_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcWeightToOpenType
  {
    void *tmp_dlsym = dlsym(handle, "FcWeightToOpenType");
    __builtin_memcpy(&FcWeightToOpenType_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcStrCopy
  {
    void *tmp_dlsym = dlsym(handle, "FcStrCopy");
    __builtin_memcpy(&FcStrCopy_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcStrCopyFilename
  {
    void *tmp_dlsym = dlsym(handle, "FcStrCopyFilename");
    __builtin_memcpy(&FcStrCopyFilename_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcStrPlus
  {
    void *tmp_dlsym = dlsym(handle, "FcStrPlus");
    __builtin_memcpy(&FcStrPlus_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcStrFree
  {
    void *tmp_dlsym = dlsym(handle, "FcStrFree");
    __builtin_memcpy(&FcStrFree_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcStrDowncase
  {
    void *tmp_dlsym = dlsym(handle, "FcStrDowncase");
    __builtin_memcpy(&FcStrDowncase_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcStrCmpIgnoreCase
  {
    void *tmp_dlsym = dlsym(handle, "FcStrCmpIgnoreCase");
    __builtin_memcpy(&FcStrCmpIgnoreCase_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcStrCmp
  {
    void *tmp_dlsym = dlsym(handle, "FcStrCmp");
    __builtin_memcpy(&FcStrCmp_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcStrStrIgnoreCase
  {
    void *tmp_dlsym = dlsym(handle, "FcStrStrIgnoreCase");
    __builtin_memcpy(&FcStrStrIgnoreCase_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcStrStr
  {
    void *tmp_dlsym = dlsym(handle, "FcStrStr");
    __builtin_memcpy(&FcStrStr_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcUtf8ToUcs4
  {
    void *tmp_dlsym = dlsym(handle, "FcUtf8ToUcs4");
    __builtin_memcpy(&FcUtf8ToUcs4_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcUtf8Len
  {
    void *tmp_dlsym = dlsym(handle, "FcUtf8Len");
    __builtin_memcpy(&FcUtf8Len_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcUcs4ToUtf8
  {
    void *tmp_dlsym = dlsym(handle, "FcUcs4ToUtf8");
    __builtin_memcpy(&FcUcs4ToUtf8_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcUtf16ToUcs4
  {
    void *tmp_dlsym = dlsym(handle, "FcUtf16ToUcs4");
    __builtin_memcpy(&FcUtf16ToUcs4_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcUtf16Len
  {
    void *tmp_dlsym = dlsym(handle, "FcUtf16Len");
    __builtin_memcpy(&FcUtf16Len_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcStrDirname
  {
    void *tmp_dlsym = dlsym(handle, "FcStrDirname");
    __builtin_memcpy(&FcStrDirname_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcStrBasename
  {
    void *tmp_dlsym = dlsym(handle, "FcStrBasename");
    __builtin_memcpy(&FcStrBasename_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcStrSetCreate
  {
    void *tmp_dlsym = dlsym(handle, "FcStrSetCreate");
    __builtin_memcpy(&FcStrSetCreate_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcStrSetMember
  {
    void *tmp_dlsym = dlsym(handle, "FcStrSetMember");
    __builtin_memcpy(&FcStrSetMember_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcStrSetEqual
  {
    void *tmp_dlsym = dlsym(handle, "FcStrSetEqual");
    __builtin_memcpy(&FcStrSetEqual_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcStrSetAdd
  {
    void *tmp_dlsym = dlsym(handle, "FcStrSetAdd");
    __builtin_memcpy(&FcStrSetAdd_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcStrSetAddFilename
  {
    void *tmp_dlsym = dlsym(handle, "FcStrSetAddFilename");
    __builtin_memcpy(&FcStrSetAddFilename_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcStrSetDel
  {
    void *tmp_dlsym = dlsym(handle, "FcStrSetDel");
    __builtin_memcpy(&FcStrSetDel_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcStrSetDestroy
  {
    void *tmp_dlsym = dlsym(handle, "FcStrSetDestroy");
    __builtin_memcpy(&FcStrSetDestroy_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcStrListCreate
  {
    void *tmp_dlsym = dlsym(handle, "FcStrListCreate");
    __builtin_memcpy(&FcStrListCreate_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcStrListFirst
  {
    void *tmp_dlsym = dlsym(handle, "FcStrListFirst");
    __builtin_memcpy(&FcStrListFirst_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcStrListNext
  {
    void *tmp_dlsym = dlsym(handle, "FcStrListNext");
    __builtin_memcpy(&FcStrListNext_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcStrListDone
  {
    void *tmp_dlsym = dlsym(handle, "FcStrListDone");
    __builtin_memcpy(&FcStrListDone_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcConfigParseAndLoad
  {
    void *tmp_dlsym = dlsym(handle, "FcConfigParseAndLoad");
    __builtin_memcpy(&FcConfigParseAndLoad_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// FcConfigParseAndLoadFromMemory
  {
    void *tmp_dlsym = dlsym(handle, "FcConfigParseAndLoadFromMemory");
    __builtin_memcpy(&FcConfigParseAndLoadFromMemory_dylibloader_wrapper_fontconfig, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
return 0;
}
