// This file is generated. Do not edit!
// see https://github.com/hpvb/dynload-wrapper for details
// generated by generate-wrapper.py 0.7 on 2026-03-13 16:30:35
// flags: generate-wrapper.py --include /home/build/github/godot/thirdparty/linuxbsd_headers/speechd/libspeechd.h --sys-include thirdparty/linuxbsd_headers/speechd/libspeechd.h --soname libspeechd.so.2 --init-name speechd --omit-prefix spd_get_client_list --output-header /home/build/github/godot/platform/linuxbsd/speechd-so_wrap.h --output-implementation /home/build/github/godot/platform/linuxbsd/speechd-so_wrap.c
//
#include <stdint.h>

#define SPDConnectionAddress__free SPDConnectionAddress__free_dylibloader_orig_speechd
#define spd_get_default_address spd_get_default_address_dylibloader_orig_speechd
#define spd_open spd_open_dylibloader_orig_speechd
#define spd_open2 spd_open2_dylibloader_orig_speechd
#define spd_close spd_close_dylibloader_orig_speechd
#define spd_say spd_say_dylibloader_orig_speechd
#define spd_sayf spd_sayf_dylibloader_orig_speechd
#define spd_stop spd_stop_dylibloader_orig_speechd
#define spd_stop_all spd_stop_all_dylibloader_orig_speechd
#define spd_stop_uid spd_stop_uid_dylibloader_orig_speechd
#define spd_cancel spd_cancel_dylibloader_orig_speechd
#define spd_cancel_all spd_cancel_all_dylibloader_orig_speechd
#define spd_cancel_uid spd_cancel_uid_dylibloader_orig_speechd
#define spd_pause spd_pause_dylibloader_orig_speechd
#define spd_pause_all spd_pause_all_dylibloader_orig_speechd
#define spd_pause_uid spd_pause_uid_dylibloader_orig_speechd
#define spd_resume spd_resume_dylibloader_orig_speechd
#define spd_resume_all spd_resume_all_dylibloader_orig_speechd
#define spd_resume_uid spd_resume_uid_dylibloader_orig_speechd
#define spd_key spd_key_dylibloader_orig_speechd
#define spd_char spd_char_dylibloader_orig_speechd
#define spd_wchar spd_wchar_dylibloader_orig_speechd
#define spd_sound_icon spd_sound_icon_dylibloader_orig_speechd
#define spd_set_voice_type spd_set_voice_type_dylibloader_orig_speechd
#define spd_set_voice_type_all spd_set_voice_type_all_dylibloader_orig_speechd
#define spd_set_voice_type_uid spd_set_voice_type_uid_dylibloader_orig_speechd
#define spd_get_voice_type spd_get_voice_type_dylibloader_orig_speechd
#define spd_set_synthesis_voice spd_set_synthesis_voice_dylibloader_orig_speechd
#define spd_set_synthesis_voice_all spd_set_synthesis_voice_all_dylibloader_orig_speechd
#define spd_set_synthesis_voice_uid spd_set_synthesis_voice_uid_dylibloader_orig_speechd
#define spd_set_data_mode spd_set_data_mode_dylibloader_orig_speechd
#define spd_set_notification_on spd_set_notification_on_dylibloader_orig_speechd
#define spd_set_notification_off spd_set_notification_off_dylibloader_orig_speechd
#define spd_set_notification spd_set_notification_dylibloader_orig_speechd
#define spd_set_voice_rate spd_set_voice_rate_dylibloader_orig_speechd
#define spd_set_voice_rate_all spd_set_voice_rate_all_dylibloader_orig_speechd
#define spd_set_voice_rate_uid spd_set_voice_rate_uid_dylibloader_orig_speechd
#define spd_get_voice_rate spd_get_voice_rate_dylibloader_orig_speechd
#define spd_set_voice_pitch spd_set_voice_pitch_dylibloader_orig_speechd
#define spd_set_voice_pitch_all spd_set_voice_pitch_all_dylibloader_orig_speechd
#define spd_set_voice_pitch_uid spd_set_voice_pitch_uid_dylibloader_orig_speechd
#define spd_get_voice_pitch spd_get_voice_pitch_dylibloader_orig_speechd
#define spd_set_volume spd_set_volume_dylibloader_orig_speechd
#define spd_set_volume_all spd_set_volume_all_dylibloader_orig_speechd
#define spd_set_volume_uid spd_set_volume_uid_dylibloader_orig_speechd
#define spd_get_volume spd_get_volume_dylibloader_orig_speechd
#define spd_set_punctuation spd_set_punctuation_dylibloader_orig_speechd
#define spd_set_punctuation_all spd_set_punctuation_all_dylibloader_orig_speechd
#define spd_set_punctuation_uid spd_set_punctuation_uid_dylibloader_orig_speechd
#define spd_set_capital_letters spd_set_capital_letters_dylibloader_orig_speechd
#define spd_set_capital_letters_all spd_set_capital_letters_all_dylibloader_orig_speechd
#define spd_set_capital_letters_uid spd_set_capital_letters_uid_dylibloader_orig_speechd
#define spd_set_spelling spd_set_spelling_dylibloader_orig_speechd
#define spd_set_spelling_all spd_set_spelling_all_dylibloader_orig_speechd
#define spd_set_spelling_uid spd_set_spelling_uid_dylibloader_orig_speechd
#define spd_set_language spd_set_language_dylibloader_orig_speechd
#define spd_set_language_all spd_set_language_all_dylibloader_orig_speechd
#define spd_set_language_uid spd_set_language_uid_dylibloader_orig_speechd
#define spd_get_language spd_get_language_dylibloader_orig_speechd
#define spd_set_output_module spd_set_output_module_dylibloader_orig_speechd
#define spd_set_output_module_all spd_set_output_module_all_dylibloader_orig_speechd
#define spd_set_output_module_uid spd_set_output_module_uid_dylibloader_orig_speechd
#define spd_get_message_list_fd spd_get_message_list_fd_dylibloader_orig_speechd
#define spd_list_modules spd_list_modules_dylibloader_orig_speechd
#define free_spd_modules free_spd_modules_dylibloader_orig_speechd
#define spd_get_output_module spd_get_output_module_dylibloader_orig_speechd
#define spd_list_voices spd_list_voices_dylibloader_orig_speechd
#define spd_list_synthesis_voices spd_list_synthesis_voices_dylibloader_orig_speechd
#define free_spd_voices free_spd_voices_dylibloader_orig_speechd
#define spd_execute_command_with_list_reply spd_execute_command_with_list_reply_dylibloader_orig_speechd
#define spd_execute_command spd_execute_command_dylibloader_orig_speechd
#define spd_execute_command_with_reply spd_execute_command_with_reply_dylibloader_orig_speechd
#define spd_execute_command_wo_mutex spd_execute_command_wo_mutex_dylibloader_orig_speechd
#define spd_send_data spd_send_data_dylibloader_orig_speechd
#define spd_send_data_wo_mutex spd_send_data_wo_mutex_dylibloader_orig_speechd
#include "thirdparty/linuxbsd_headers/speechd/libspeechd.h" // IWYU pragma: export.
#undef SPDConnectionAddress__free
#undef spd_get_default_address
#undef spd_open
#undef spd_open2
#undef spd_close
#undef spd_say
#undef spd_sayf
#undef spd_stop
#undef spd_stop_all
#undef spd_stop_uid
#undef spd_cancel
#undef spd_cancel_all
#undef spd_cancel_uid
#undef spd_pause
#undef spd_pause_all
#undef spd_pause_uid
#undef spd_resume
#undef spd_resume_all
#undef spd_resume_uid
#undef spd_key
#undef spd_char
#undef spd_wchar
#undef spd_sound_icon
#undef spd_set_voice_type
#undef spd_set_voice_type_all
#undef spd_set_voice_type_uid
#undef spd_get_voice_type
#undef spd_set_synthesis_voice
#undef spd_set_synthesis_voice_all
#undef spd_set_synthesis_voice_uid
#undef spd_set_data_mode
#undef spd_set_notification_on
#undef spd_set_notification_off
#undef spd_set_notification
#undef spd_set_voice_rate
#undef spd_set_voice_rate_all
#undef spd_set_voice_rate_uid
#undef spd_get_voice_rate
#undef spd_set_voice_pitch
#undef spd_set_voice_pitch_all
#undef spd_set_voice_pitch_uid
#undef spd_get_voice_pitch
#undef spd_set_volume
#undef spd_set_volume_all
#undef spd_set_volume_uid
#undef spd_get_volume
#undef spd_set_punctuation
#undef spd_set_punctuation_all
#undef spd_set_punctuation_uid
#undef spd_set_capital_letters
#undef spd_set_capital_letters_all
#undef spd_set_capital_letters_uid
#undef spd_set_spelling
#undef spd_set_spelling_all
#undef spd_set_spelling_uid
#undef spd_set_language
#undef spd_set_language_all
#undef spd_set_language_uid
#undef spd_get_language
#undef spd_set_output_module
#undef spd_set_output_module_all
#undef spd_set_output_module_uid
#undef spd_get_message_list_fd
#undef spd_list_modules
#undef free_spd_modules
#undef spd_get_output_module
#undef spd_list_voices
#undef spd_list_synthesis_voices
#undef free_spd_voices
#undef spd_execute_command_with_list_reply
#undef spd_execute_command
#undef spd_execute_command_with_reply
#undef spd_execute_command_wo_mutex
#undef spd_send_data
#undef spd_send_data_wo_mutex
#include <dlfcn.h>
#include <stdio.h>
void (*SPDConnectionAddress__free_dylibloader_wrapper_speechd)(SPDConnectionAddress *);
SPDConnectionAddress *(*spd_get_default_address_dylibloader_wrapper_speechd)(char **);
SPDConnection *(*spd_open_dylibloader_wrapper_speechd)(const char *, const char *, const char *, SPDConnectionMode);
SPDConnection *(*spd_open2_dylibloader_wrapper_speechd)(const char *, const char *, const char *, SPDConnectionMode, SPDConnectionAddress *, int, char **);
void (*spd_close_dylibloader_wrapper_speechd)(SPDConnection *);
int (*spd_say_dylibloader_wrapper_speechd)(SPDConnection *, SPDPriority, const char *);
int (*spd_sayf_dylibloader_wrapper_speechd)(SPDConnection *, SPDPriority, const char *, ...);
int (*spd_stop_dylibloader_wrapper_speechd)(SPDConnection *);
int (*spd_stop_all_dylibloader_wrapper_speechd)(SPDConnection *);
int (*spd_stop_uid_dylibloader_wrapper_speechd)(SPDConnection *, int);
int (*spd_cancel_dylibloader_wrapper_speechd)(SPDConnection *);
int (*spd_cancel_all_dylibloader_wrapper_speechd)(SPDConnection *);
int (*spd_cancel_uid_dylibloader_wrapper_speechd)(SPDConnection *, int);
int (*spd_pause_dylibloader_wrapper_speechd)(SPDConnection *);
int (*spd_pause_all_dylibloader_wrapper_speechd)(SPDConnection *);
int (*spd_pause_uid_dylibloader_wrapper_speechd)(SPDConnection *, int);
int (*spd_resume_dylibloader_wrapper_speechd)(SPDConnection *);
int (*spd_resume_all_dylibloader_wrapper_speechd)(SPDConnection *);
int (*spd_resume_uid_dylibloader_wrapper_speechd)(SPDConnection *, int);
int (*spd_key_dylibloader_wrapper_speechd)(SPDConnection *, SPDPriority, const char *);
int (*spd_char_dylibloader_wrapper_speechd)(SPDConnection *, SPDPriority, const char *);
int (*spd_wchar_dylibloader_wrapper_speechd)(SPDConnection *, SPDPriority, wchar_t);
int (*spd_sound_icon_dylibloader_wrapper_speechd)(SPDConnection *, SPDPriority, const char *);
int (*spd_set_voice_type_dylibloader_wrapper_speechd)(SPDConnection *, SPDVoiceType);
int (*spd_set_voice_type_all_dylibloader_wrapper_speechd)(SPDConnection *, SPDVoiceType);
int (*spd_set_voice_type_uid_dylibloader_wrapper_speechd)(SPDConnection *, SPDVoiceType, unsigned int);
SPDVoiceType (*spd_get_voice_type_dylibloader_wrapper_speechd)(SPDConnection *);
int (*spd_set_synthesis_voice_dylibloader_wrapper_speechd)(SPDConnection *, const char *);
int (*spd_set_synthesis_voice_all_dylibloader_wrapper_speechd)(SPDConnection *, const char *);
int (*spd_set_synthesis_voice_uid_dylibloader_wrapper_speechd)(SPDConnection *, const char *, unsigned int);
int (*spd_set_data_mode_dylibloader_wrapper_speechd)(SPDConnection *, SPDDataMode);
int (*spd_set_notification_on_dylibloader_wrapper_speechd)(SPDConnection *, SPDNotification);
int (*spd_set_notification_off_dylibloader_wrapper_speechd)(SPDConnection *, SPDNotification);
int (*spd_set_notification_dylibloader_wrapper_speechd)(SPDConnection *, SPDNotification, const char *);
int (*spd_set_voice_rate_dylibloader_wrapper_speechd)(SPDConnection *, signed int);
int (*spd_set_voice_rate_all_dylibloader_wrapper_speechd)(SPDConnection *, signed int);
int (*spd_set_voice_rate_uid_dylibloader_wrapper_speechd)(SPDConnection *, signed int, unsigned int);
int (*spd_get_voice_rate_dylibloader_wrapper_speechd)(SPDConnection *);
int (*spd_set_voice_pitch_dylibloader_wrapper_speechd)(SPDConnection *, signed int);
int (*spd_set_voice_pitch_all_dylibloader_wrapper_speechd)(SPDConnection *, signed int);
int (*spd_set_voice_pitch_uid_dylibloader_wrapper_speechd)(SPDConnection *, signed int, unsigned int);
int (*spd_get_voice_pitch_dylibloader_wrapper_speechd)(SPDConnection *);
int (*spd_set_volume_dylibloader_wrapper_speechd)(SPDConnection *, signed int);
int (*spd_set_volume_all_dylibloader_wrapper_speechd)(SPDConnection *, signed int);
int (*spd_set_volume_uid_dylibloader_wrapper_speechd)(SPDConnection *, signed int, unsigned int);
int (*spd_get_volume_dylibloader_wrapper_speechd)(SPDConnection *);
int (*spd_set_punctuation_dylibloader_wrapper_speechd)(SPDConnection *, SPDPunctuation);
int (*spd_set_punctuation_all_dylibloader_wrapper_speechd)(SPDConnection *, SPDPunctuation);
int (*spd_set_punctuation_uid_dylibloader_wrapper_speechd)(SPDConnection *, SPDPunctuation, unsigned int);
int (*spd_set_capital_letters_dylibloader_wrapper_speechd)(SPDConnection *, SPDCapitalLetters);
int (*spd_set_capital_letters_all_dylibloader_wrapper_speechd)(SPDConnection *, SPDCapitalLetters);
int (*spd_set_capital_letters_uid_dylibloader_wrapper_speechd)(SPDConnection *, SPDCapitalLetters, unsigned int);
int (*spd_set_spelling_dylibloader_wrapper_speechd)(SPDConnection *, SPDSpelling);
int (*spd_set_spelling_all_dylibloader_wrapper_speechd)(SPDConnection *, SPDSpelling);
int (*spd_set_spelling_uid_dylibloader_wrapper_speechd)(SPDConnection *, SPDSpelling, unsigned int);
int (*spd_set_language_dylibloader_wrapper_speechd)(SPDConnection *, const char *);
int (*spd_set_language_all_dylibloader_wrapper_speechd)(SPDConnection *, const char *);
int (*spd_set_language_uid_dylibloader_wrapper_speechd)(SPDConnection *, const char *, unsigned int);
char *(*spd_get_language_dylibloader_wrapper_speechd)(SPDConnection *);
int (*spd_set_output_module_dylibloader_wrapper_speechd)(SPDConnection *, const char *);
int (*spd_set_output_module_all_dylibloader_wrapper_speechd)(SPDConnection *, const char *);
int (*spd_set_output_module_uid_dylibloader_wrapper_speechd)(SPDConnection *, const char *, unsigned int);
int (*spd_get_message_list_fd_dylibloader_wrapper_speechd)(SPDConnection *, int, int *, char **);
char **(*spd_list_modules_dylibloader_wrapper_speechd)(SPDConnection *);
void (*free_spd_modules_dylibloader_wrapper_speechd)(char **);
char *(*spd_get_output_module_dylibloader_wrapper_speechd)(SPDConnection *);
char **(*spd_list_voices_dylibloader_wrapper_speechd)(SPDConnection *);
SPDVoice **(*spd_list_synthesis_voices_dylibloader_wrapper_speechd)(SPDConnection *);
void (*free_spd_voices_dylibloader_wrapper_speechd)(SPDVoice **);
char **(*spd_execute_command_with_list_reply_dylibloader_wrapper_speechd)(SPDConnection *, char *);
int (*spd_execute_command_dylibloader_wrapper_speechd)(SPDConnection *, char *);
int (*spd_execute_command_with_reply_dylibloader_wrapper_speechd)(SPDConnection *, char *, char **);
int (*spd_execute_command_wo_mutex_dylibloader_wrapper_speechd)(SPDConnection *, char *);
char *(*spd_send_data_dylibloader_wrapper_speechd)(SPDConnection *, const char *, int);
char *(*spd_send_data_wo_mutex_dylibloader_wrapper_speechd)(SPDConnection *, const char *, int);
int initialize_speechd(int verbose) {
  void *handle;
  char *error;
#if defined(__OpenBSD__) || defined(__NetBSD__)
  handle = dlopen("libspeechd.so", RTLD_LAZY);
#else
  handle = dlopen("libspeechd.so.2", RTLD_LAZY);
#endif
  if (!handle) {
    if (verbose) {
      fprintf(stderr, "%s\n", dlerror());
    }
    return(1);
  }
  dlerror();
// SPDConnectionAddress__free
  {
    void *tmp_dlsym = dlsym(handle, "SPDConnectionAddress__free");
    __builtin_memcpy(&SPDConnectionAddress__free_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_get_default_address
  {
    void *tmp_dlsym = dlsym(handle, "spd_get_default_address");
    __builtin_memcpy(&spd_get_default_address_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_open
  {
    void *tmp_dlsym = dlsym(handle, "spd_open");
    __builtin_memcpy(&spd_open_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_open2
  {
    void *tmp_dlsym = dlsym(handle, "spd_open2");
    __builtin_memcpy(&spd_open2_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_close
  {
    void *tmp_dlsym = dlsym(handle, "spd_close");
    __builtin_memcpy(&spd_close_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_say
  {
    void *tmp_dlsym = dlsym(handle, "spd_say");
    __builtin_memcpy(&spd_say_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_sayf
  {
    void *tmp_dlsym = dlsym(handle, "spd_sayf");
    __builtin_memcpy(&spd_sayf_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_stop
  {
    void *tmp_dlsym = dlsym(handle, "spd_stop");
    __builtin_memcpy(&spd_stop_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_stop_all
  {
    void *tmp_dlsym = dlsym(handle, "spd_stop_all");
    __builtin_memcpy(&spd_stop_all_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_stop_uid
  {
    void *tmp_dlsym = dlsym(handle, "spd_stop_uid");
    __builtin_memcpy(&spd_stop_uid_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_cancel
  {
    void *tmp_dlsym = dlsym(handle, "spd_cancel");
    __builtin_memcpy(&spd_cancel_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_cancel_all
  {
    void *tmp_dlsym = dlsym(handle, "spd_cancel_all");
    __builtin_memcpy(&spd_cancel_all_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_cancel_uid
  {
    void *tmp_dlsym = dlsym(handle, "spd_cancel_uid");
    __builtin_memcpy(&spd_cancel_uid_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_pause
  {
    void *tmp_dlsym = dlsym(handle, "spd_pause");
    __builtin_memcpy(&spd_pause_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_pause_all
  {
    void *tmp_dlsym = dlsym(handle, "spd_pause_all");
    __builtin_memcpy(&spd_pause_all_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_pause_uid
  {
    void *tmp_dlsym = dlsym(handle, "spd_pause_uid");
    __builtin_memcpy(&spd_pause_uid_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_resume
  {
    void *tmp_dlsym = dlsym(handle, "spd_resume");
    __builtin_memcpy(&spd_resume_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_resume_all
  {
    void *tmp_dlsym = dlsym(handle, "spd_resume_all");
    __builtin_memcpy(&spd_resume_all_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_resume_uid
  {
    void *tmp_dlsym = dlsym(handle, "spd_resume_uid");
    __builtin_memcpy(&spd_resume_uid_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_key
  {
    void *tmp_dlsym = dlsym(handle, "spd_key");
    __builtin_memcpy(&spd_key_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_char
  {
    void *tmp_dlsym = dlsym(handle, "spd_char");
    __builtin_memcpy(&spd_char_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_wchar
  {
    void *tmp_dlsym = dlsym(handle, "spd_wchar");
    __builtin_memcpy(&spd_wchar_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_sound_icon
  {
    void *tmp_dlsym = dlsym(handle, "spd_sound_icon");
    __builtin_memcpy(&spd_sound_icon_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_set_voice_type
  {
    void *tmp_dlsym = dlsym(handle, "spd_set_voice_type");
    __builtin_memcpy(&spd_set_voice_type_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_set_voice_type_all
  {
    void *tmp_dlsym = dlsym(handle, "spd_set_voice_type_all");
    __builtin_memcpy(&spd_set_voice_type_all_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_set_voice_type_uid
  {
    void *tmp_dlsym = dlsym(handle, "spd_set_voice_type_uid");
    __builtin_memcpy(&spd_set_voice_type_uid_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_get_voice_type
  {
    void *tmp_dlsym = dlsym(handle, "spd_get_voice_type");
    __builtin_memcpy(&spd_get_voice_type_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_set_synthesis_voice
  {
    void *tmp_dlsym = dlsym(handle, "spd_set_synthesis_voice");
    __builtin_memcpy(&spd_set_synthesis_voice_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_set_synthesis_voice_all
  {
    void *tmp_dlsym = dlsym(handle, "spd_set_synthesis_voice_all");
    __builtin_memcpy(&spd_set_synthesis_voice_all_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_set_synthesis_voice_uid
  {
    void *tmp_dlsym = dlsym(handle, "spd_set_synthesis_voice_uid");
    __builtin_memcpy(&spd_set_synthesis_voice_uid_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_set_data_mode
  {
    void *tmp_dlsym = dlsym(handle, "spd_set_data_mode");
    __builtin_memcpy(&spd_set_data_mode_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_set_notification_on
  {
    void *tmp_dlsym = dlsym(handle, "spd_set_notification_on");
    __builtin_memcpy(&spd_set_notification_on_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_set_notification_off
  {
    void *tmp_dlsym = dlsym(handle, "spd_set_notification_off");
    __builtin_memcpy(&spd_set_notification_off_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_set_notification
  {
    void *tmp_dlsym = dlsym(handle, "spd_set_notification");
    __builtin_memcpy(&spd_set_notification_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_set_voice_rate
  {
    void *tmp_dlsym = dlsym(handle, "spd_set_voice_rate");
    __builtin_memcpy(&spd_set_voice_rate_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_set_voice_rate_all
  {
    void *tmp_dlsym = dlsym(handle, "spd_set_voice_rate_all");
    __builtin_memcpy(&spd_set_voice_rate_all_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_set_voice_rate_uid
  {
    void *tmp_dlsym = dlsym(handle, "spd_set_voice_rate_uid");
    __builtin_memcpy(&spd_set_voice_rate_uid_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_get_voice_rate
  {
    void *tmp_dlsym = dlsym(handle, "spd_get_voice_rate");
    __builtin_memcpy(&spd_get_voice_rate_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_set_voice_pitch
  {
    void *tmp_dlsym = dlsym(handle, "spd_set_voice_pitch");
    __builtin_memcpy(&spd_set_voice_pitch_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_set_voice_pitch_all
  {
    void *tmp_dlsym = dlsym(handle, "spd_set_voice_pitch_all");
    __builtin_memcpy(&spd_set_voice_pitch_all_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_set_voice_pitch_uid
  {
    void *tmp_dlsym = dlsym(handle, "spd_set_voice_pitch_uid");
    __builtin_memcpy(&spd_set_voice_pitch_uid_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_get_voice_pitch
  {
    void *tmp_dlsym = dlsym(handle, "spd_get_voice_pitch");
    __builtin_memcpy(&spd_get_voice_pitch_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_set_volume
  {
    void *tmp_dlsym = dlsym(handle, "spd_set_volume");
    __builtin_memcpy(&spd_set_volume_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_set_volume_all
  {
    void *tmp_dlsym = dlsym(handle, "spd_set_volume_all");
    __builtin_memcpy(&spd_set_volume_all_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_set_volume_uid
  {
    void *tmp_dlsym = dlsym(handle, "spd_set_volume_uid");
    __builtin_memcpy(&spd_set_volume_uid_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_get_volume
  {
    void *tmp_dlsym = dlsym(handle, "spd_get_volume");
    __builtin_memcpy(&spd_get_volume_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_set_punctuation
  {
    void *tmp_dlsym = dlsym(handle, "spd_set_punctuation");
    __builtin_memcpy(&spd_set_punctuation_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_set_punctuation_all
  {
    void *tmp_dlsym = dlsym(handle, "spd_set_punctuation_all");
    __builtin_memcpy(&spd_set_punctuation_all_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_set_punctuation_uid
  {
    void *tmp_dlsym = dlsym(handle, "spd_set_punctuation_uid");
    __builtin_memcpy(&spd_set_punctuation_uid_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_set_capital_letters
  {
    void *tmp_dlsym = dlsym(handle, "spd_set_capital_letters");
    __builtin_memcpy(&spd_set_capital_letters_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_set_capital_letters_all
  {
    void *tmp_dlsym = dlsym(handle, "spd_set_capital_letters_all");
    __builtin_memcpy(&spd_set_capital_letters_all_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_set_capital_letters_uid
  {
    void *tmp_dlsym = dlsym(handle, "spd_set_capital_letters_uid");
    __builtin_memcpy(&spd_set_capital_letters_uid_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_set_spelling
  {
    void *tmp_dlsym = dlsym(handle, "spd_set_spelling");
    __builtin_memcpy(&spd_set_spelling_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_set_spelling_all
  {
    void *tmp_dlsym = dlsym(handle, "spd_set_spelling_all");
    __builtin_memcpy(&spd_set_spelling_all_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_set_spelling_uid
  {
    void *tmp_dlsym = dlsym(handle, "spd_set_spelling_uid");
    __builtin_memcpy(&spd_set_spelling_uid_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_set_language
  {
    void *tmp_dlsym = dlsym(handle, "spd_set_language");
    __builtin_memcpy(&spd_set_language_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_set_language_all
  {
    void *tmp_dlsym = dlsym(handle, "spd_set_language_all");
    __builtin_memcpy(&spd_set_language_all_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_set_language_uid
  {
    void *tmp_dlsym = dlsym(handle, "spd_set_language_uid");
    __builtin_memcpy(&spd_set_language_uid_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_get_language
  {
    void *tmp_dlsym = dlsym(handle, "spd_get_language");
    __builtin_memcpy(&spd_get_language_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_set_output_module
  {
    void *tmp_dlsym = dlsym(handle, "spd_set_output_module");
    __builtin_memcpy(&spd_set_output_module_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_set_output_module_all
  {
    void *tmp_dlsym = dlsym(handle, "spd_set_output_module_all");
    __builtin_memcpy(&spd_set_output_module_all_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_set_output_module_uid
  {
    void *tmp_dlsym = dlsym(handle, "spd_set_output_module_uid");
    __builtin_memcpy(&spd_set_output_module_uid_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_get_message_list_fd
  {
    void *tmp_dlsym = dlsym(handle, "spd_get_message_list_fd");
    __builtin_memcpy(&spd_get_message_list_fd_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_list_modules
  {
    void *tmp_dlsym = dlsym(handle, "spd_list_modules");
    __builtin_memcpy(&spd_list_modules_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// free_spd_modules
  {
    void *tmp_dlsym = dlsym(handle, "free_spd_modules");
    __builtin_memcpy(&free_spd_modules_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_get_output_module
  {
    void *tmp_dlsym = dlsym(handle, "spd_get_output_module");
    __builtin_memcpy(&spd_get_output_module_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_list_voices
  {
    void *tmp_dlsym = dlsym(handle, "spd_list_voices");
    __builtin_memcpy(&spd_list_voices_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_list_synthesis_voices
  {
    void *tmp_dlsym = dlsym(handle, "spd_list_synthesis_voices");
    __builtin_memcpy(&spd_list_synthesis_voices_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// free_spd_voices
  {
    void *tmp_dlsym = dlsym(handle, "free_spd_voices");
    __builtin_memcpy(&free_spd_voices_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_execute_command_with_list_reply
  {
    void *tmp_dlsym = dlsym(handle, "spd_execute_command_with_list_reply");
    __builtin_memcpy(&spd_execute_command_with_list_reply_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_execute_command
  {
    void *tmp_dlsym = dlsym(handle, "spd_execute_command");
    __builtin_memcpy(&spd_execute_command_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_execute_command_with_reply
  {
    void *tmp_dlsym = dlsym(handle, "spd_execute_command_with_reply");
    __builtin_memcpy(&spd_execute_command_with_reply_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_execute_command_wo_mutex
  {
    void *tmp_dlsym = dlsym(handle, "spd_execute_command_wo_mutex");
    __builtin_memcpy(&spd_execute_command_wo_mutex_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_send_data
  {
    void *tmp_dlsym = dlsym(handle, "spd_send_data");
    __builtin_memcpy(&spd_send_data_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
// spd_send_data_wo_mutex
  {
    void *tmp_dlsym = dlsym(handle, "spd_send_data_wo_mutex");
    __builtin_memcpy(&spd_send_data_wo_mutex_dylibloader_wrapper_speechd, &tmp_dlsym, sizeof(void *));
  }
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
    }
  }
return 0;
}
